"""Tests for release_bot's github_client checklist/version helpers."""

import github_client as github

CHECKLIST_BODY = """## Release 2026.7.22.1

### Changes

- [ ] `abc1234` chore: bump version by bot@example.com
- [x] **fix: real bug** (#5) by human@example.com

---
*This release was automatically generated by the Concourse release pipeline.*
*Closing this issue will trigger the production deployment.*
"""

FULLY_CHECKED_BODY = CHECKLIST_BODY.replace(
    "- [ ] `abc1234` chore: bump version by bot@example.com",
    "- [x] `abc1234` chore: bump version by bot@example.com",
)

UPPERCASE_CHECKED_BODY = CHECKLIST_BODY.replace(
    "- [ ] `abc1234` chore: bump version by bot@example.com",
    "- [X] `abc1234` chore: bump version by bot@example.com",
)

NO_CHECKLIST_BODY = "Just some notes, no checklist here."


def test_checklist_status_counts_checked_and_total():
    """One of two checklist lines is checked."""
    checked, total = github.checklist_status(CHECKLIST_BODY)
    assert checked == 1
    assert total == 2


def test_checklist_status_empty_body_is_zero_zero():
    """A body with no checklist lines reports (0, 0)."""
    assert github.checklist_status(NO_CHECKLIST_BODY) == (0, 0)


def test_is_fully_checked_false_when_any_line_unchecked():
    """Not fully checked while at least one line is unchecked."""
    assert github.is_fully_checked(CHECKLIST_BODY) is False


def test_is_fully_checked_true_when_all_lines_checked():
    """Fully checked once every checklist line is checked."""
    assert github.is_fully_checked(FULLY_CHECKED_BODY) is True


def test_checklist_status_counts_uppercase_x_as_checked():
    """GitHub treats "[X]" (uppercase) the same as "[x]" -- so must we."""
    checked, total = github.checklist_status(UPPERCASE_CHECKED_BODY)
    assert checked == 2
    assert total == 2
    assert github.is_fully_checked(UPPERCASE_CHECKED_BODY) is True


def test_is_fully_checked_false_when_no_checklist_lines():
    """A body with zero checklist lines is never "ready" -- nothing to check."""
    assert github.is_fully_checked(NO_CHECKLIST_BODY) is False


def test_extract_version_finds_release_header():
    """Version is parsed from the "## Release X" header."""
    assert github.extract_version(CHECKLIST_BODY) == "2026.7.22.1"


def test_extract_version_returns_none_without_header():
    """No version header present -- returns None."""
    assert github.extract_version(NO_CHECKLIST_BODY) is None
