"""Nightly assertion run over the alerting config Pulumi cannot manage.

`bin/alerting-drift-check` compares live Sentry metric alert rules, Rootly
route rules, and Grafana contact-point delivery state against expectations
recorded in the script, and reports anything that has moved. This job runs it
nightly and, when the report's content has changed since the last run, commits
it to `docs/generated/alerting-drift-report.md` and opens or updates a pull
request carrying the diff.

Same shape and same credentials as `github_drift`, deliberately: this is the
second scheduled "assert live state nobody can express in IaC" check, and one
mechanism serving both beats two. A pull request is the visibility mechanism
because a red Concourse build is not one -- nobody is subscribed to this
pipeline, and the whole reason these checks exist is that alerting failures
went unnoticed for weeks.

The report is written to be stable between runs: no day counts, no event
volumes, nothing that moves on its own. A diff therefore means something in
the alerting control plane actually changed.

Findings are not applied automatically. Every check here covers config the
Pulumi providers cannot fully represent, and auto-repairing that is what
produced the empty-shell rules in the first place -- reconciling a finding is
a human call.

Credentials:

- The check decrypts `src/bridge/secrets/{sentry,rootly,grafana_cloud}/*.yaml`
  through the same sops/KMS path every `pulumi_job()` step on this pool
  already uses. No new credential to provision.
- Pushing the branch and opening the PR uses the same dedicated
  `((github.drift_pr_app_id))` / `((github.drift_pr_app_installation_id))` /
  `((github.drift_pr_app_pem))` credential `iam_drift` and `github_drift`
  already rely on.
"""

import sys

from ol_concourse.lib.constants import REGISTRY_IMAGE
from ol_concourse.lib.models.pipeline import (
    AnonymousResource,
    Command,
    GetStep,
    Identifier,
    Input,
    Job,
    Pipeline,
    Platform,
    TaskConfig,
    TaskStep,
)
from ol_concourse.lib.resources import git_repo, schedule

from ol_concourse.pipelines.constants import ECR_REGION, dockerhub_ecr_image_uri

GITHUB_REPOSITORY = "mitodl/ol-infrastructure"
GITHUB_APP_ID_VAULT_PATH = "((github.drift_pr_app_id))"
GITHUB_APP_INSTALLATION_ID_VAULT_PATH = "((github.drift_pr_app_installation_id))"
GITHUB_APP_PRIVATE_KEY_VAULT_PATH = "((github.drift_pr_app_pem))"
REPORT_PATH = "docs/generated/alerting-drift-report.md"
DRIFT_BRANCH = "alerting-drift"

ol_infrastructure = git_repo(
    Identifier("ol-infrastructure"),
    uri=f"https://github.com/{GITHUB_REPOSITORY}",
)

drift_schedule = schedule(
    Identifier("nightly-schedule"),
    interval="24h",
    start="03:00",
    stop="04:00",
)

ol_infrastructure_image = AnonymousResource(
    type=REGISTRY_IMAGE,
    source={
        "repository": dockerhub_ecr_image_uri("mitodl/ol-infrastructure"),
        "tag": "latest",
        "aws_region": ECR_REGION,
    },
)

# The check exits 1 whenever it finds DRIFT (KNOWN and INFO findings exit 0).
# That must not fail the job: a DRIFT finding is the thing this pipeline exists
# to report, and aborting on it would suppress the very report that carries it.
# An unhandled exception also exits 1 and would be indistinguishable by exit
# code alone. The check only ever prints findings to stdout (see its module
# docstring), so a non-empty stderr reliably means it broke; that is checked
# explicitly here so an execution failure aborts before a truncated report gets
# committed as though it were a clean run.
DRIFT_REPORT_COMMAND = (
    f"mkdir -p ol-infrastructure/{REPORT_PATH.rsplit('/', 1)[0]}\n"
    "PYTHONPATH=ol-infrastructure/src python"
    " ol-infrastructure/bin/alerting-drift-check"
    " > /tmp/drift-stdout.txt 2> /tmp/drift-stderr.txt || true\n"
    "if [ -s /tmp/drift-stderr.txt ]; then\n"
    "  echo 'alerting-drift-check failed unexpectedly -- aborting before"
    " writing or pushing a report:' >&2\n"
    "  cat /tmp/drift-stderr.txt >&2\n"
    "  exit 1\n"
    "fi\n"
    "{\n"
    '  echo "# Alerting control-plane drift report"\n'
    "  echo\n"
    '  echo "Nightly assertion over the Sentry alert rules, Rootly route'
    " rules, and Grafana contact points that the Pulumi providers cannot"
    " manage. Generated by the \\`alerting-drift\\` Concourse job -- see"
    " \\`src/ol_concourse/pipelines/infrastructure/alerting_drift/pipeline.py\\`."
    " A DRIFT finding is not auto-repaired: decide whether live or the"
    " expectation recorded in \\`bin/alerting-drift-check\\` is correct, then"
    ' change whichever one is wrong."\n'
    "  echo\n"
    "  echo '```'\n"
    "  cat /tmp/drift-stdout.txt\n"
    "  echo '```'\n"
    f"}} > ol-infrastructure/{REPORT_PATH}\n"
)

# Same reasoning as github_drift's: `open-drift-pr` decides whether to push by
# comparing the full working tree against the remote branch, which changes
# every night here purely because `main` moved. Compare the report file alone
# and only open/update the PR when its content actually changed.
OPEN_PR_COMMAND = (
    "cd ol-infrastructure\n"
    'git config --global --add safe.directory "$(pwd)"\n'
    'REMOTE_REPORT=""\n'
    f"if git ls-remote --exit-code origin refs/heads/{DRIFT_BRANCH}"
    " > /dev/null 2>&1; then\n"
    f"  git fetch --quiet origin refs/heads/{DRIFT_BRANCH}\n"
    f'  REMOTE_REPORT="$(git show "FETCH_HEAD:{REPORT_PATH}" 2>/dev/null'
    ' || true)"\n'
    "fi\n"
    f'if [ "$REMOTE_REPORT" = "$(cat {REPORT_PATH})" ]; then\n'
    '  echo "Report unchanged since the last run on'
    f' {DRIFT_BRANCH}; not pushing."\n'
    "else\n"
    "  cd ..\n"
    "  echo 'Nightly alerting control-plane drift report. See the file diff"
    " for what changed; findings are not applied automatically.'"
    " > /tmp/pr_body.md\n"
    "  python ol-infrastructure/bin/open-drift-pr"
    " --repo-dir ol-infrastructure"
    f" --repo {GITHUB_REPOSITORY}"
    f" --branch {DRIFT_BRANCH}"
    " --title 'chore(alerting): nightly control-plane drift report'"
    " --body-file /tmp/pr_body.md\n"
    "fi\n"
)


def drift_job() -> Job:
    """Build the run-check-then-propose job."""
    return Job(
        name=Identifier("check-alerting-drift"),
        plan=[
            GetStep(get=drift_schedule.name, trigger=True),
            GetStep(get=ol_infrastructure.name, trigger=False),
            TaskStep(
                task=Identifier("report-alerting-drift"),
                config=TaskConfig(
                    platform=Platform.linux,
                    image_resource=ol_infrastructure_image,
                    inputs=[Input(name=ol_infrastructure.name)],
                    params={
                        "GITHUB_APP_ID": GITHUB_APP_ID_VAULT_PATH,
                        "GITHUB_APP_INSTALLATION_ID": (
                            GITHUB_APP_INSTALLATION_ID_VAULT_PATH
                        ),
                        "GITHUB_APP_PRIVATE_KEY": GITHUB_APP_PRIVATE_KEY_VAULT_PATH,
                    },
                    run=Command(
                        user="root",
                        path="sh",
                        args=["-exc", DRIFT_REPORT_COMMAND + OPEN_PR_COMMAND],
                    ),
                ),
            ),
        ],
    )


def alerting_drift_pipeline() -> Pipeline:
    return Pipeline(
        resources=[drift_schedule, ol_infrastructure],
        jobs=[drift_job()],
    )


if __name__ == "__main__":
    definition_json = alerting_drift_pipeline().model_dump_json(indent=2)
    with open("definition.json", "w") as definition:  # noqa: PTH123
        definition.write(definition_json)
    sys.stdout.write(definition_json)
    print()  # noqa: T201
    print("fly -t pr-inf sp -p alerting-drift -c definition.json")  # noqa: T201
