from enum import Enum

from bridge.settings.openedx.types import (
    DeploymentEnvRelease,
    EnvRelease,
    OpenEdxApplicationVersion,
    OpenEdxDeploymentName,
    OpenEdxSupportedRelease,
)


class OpenLearningOpenEdxDeployment(Enum):
    mitx = DeploymentEnvRelease(
        deployment_name="mitx",
        env_release_map=[
            # Residential environments want to track master in CI for testing new
            # features as they land. (TMM 2025-05-20)
            EnvRelease("CI", OpenEdxSupportedRelease["master"]),
            EnvRelease("QA", OpenEdxSupportedRelease["ulmo"]),
            EnvRelease("Production", OpenEdxSupportedRelease["teak"]),
        ],
    )
    mitx_staging = DeploymentEnvRelease(
        deployment_name="mitx-staging",
        env_release_map=[
            # Residential environments want to track master in CI for testing new
            # features as they land. (TMM 2025-05-20)
            EnvRelease("CI", OpenEdxSupportedRelease["master"]),
            EnvRelease("QA", OpenEdxSupportedRelease["ulmo"]),
            EnvRelease("Production", OpenEdxSupportedRelease["teak"]),
        ],
    )
    mitxonline = DeploymentEnvRelease(
        deployment_name="mitxonline",
        env_release_map=[
            EnvRelease("CI", OpenEdxSupportedRelease["master"]),
            EnvRelease("QA", OpenEdxSupportedRelease["master"]),
            EnvRelease("Production", OpenEdxSupportedRelease["master"]),
        ],
    )
    xpro = DeploymentEnvRelease(
        deployment_name="xpro",
        env_release_map=[
            EnvRelease("CI", OpenEdxSupportedRelease["ulmo"]),
            EnvRelease("QA", OpenEdxSupportedRelease["teak"]),
            EnvRelease("Production", OpenEdxSupportedRelease["teak"]),
        ],
    )

    @classmethod
    def get_item(cls, key: OpenEdxDeploymentName) -> DeploymentEnvRelease:
        deployment_name_map = {
            "mitx": cls.mitx,
            "mitx-staging": cls.mitx_staging,
            "mitxonline": cls.mitxonline,
            "xpro": cls.xpro,
        }
        try:
            deployment = cls[key]
        except KeyError:
            deployment = deployment_name_map[key]
        return deployment.value


ReleaseMap: dict[
    OpenEdxSupportedRelease,
    dict[OpenEdxDeploymentName, list[OpenEdxApplicationVersion]],
] = {
    "teak": {
        "mitx": [
            OpenEdxApplicationVersion(
                application="codejail",
                application_type="IDA",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="communications",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="authoring",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="discussions",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="edx-platform",
                application_type="IDA",
                release="teak",
                branch_override="mitx/teak",
                origin_override="https://github.com/mitodl/edx-platform",
                runtime_version_override="3.11",
            ),
            OpenEdxApplicationVersion(
                application="edxapp_theme",
                application_type="IDA",
                release="teak",
                branch_override="teak",
                origin_override="https://github.com/mitodl/mitx-theme",
            ),
            OpenEdxApplicationVersion(
                application="forum",
                application_type="IDA",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="gradebook",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="learner-dashboard",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="learning",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="notes-api",
                application_type="IDA",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="ora-grading",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="xqueue",
                application_type="IDA",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="xqwatcher",
                application_type="IDA",
                branch_override="master",
                origin_override="https://github.com/mitodl/xqueue-watcher",
                release="teak",
            ),
        ],
        "mitx-staging": [
            OpenEdxApplicationVersion(
                application="codejail",
                application_type="IDA",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="communications",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="authoring",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="discussions",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="edx-platform",
                application_type="IDA",
                release="teak",
                branch_override="mitx/teak",
                origin_override="https://github.com/mitodl/edx-platform",
                runtime_version_override="3.11",
            ),
            OpenEdxApplicationVersion(
                application="edxapp_theme",
                application_type="IDA",
                release="teak",
                branch_override="teak",
                origin_override="https://github.com/mitodl/mitx-theme",
            ),
            OpenEdxApplicationVersion(
                application="forum",
                application_type="IDA",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="gradebook",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="learning",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="learner-dashboard",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="notes-api",
                application_type="IDA",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="ora-grading",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="xqueue",
                application_type="IDA",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="xqwatcher",
                application_type="IDA",
                branch_override="master",
                origin_override="https://github.com/mitodl/xqueue-watcher",
                release="teak",
            ),
        ],
        "xpro": [
            OpenEdxApplicationVersion(
                application="codejail",
                application_type="IDA",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="authoring",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="discussions",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="edx-platform",
                application_type="IDA",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="edxapp_theme",
                application_type="IDA",
                release="teak",
                branch_override="teak",
                origin_override="https://github.com/mitodl/mitxpro-theme",
            ),
            OpenEdxApplicationVersion(
                application="forum",
                application_type="IDA",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="gradebook",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="learning",
                application_type="MFE",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="notes-api",
                application_type="IDA",
                release="teak",
            ),
            OpenEdxApplicationVersion(
                application="ora-grading",
                application_type="MFE",
                release="teak",
            ),
        ],
    },
    "ulmo": {
        "mitx": [
            OpenEdxApplicationVersion(
                application="codejail",
                application_type="IDA",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="communications",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="authoring",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="discussions",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="edx-platform",
                application_type="IDA",
                release="ulmo",
                branch_override="mitx/ulmo",
                origin_override="https://github.com/mitodl/edx-platform",
                runtime_version_override="3.11",
            ),
            OpenEdxApplicationVersion(
                application="edxapp_theme",
                application_type="IDA",
                release="ulmo",
                branch_override="ulmo",
                origin_override="https://github.com/mitodl/mitx-theme",
            ),
            OpenEdxApplicationVersion(
                application="gradebook",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="learner-dashboard",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="learning",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="notes-api",
                application_type="IDA",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="ora-grading",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="xqueue",
                application_type="IDA",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="xqwatcher",
                application_type="IDA",
                branch_override="master",
                origin_override="https://github.com/mitodl/xqueue-watcher",
                release="ulmo",
            ),
        ],
        "mitx-staging": [
            OpenEdxApplicationVersion(
                application="codejail",
                application_type="IDA",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="communications",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="authoring",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="discussions",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="edx-platform",
                application_type="IDA",
                release="ulmo",
                branch_override="mitx/ulmo",
                origin_override="https://github.com/mitodl/edx-platform",
                runtime_version_override="3.11",
            ),
            OpenEdxApplicationVersion(
                application="edxapp_theme",
                application_type="IDA",
                release="ulmo",
                branch_override="ulmo",
                origin_override="https://github.com/mitodl/mitx-theme",
            ),
            OpenEdxApplicationVersion(
                application="gradebook",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="learning",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="learner-dashboard",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="notes-api",
                application_type="IDA",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="ora-grading",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="xqueue",
                application_type="IDA",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="xqwatcher",
                application_type="IDA",
                branch_override="master",
                origin_override="https://github.com/mitodl/xqueue-watcher",
                release="ulmo",
            ),
        ],
        "xpro": [
            OpenEdxApplicationVersion(
                application="codejail",
                application_type="IDA",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="authoring",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="discussions",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="edx-platform",
                application_type="IDA",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="edxapp_theme",
                application_type="IDA",
                release="ulmo",
                branch_override="ulmo",
                origin_override="https://github.com/mitodl/mitxpro-theme",
            ),
            OpenEdxApplicationVersion(
                application="gradebook",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="learning",
                application_type="MFE",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="notes-api",
                application_type="IDA",
                release="ulmo",
            ),
            OpenEdxApplicationVersion(
                application="ora-grading",
                application_type="MFE",
                release="ulmo",
            ),
        ],
    },
    "master": {
        "mitxonline": [
            OpenEdxApplicationVersion(
                application="codejail",
                application_type="IDA",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="communications",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="authoring",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="discussions",
                application_type="MFE",
                release="master",
                origin_override="https://github.com/mitodl/frontend-app-discussions",
                branch_override="tmacey/fix_learner_posts_link",
            ),
            OpenEdxApplicationVersion(
                application="edx-platform",
                application_type="IDA",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="edxapp_theme",
                application_type="IDA",
                release="master",
                branch_override="main",
                origin_override="https://github.com/mitodl/mitxonline-theme",
            ),
            OpenEdxApplicationVersion(
                application="gradebook",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="learning",
                application_type="MFE",
                release="master",
                translation_overrides=[
                    "atlas pull -r mitodl/mitxonline-translations -n main translations/frontend-app-learning/src/i18n/messages:src/i18n/messages/frontend-app-learning",  # noqa: E501
                    "node_modules/@edx/frontend-platform/i18n/scripts/intl-imports.js frontend-app-learning",  # noqa: E501
                ],
            ),
            OpenEdxApplicationVersion(
                application="ora-grading",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="xqueue",
                application_type="IDA",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="xqwatcher",
                application_type="IDA",
                release="master",
            ),
        ],
        "mitx": [
            OpenEdxApplicationVersion(
                application="codejail",
                application_type="IDA",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="communications",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="authoring",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="discussions",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="edx-platform",
                application_type="IDA",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="edxapp_theme",
                application_type="IDA",
                release="master",
                branch_override="master",
                origin_override="https://github.com/mitodl/mitx-theme",
            ),
            OpenEdxApplicationVersion(
                application="gradebook",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="learner-dashboard",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="learning",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="notes-api",
                application_type="IDA",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="ora-grading",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="xqueue",
                application_type="IDA",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="xqwatcher",
                application_type="IDA",
                release="master",
            ),
        ],
        "mitx-staging": [
            OpenEdxApplicationVersion(
                application="codejail",
                application_type="IDA",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="communications",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="authoring",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="discussions",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="edx-platform",
                application_type="IDA",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="edxapp_theme",
                application_type="IDA",
                release="master",
                branch_override="master",
                origin_override="https://github.com/mitodl/mitx-theme",
            ),
            OpenEdxApplicationVersion(
                application="gradebook",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="learning",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="learner-dashboard",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="notes-api",
                application_type="IDA",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="ora-grading",
                application_type="MFE",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="xqueue",
                application_type="IDA",
                release="master",
            ),
            OpenEdxApplicationVersion(
                application="xqwatcher", application_type="IDA", release="master"
            ),
        ],
    },
}
