import ast
from pathlib import Path

import pytest

from ol_infrastructure.lib.fastly import (
    validate_vcl_snippet_name,
    vcl_snippet,
)

SRC_ROOT = Path(__file__).parents[3] / "src"


@pytest.mark.parametrize(
    "name",
    [
        "handle domain redirect",
        "Build cache key from whitelisted query params",
        "Set x-forwarded-host - miss",
        "TTLs setup",
        "a",
        "Strip.header_from-NextJS backend 2",
    ],
)
def test_legal_names_are_accepted(name):
    assert validate_vcl_snippet_name(name) == name


@pytest.mark.parametrize(
    "name",
    [
        "Handle course/program redirects to MIT Learn",  # ol-infrastructure#5513
        "Strip internal cache-key header before backend fetch (miss)",  # #5563
        "Generated by force TLS, change hash keys",  # comma
        "404 page",  # does not start with a letter
        "_leading underscore",
        " leading space",
        "",
    ],
)
def test_illegal_names_are_rejected(name):
    with pytest.raises(ValueError, match="Invalid Fastly VCL snippet name"):
        validate_vcl_snippet_name(name)


def test_vcl_snippet_rejects_illegal_name_before_building_args():
    with pytest.raises(ValueError, match="Invalid Fastly VCL snippet name"):
        vcl_snippet(name="redirect /courses", content="# noop", type="recv")


def test_vcl_snippet_passes_through_arguments():
    snippet = vcl_snippet(
        name="handle domain redirect",
        content="# noop",
        type="recv",
        priority=10,
    )
    assert snippet.name == "handle domain redirect"
    assert snippet.content == "# noop"
    assert snippet.type == "recv"
    assert snippet.priority == 10


def _snippet_calls(tree):
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            func = node.func
            called = (
                func.attr
                if isinstance(func, ast.Attribute)
                else getattr(func, "id", "")
            )
            if called in {"ServiceVclSnippetArgs", "vcl_snippet"}:
                yield called, node


def test_stacks_build_snippets_through_the_validating_helper():
    """A raw ServiceVclSnippetArgs bypasses validation and corrupts state mid-apply."""
    offenders = []
    for source_file in sorted(SRC_ROOT.rglob("*.py")):
        tree = ast.parse(source_file.read_text())
        for called, node in _snippet_calls(tree):
            if called == "ServiceVclSnippetArgs" and source_file.name != "fastly.py":
                offenders.append(f"{source_file}:{node.lineno}")
    assert not offenders


def test_all_snippet_names_in_the_repo_are_legal():
    for source_file in sorted(SRC_ROOT.rglob("*.py")):
        tree = ast.parse(source_file.read_text())
        for _called, node in _snippet_calls(tree):
            for keyword in node.keywords:
                if keyword.arg == "name" and isinstance(keyword.value, ast.Constant):
                    validate_vcl_snippet_name(keyword.value.value)
