"""Nightly drift check for the mitodl GitHub estate (phase 6 of the org import).

`bin/github-estate-audit drift` compares the committed fleet YAML
(`saas/github/repositories/data/repos/*.yaml`) against a fresh crawl of live
GitHub and reports every field that has moved out of band -- a console change
nobody made through Pulumi. This job runs that comparison nightly and, when
the report's content has changed since the last run, commits it to
`docs/generated/github-drift-report.md` and opens or updates a pull request
carrying the diff. It never edits the fleet YAML itself: reconciling a drift
finding (deciding whether live or declared should win) is still a human call,
same as every other phase-5 remediation in this project.

Two separate GitHub App credentials are in play, on purpose -- same boundary
`bin/open-drift-pr`'s own docstring calls out for iam_drift:

- The crawl itself (`github-org-inventory report --refresh` and
  `github-estate-audit drift`) authenticates as `ol-infrastructure-as-code`
  via `ol_infrastructure.lib.github_helper.get_installation_token()`, which
  decrypts `src/bridge/secrets/pulumi/github_app.yaml` through the same
  sops/KMS path every `pulumi_job()` step on this pool already uses -- no new
  credential to provision. That app holds `pull_requests: read`, not
  `write` (see `docs/github-app-permissions.md`), so it cannot open a PR.
- Pushing the branch and opening the PR uses the SAME dedicated
  `((github.drift_pr_app_id))` / `((github.drift_pr_app_installation_id))` /
  `((github.drift_pr_app_pem))` credential iam_drift already relies on --
  already scoped to `contents:write` + `pull_requests:write` on
  `mitodl/ol-infrastructure`, which is the only repo this job ever pushes to
  (the drift *report*, not the 316 org repos it reports on).
"""

import sys

from ol_concourse.lib.constants import REGISTRY_IMAGE
from ol_concourse.lib.models.pipeline import (
    AnonymousResource,
    Command,
    GetStep,
    Identifier,
    Input,
    Job,
    Pipeline,
    Platform,
    TaskConfig,
    TaskStep,
)
from ol_concourse.lib.resources import git_repo, schedule

from ol_concourse.pipelines.constants import ECR_REGION, dockerhub_ecr_image_uri

GITHUB_REPOSITORY = "mitodl/ol-infrastructure"
GITHUB_APP_ID_VAULT_PATH = "((github.drift_pr_app_id))"
GITHUB_APP_INSTALLATION_ID_VAULT_PATH = "((github.drift_pr_app_installation_id))"
GITHUB_APP_PRIVATE_KEY_VAULT_PATH = "((github.drift_pr_app_pem))"
REPORT_PATH = "docs/generated/github-drift-report.md"
DRIFT_BRANCH = "github-estate-drift"

ol_infrastructure = git_repo(
    Identifier("ol-infrastructure"),
    uri=f"https://github.com/{GITHUB_REPOSITORY}",
)

drift_schedule = schedule(
    Identifier("nightly-schedule"),
    interval="24h",
    start="02:00",
    stop="03:00",
)

ol_infrastructure_image = AnonymousResource(
    type=REGISTRY_IMAGE,
    source={
        "repository": dockerhub_ecr_image_uri("mitodl/ol-infrastructure"),
        "tag": "latest",
        "aws_region": ECR_REGION,
    },
)

# Refresh the crawl cache (reads live GitHub, writes nothing to the checkout),
# then diff it against the committed fleet data. `drift` exits 1 when it finds
# anything, which would otherwise abort the script under `set -e` -- `|| true`
# on that one line is deliberate, not a mistake: a non-empty report is the
# expected, useful output of this job, not a failure of it.
DRIFT_REPORT_COMMAND = (
    f"mkdir -p ol-infrastructure/{REPORT_PATH.rsplit('/', 1)[0]}\n"
    "python ol-infrastructure/bin/github-org-inventory report --refresh"
    " --cache /tmp/github-drift-cache.json > /dev/null\n"
    "{\n"
    '  echo "# GitHub estate drift report"\n'
    "  echo\n"
    '  echo "Nightly diff of the committed fleet data in'
    " \\`saas/github/repositories/data/repos/\\` against live GitHub."
    " Generated by the \\`github-estate-drift\\` Concourse job -- see"
    " \\`src/ol_concourse/pipelines/infrastructure/github_drift/pipeline.py\\`."
    " A finding here is not auto-applied: encode the intended value as a"
    " per-repo deviation (if live is correct) or fix it live with"
    " \\`pulumi up\\` (if the committed value is correct), same as any other"
    ' phase-5 remediation."\n'
    "  echo\n"
    "  echo '```'\n"
    "  python ol-infrastructure/bin/github-estate-audit drift"
    " --cache /tmp/github-drift-cache.json || true\n"
    "  echo '```'\n"
    f"}} > ol-infrastructure/{REPORT_PATH}\n"
)

OPEN_PR_COMMAND = (
    "echo 'Nightly GitHub estate drift report. See the file diff for what"
    " changed; findings are not applied automatically.' > /tmp/pr_body.md\n"
    "python ol-infrastructure/bin/open-drift-pr"
    " --repo-dir ol-infrastructure"
    f" --repo {GITHUB_REPOSITORY}"
    f" --branch {DRIFT_BRANCH}"
    " --title 'chore(github): nightly estate drift report'"
    " --body-file /tmp/pr_body.md\n"
)


def drift_job() -> Job:
    return Job(
        name=Identifier("check-github-estate-drift"),
        plan=[
            GetStep(get=drift_schedule.name, trigger=True),
            GetStep(get=ol_infrastructure.name, trigger=False),
            TaskStep(
                task=Identifier("report-github-estate-drift"),
                config=TaskConfig(
                    platform=Platform.linux,
                    image_resource=ol_infrastructure_image,
                    inputs=[Input(name=ol_infrastructure.name)],
                    params={
                        "GITHUB_APP_ID": GITHUB_APP_ID_VAULT_PATH,
                        "GITHUB_APP_INSTALLATION_ID": (
                            GITHUB_APP_INSTALLATION_ID_VAULT_PATH
                        ),
                        "GITHUB_APP_PRIVATE_KEY": GITHUB_APP_PRIVATE_KEY_VAULT_PATH,
                    },
                    run=Command(
                        user="root",
                        path="sh",
                        args=["-exc", DRIFT_REPORT_COMMAND + OPEN_PR_COMMAND],
                    ),
                ),
            ),
        ],
    )


def github_drift_pipeline() -> Pipeline:
    return Pipeline(
        resources=[drift_schedule, ol_infrastructure],
        jobs=[drift_job()],
    )


if __name__ == "__main__":
    definition_json = github_drift_pipeline().model_dump_json(indent=2)
    with open("definition.json", "w") as definition:  # noqa: PTH123
        definition.write(definition_json)
    sys.stdout.write(definition_json)
    print()  # noqa: T201
    print("fly -t pr-inf sp -p github-estate-drift -c definition.json")  # noqa: T201
