"""Nightly drift check for the mitodl GitHub estate (phase 6 of the org import).

`bin/github-estate-audit drift` compares the committed fleet YAML
(`saas/github/repositories/data/repos/*.yaml`) against a fresh crawl of live
GitHub and reports every field that has moved out of band -- a console change
nobody made through Pulumi. This job runs that comparison nightly and, when
the report's content has changed since the last run, commits it to
`docs/generated/github-drift-report.md` and opens or updates a pull request
carrying the diff. It never edits the fleet YAML itself: reconciling a drift
finding (deciding whether live or declared should win) is still a human call,
same as every other phase-5 remediation in this project.

Two separate GitHub App credentials are in play, on purpose -- same boundary
`bin/open-drift-pr`'s own docstring calls out for iam_drift:

- The crawl itself (`github-org-inventory report --refresh` and
  `github-estate-audit drift`) authenticates as `ol-infrastructure-as-code`
  via `ol_infrastructure.lib.github_helper.get_installation_token()`, which
  decrypts `src/bridge/secrets/pulumi/github_app.yaml` through the same
  sops/KMS path every `pulumi_job()` step on this pool already uses -- no new
  credential to provision. That app holds `pull_requests: read`, not
  `write` (see `docs/github-app-permissions.md`), so it cannot open a PR.
- Pushing the branch and opening the PR uses the SAME dedicated
  `((github.drift_pr_app_id))` / `((github.drift_pr_app_installation_id))` /
  `((github.drift_pr_app_pem))` credential iam_drift already relies on --
  already scoped to `contents:write` + `pull_requests:write` on
  `mitodl/ol-infrastructure`, which is the only repo this job ever pushes to
  (the drift *report*, not the 316 org repos it reports on).
"""

import sys

from ol_concourse.lib.constants import REGISTRY_IMAGE
from ol_concourse.lib.models.pipeline import (
    AnonymousResource,
    Command,
    GetStep,
    Identifier,
    Input,
    Job,
    Pipeline,
    Platform,
    TaskConfig,
    TaskStep,
)
from ol_concourse.lib.resources import git_repo, schedule

from ol_concourse.pipelines.constants import ECR_REGION, dockerhub_ecr_image_uri

GITHUB_REPOSITORY = "mitodl/ol-infrastructure"
GITHUB_APP_ID_VAULT_PATH = "((github.drift_pr_app_id))"
GITHUB_APP_INSTALLATION_ID_VAULT_PATH = "((github.drift_pr_app_installation_id))"
GITHUB_APP_PRIVATE_KEY_VAULT_PATH = "((github.drift_pr_app_pem))"
REPORT_PATH = "docs/generated/github-drift-report.md"
DRIFT_BRANCH = "github-estate-drift"

ol_infrastructure = git_repo(
    Identifier("ol-infrastructure"),
    uri=f"https://github.com/{GITHUB_REPOSITORY}",
)

drift_schedule = schedule(
    Identifier("nightly-schedule"),
    interval="24h",
    start="02:00",
    stop="03:00",
)

ol_infrastructure_image = AnonymousResource(
    type=REGISTRY_IMAGE,
    source={
        "repository": dockerhub_ecr_image_uri("mitodl/ol-infrastructure"),
        "tag": "latest",
        "aws_region": ECR_REGION,
    },
)

# Refresh the crawl cache (reads live GitHub, writes nothing to the checkout),
# then run `drift`. Its own contract is `return 1 if total else 0` (findings
# present vs. clean) -- but an unhandled Python exception also exits 1 and
# would be indistinguishable from a real "N differences found" result by exit
# code alone. `drift()` only ever calls plain `print()` (stdout), never
# `file=sys.stderr`, so a non-empty stderr reliably means something broke
# rather than that it found something -- checked explicitly below so an
# execution failure aborts the job instead of silently committing a partial
# or empty report as if it were a clean/successful run.
DRIFT_REPORT_COMMAND = (
    f"mkdir -p ol-infrastructure/{REPORT_PATH.rsplit('/', 1)[0]}\n"
    "python ol-infrastructure/bin/github-org-inventory report --refresh"
    " --cache /tmp/github-drift-cache.json > /dev/null\n"
    "if ! python ol-infrastructure/bin/github-estate-audit drift"
    " --cache /tmp/github-drift-cache.json"
    " > /tmp/drift-stdout.txt 2> /tmp/drift-stderr.txt; then\n"
    "  if [ -s /tmp/drift-stderr.txt ]; then\n"
    "    echo 'github-estate-audit drift failed unexpectedly -- aborting"
    " before writing or pushing a report:' >&2\n"
    "    cat /tmp/drift-stderr.txt >&2\n"
    "    exit 1\n"
    "  fi\n"
    "fi\n"
    "{\n"
    '  echo "# GitHub estate drift report"\n'
    "  echo\n"
    '  echo "Nightly diff of the committed fleet data in'
    " \\`saas/github/repositories/data/repos/\\` against live GitHub."
    " Generated by the \\`github-estate-drift\\` Concourse job -- see"
    " \\`src/ol_concourse/pipelines/infrastructure/github_drift/pipeline.py\\`."
    " A finding here is not auto-applied: encode the intended value as a"
    " per-repo deviation (if live is correct) or fix it live with"
    " \\`pulumi up\\` (if the committed value is correct), same as any other"
    ' phase-5 remediation."\n'
    "  echo\n"
    "  echo '```'\n"
    "  cat /tmp/drift-stdout.txt\n"
    "  echo '```'\n"
    f"}} > ol-infrastructure/{REPORT_PATH}\n"
)

# `open-drift-pr` decides whether to push by comparing the FULL working tree
# against the remote branch's tree (see its own `_remote_tree`), which is the
# right comparison for iam_drift (the only file its analyzer ever touches
# moves in step with real drift). It's the wrong one here: this checkout is
# always freshly cloned from `main`'s current tip, so the full tree changes
# every night regardless of whether the report content changed, purely
# because `main` itself moved -- defeating the "skip when unchanged"
# optimization `open-drift-pr` exists to provide, and pushing/updating the PR
# every night even when nothing in the report is new. Compare just the report
# file's content against what's already on the remote branch ourselves, and
# only invoke `open-drift-pr` when that comparison shows a real change (or
# the branch doesn't exist yet, i.e. the first run).
OPEN_PR_COMMAND = (
    "cd ol-infrastructure\n"
    'git config --global --add safe.directory "$(pwd)"\n'
    'REMOTE_REPORT=""\n'
    f"if git ls-remote --exit-code origin refs/heads/{DRIFT_BRANCH}"
    " > /dev/null 2>&1; then\n"
    f"  git fetch --quiet origin refs/heads/{DRIFT_BRANCH}\n"
    f'  REMOTE_REPORT="$(git show "FETCH_HEAD:{REPORT_PATH}" 2>/dev/null'
    ' || true)"\n'
    "fi\n"
    f'if [ "$REMOTE_REPORT" = "$(cat {REPORT_PATH})" ]; then\n'
    '  echo "Report unchanged since the last run on'
    f' {DRIFT_BRANCH}; not pushing."\n'
    "else\n"
    "  cd ..\n"
    "  echo 'Nightly GitHub estate drift report. See the file diff for what"
    " changed; findings are not applied automatically.' > /tmp/pr_body.md\n"
    "  python ol-infrastructure/bin/open-drift-pr"
    " --repo-dir ol-infrastructure"
    f" --repo {GITHUB_REPOSITORY}"
    f" --branch {DRIFT_BRANCH}"
    " --title 'chore(github): nightly estate drift report'"
    " --body-file /tmp/pr_body.md\n"
    "fi\n"
)


def drift_job() -> Job:
    return Job(
        name=Identifier("check-github-estate-drift"),
        plan=[
            GetStep(get=drift_schedule.name, trigger=True),
            GetStep(get=ol_infrastructure.name, trigger=False),
            TaskStep(
                task=Identifier("report-github-estate-drift"),
                config=TaskConfig(
                    platform=Platform.linux,
                    image_resource=ol_infrastructure_image,
                    inputs=[Input(name=ol_infrastructure.name)],
                    params={
                        "GITHUB_APP_ID": GITHUB_APP_ID_VAULT_PATH,
                        "GITHUB_APP_INSTALLATION_ID": (
                            GITHUB_APP_INSTALLATION_ID_VAULT_PATH
                        ),
                        "GITHUB_APP_PRIVATE_KEY": GITHUB_APP_PRIVATE_KEY_VAULT_PATH,
                    },
                    run=Command(
                        user="root",
                        path="sh",
                        args=["-exc", DRIFT_REPORT_COMMAND + OPEN_PR_COMMAND],
                    ),
                ),
            ),
        ],
    )


def github_drift_pipeline() -> Pipeline:
    return Pipeline(
        resources=[drift_schedule, ol_infrastructure],
        jobs=[drift_job()],
    )


if __name__ == "__main__":
    definition_json = github_drift_pipeline().model_dump_json(indent=2)
    with open("definition.json", "w") as definition:  # noqa: PTH123
        definition.write(definition_json)
    sys.stdout.write(definition_json)
    print()  # noqa: T201
    print("fly -t pr-inf sp -p github-estate-drift -c definition.json")  # noqa: T201
