---
secretsprovider: awskms://alias/infrastructure-secrets-qa
config:
  marimo_data:apps_domain: nb-qa.data.ol.mit.edu
  aws:region: us-east-1
  vault:address: https://vault-qa.odl.mit.edu
  vault_server:env_namespace: operations.qa
