python_sources()

resources(
    name="sops_secrets",
    sources=[
        "**/*.yaml",
        "**/*.json",
        "**/*.env"
    ],
    description="Files containing encrypted values managed via SOPS for use with Pulumi and PyInfra code."
)
