---
slack-bot-token: <REPLACE_WITH_VAULT_VALUE>
slack-app-token: <REPLACE_WITH_VAULT_VALUE>
concourse-username: <REPLACE_WITH_VAULT_VALUE>
concourse-password: <REPLACE_WITH_VAULT_VALUE>
github-token: <REPLACE_WITH_VAULT_VALUE>
