# TODO: Encrypt with SOPS before committing.
# Run: sops --encrypt --in-place secrets.applications.ci.yaml
# Using KMS key: arn:aws:kms:us-east-1:610119931565:alias/infrastructure-secrets-ci
---
slack-bot-token: xoxb-REPLACE_ME
slack-app-token: xapp-REPLACE_ME
concourse-username: release-bot
concourse-password: REPLACE_ME
github-token: ghp_REPLACE_ME
