---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHjnbqe9AmEW1Js10nySybyuAG7Fb5E9EHUgkmqFDv7PxQGTfGgSk9EZ4ZNb/wbJfXd+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMA0HqkgIE4odoJJA1AgEQgDvV0/Ss11eXyMaVbNAyMdRYYZtma1v9dVZa+p4MuzZFJn9xBZU9Fsa1suYQRgBa5jhg3XsmZDnN8st/aw==
config:
  aws:region: us-east-1
  xqwatcher:business_unit: residential-staging
  xqwatcher:cluster: residential
  xqwatcher:namespace: mitx-staging-openedx
  xqwatcher:min_replicas: 1
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
  xqwatcher:xqueue_server_url: https://xqueue.mitx-staging-ci.odl.mit.edu
  xqwatcher:queues:
    Watcher-MITx-6.00x:
      CONNECTIONS: 5
      HANDLERS:
      - HANDLER: xqueue_watcher.containergrader.ContainerGrader
        KWARGS:
          grader_root: /graders/python3graders/
          image: 610119931565.dkr.ecr.us-east-1.amazonaws.com/mitodl/graders-mit-600x:latest
          backend: kubernetes
          cpu_limit: 1000m
          memory_limit: 512Mi
          timeout: 60
          image_pull_policy: Always
    Watcher-MITx-6.0001r:
      CONNECTIONS: 5
      HANDLERS:
      - HANDLER: xqueue_watcher.containergrader.ContainerGrader
        KWARGS:
          grader_root: /graders/python3graders/
          image: 610119931565.dkr.ecr.us-east-1.amazonaws.com/mitodl/graders-mit-600x:latest
          backend: kubernetes
          cpu_limit: 1000m
          memory_limit: 512Mi
          timeout: 60
          image_pull_policy: Always
