---
secretsprovider: awskms://alias/infrastructure-secrets-production
encryptedkey: AQICAHjmo6C0sCNz3fdkFlhbu0tdBZxnHmPYSnqtmocvGiuNygG5AzdO0QY0yXbhDGt3drvfAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMevv1o+gghWthYkifAgEQgDtMc3j8K7A1ne9ZjHtpgBo9wlSor6yW7KOQpjGjToqweQ5wvlLlkOQibnSKKxi6Vhsm3gXz7nlzNuliIg==
config:
  aws:region: us-east-1
  xqwatcher:business_unit: mitxonline
  xqwatcher:cluster: applications
  xqwatcher:namespace: mitxonline-openedx
  xqwatcher:min_replicas: 2
  xqwatcher:docker_tag: latest
  vault:address: https://vault-production.odl.mit.edu
  vault_server:env_namespace: operations.production
