---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHjnbqe9AmEW1Js10nySybyuAG7Fb5E9EHUgkmqFDv7PxQHQ1nYxdMdGpUV3lkCYkPCCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsqc+FPq0+d14aeiEAgEQgDtOLAH8o/ueXOQKwFgUIv0reMzktDtSL+DF4pec6zPtl0qaaP7mXGY9WECr4y4YGaZ6uHtgh1pHncqqIQ==
config:
  aws:region: us-east-1
  xqwatcher:business_unit: residential
  xqwatcher:cluster: residential
  xqwatcher:namespace: mitx-openedx
  xqwatcher:min_replicas: 1
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
