---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHi3MZ/Pjy2dahB1Qm+zKkKDPV1b9MYPGp7k649HPjmOHAG+XE3l7voVbQN9bQ80XZRMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMq5xwinh6H/9mPuyeAgEQgDtUAuLW2HbXCdstaU6dZEtTOQ2SXq67YUzDbnJeE2FNb49KxWEgsXeUzz/r6XiML/cTwq1cTIHq7LDi0w==
config:
  aws:region: us-east-1
  xqwatcher:business_unit: mitxonline
  xqwatcher:cluster: applications
  xqwatcher:namespace: mitxonline-openedx
  xqwatcher:min_replicas: 1
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
  xqwatcher:xqueue_server_url: https://xqueue.mitxonline.ci.odl.mit.edu
  xqwatcher:queues:
    Watcher-MITx-6.00x:
      CONNECTIONS: 5
      HANDLERS:
      - HANDLER: xqueue_watcher.containergrader.ContainerGrader
        KWARGS:
          grader_root: /graders/python3graders/
          image: 610119931565.dkr.ecr.us-east-1.amazonaws.com/mitodl/graders-mit-600x:latest
          backend: kubernetes
          cpu_limit: 1000m
          memory_limit: 512Mi
          timeout: 60
          image_pull_policy: always
