---
secretsprovider: awskms://alias/infrastructure-secrets-production
encryptedkey: AQICAHg/+QzF9hGIaoayDitgnEVHEhuaANONVQQOnqpkIsol1gGmUka22ZxA+gSjtTQYJpu7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwgs2uibhDk5Norz9AgEQgDthPFx801sr1BklahUFoE2gLVQIt1AkbzGBbes+1R6BNTKg2gjoS8f5EeDhNyTQy3+TNxKbzMgjLG4l7A==
config:
  monitoring:fastly_customer_id:
    secure: v1:BlStRhJvdFsmqolz:d4JLskD5SCxBCqzm4RLBybe7IbvxCcCvm2Fpxsp+W6GqkH84mBI=
  monitoring:fastly_logging_bucket_name: mitodl-fastly-access-logs
  monitoring:rootly_warning_webhook_url:
    secure: v1:h15ixNmCBl3CGTHB:+T9LNnWxxQelhKTmM1p7QutP4W+7ErNKjX4SD85h7FX9o+ubXHOsNg2KDthr6z/u6EbqI+x4nxYVQXMTJUZDifvyKhDpoyLWREe9od9nOgxUxL11ctsHB4hgVeP0KqOZ/Ai12abGSWrFxPHqFw0Tqj2APpWHcbSrHIyJ/TVQHGPHtzypM/dNTlr+30T4LjMNKFyCg+22THyJQw==
  monitoring:rootly_critical_webhook_url:
    secure: v1:rfDUECxh6MkNnTsT:TkMtMOlnXu3X+q0wG+LPsbjL3ii3qanqPnmQVm6sZuAz6Hv4PbmQQKs/JwyImZSWZxa0orJGGecYCI7c/8Gi7Qdb5fTfe43IVvd0hXPXwrrwh1KRCbEXSN88hTf7anI2syZHfN96OscpPv02BfuGk/s5cfnoo32QQA0mNi1DxfGLH2nRGM2XNFwXABwZ6PZuaAc42ucB/1BKsw==
