---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: mitxonline-tls
  namespace: mitxonline
spec:
  ingressClassName: apache-apisix
  hosts:
  - "mitxonline.mit.dev"
  secret:
    name: local-dev-tls
    namespace: mitxonline
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: mitxonline-route
  namespace: mitxonline
spec:
  ingressClassName: apache-apisix
  http:
  - name: public
    match:
      hosts:
      - "mitxonline.mit.dev"
      paths:
      - "/*"
    backends:
    - serviceName: mitxonline-webapp
      servicePort: 8010
    plugins:
    - name: openid-connect
      enable: true
      config:
        client_id: "ol-mitxonline-client"
        client_secret: "local-dev-mitxonline-secret"  # pragma: allowlist secret
        discovery: "https://sso.ol.mit.dev/realms/olapps/.well-known/openid-configuration"
        scope: "openid profile email"
        redirect_uri: "https://mitxonline.mit.dev/oidc/callback"
        logout_path: "/logout"
        post_logout_redirect_uri: "/"
        unauth_action: "pass"
        session:
          secret: "local-dev-mitxonline-session-32c!!"  # pragma: allowlist secret
        ssl_verify: false
