# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['CommunicationsTypeArgs', 'CommunicationsType']

@pulumi.input_type
class CommunicationsTypeArgs:
    def __init__(__self__, *,
                 color: pulumi.Input[_builtins.str],
                 communications_type_id: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a CommunicationsType resource.

        :param pulumi.Input[_builtins.str] color: The color of the communications type
        :param pulumi.Input[_builtins.str] description: The description of the communications type
        :param pulumi.Input[_builtins.str] name: The name of the communications type
        :param pulumi.Input[_builtins.float] position: Position of the communications type
        :param pulumi.Input[_builtins.str] slug: The slug of the communications type
        """
        pulumi.set(__self__, "color", color)
        if communications_type_id is not None:
            pulumi.set(__self__, "communications_type_id", communications_type_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if position is not None:
            pulumi.set(__self__, "position", position)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)

    @_builtins.property
    @pulumi.getter
    def color(self) -> pulumi.Input[_builtins.str]:
        """
        The color of the communications type
        """
        return pulumi.get(self, "color")

    @color.setter
    def color(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "color", value)

    @_builtins.property
    @pulumi.getter(name="communicationsTypeId")
    def communications_type_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "communications_type_id")

    @communications_type_id.setter
    def communications_type_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "communications_type_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The description of the communications type
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the communications type
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Position of the communications type
        """
        return pulumi.get(self, "position")

    @position.setter
    def position(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "position", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The slug of the communications type
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "slug", value)


@pulumi.input_type
class _CommunicationsTypeState:
    def __init__(__self__, *,
                 color: pulumi.Input[Optional[_builtins.str]] = None,
                 communications_type_id: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering CommunicationsType resources.

        :param pulumi.Input[_builtins.str] color: The color of the communications type
        :param pulumi.Input[_builtins.str] description: The description of the communications type
        :param pulumi.Input[_builtins.str] name: The name of the communications type
        :param pulumi.Input[_builtins.float] position: Position of the communications type
        :param pulumi.Input[_builtins.str] slug: The slug of the communications type
        """
        if color is not None:
            pulumi.set(__self__, "color", color)
        if communications_type_id is not None:
            pulumi.set(__self__, "communications_type_id", communications_type_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if position is not None:
            pulumi.set(__self__, "position", position)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)

    @_builtins.property
    @pulumi.getter
    def color(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The color of the communications type
        """
        return pulumi.get(self, "color")

    @color.setter
    def color(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "color", value)

    @_builtins.property
    @pulumi.getter(name="communicationsTypeId")
    def communications_type_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "communications_type_id")

    @communications_type_id.setter
    def communications_type_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "communications_type_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The description of the communications type
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the communications type
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Position of the communications type
        """
        return pulumi.get(self, "position")

    @position.setter
    def position(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "position", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The slug of the communications type
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "slug", value)


@pulumi.type_token("rootly:index/communicationsType:CommunicationsType")
class CommunicationsType(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 color: pulumi.Input[Optional[_builtins.str]] = None,
                 communications_type_id: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a CommunicationsType resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] color: The color of the communications type
        :param pulumi.Input[_builtins.str] description: The description of the communications type
        :param pulumi.Input[_builtins.str] name: The name of the communications type
        :param pulumi.Input[_builtins.float] position: Position of the communications type
        :param pulumi.Input[_builtins.str] slug: The slug of the communications type
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CommunicationsTypeArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a CommunicationsType resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param CommunicationsTypeArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CommunicationsTypeArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 color: pulumi.Input[Optional[_builtins.str]] = None,
                 communications_type_id: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CommunicationsTypeArgs.__new__(CommunicationsTypeArgs)

            if color is None and not opts.urn:
                raise TypeError("Missing required property 'color'")
            __props__.__dict__["color"] = color
            __props__.__dict__["communications_type_id"] = communications_type_id
            __props__.__dict__["description"] = description
            __props__.__dict__["name"] = name
            __props__.__dict__["position"] = position
            __props__.__dict__["slug"] = slug
        super(CommunicationsType, __self__).__init__(
            'rootly:index/communicationsType:CommunicationsType',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            color: pulumi.Input[Optional[_builtins.str]] = None,
            communications_type_id: pulumi.Input[Optional[_builtins.str]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            position: pulumi.Input[Optional[_builtins.float]] = None,
            slug: pulumi.Input[Optional[_builtins.str]] = None) -> 'CommunicationsType':
        """
        Get an existing CommunicationsType resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] color: The color of the communications type
        :param pulumi.Input[_builtins.str] description: The description of the communications type
        :param pulumi.Input[_builtins.str] name: The name of the communications type
        :param pulumi.Input[_builtins.float] position: Position of the communications type
        :param pulumi.Input[_builtins.str] slug: The slug of the communications type
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _CommunicationsTypeState.__new__(_CommunicationsTypeState)

        __props__.__dict__["color"] = color
        __props__.__dict__["communications_type_id"] = communications_type_id
        __props__.__dict__["description"] = description
        __props__.__dict__["name"] = name
        __props__.__dict__["position"] = position
        __props__.__dict__["slug"] = slug
        return CommunicationsType(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def color(self) -> pulumi.Output[_builtins.str]:
        """
        The color of the communications type
        """
        return pulumi.get(self, "color")

    @_builtins.property
    @pulumi.getter(name="communicationsTypeId")
    def communications_type_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "communications_type_id")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        The description of the communications type
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the communications type
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Output[_builtins.float]:
        """
        Position of the communications type
        """
        return pulumi.get(self, "position")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Output[_builtins.str]:
        """
        The slug of the communications type
        """
        return pulumi.get(self, "slug")

