# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['FormFieldPlacementArgs', 'FormFieldPlacement']

@pulumi.input_type
class FormFieldPlacementArgs:
    def __init__(__self__, *,
                 form: pulumi.Input[_builtins.str],
                 form_set_id: pulumi.Input[_builtins.str],
                 form_field_id: pulumi.Input[Optional[_builtins.str]] = None,
                 form_field_placement_id: pulumi.Input[Optional[_builtins.str]] = None,
                 non_editable: pulumi.Input[Optional[_builtins.bool]] = None,
                 placement_operator: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 required: pulumi.Input[Optional[_builtins.bool]] = None,
                 required_operator: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a FormFieldPlacement resource.

        :param pulumi.Input[_builtins.str] form: The form this field is placed on.
        :param pulumi.Input[_builtins.str] form_set_id: The form set this field is placed in.
        :param pulumi.Input[_builtins.str] form_field_id: The form field that is placed.
        :param pulumi.Input[_builtins.bool] non_editable: Whether the field is read-only and cannot be edited by users.. Value must be one of true or false
        :param pulumi.Input[_builtins.str] placement_operator: Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=placement. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        :param pulumi.Input[_builtins.float] position: The position of the field placement.
        :param pulumi.Input[_builtins.bool] required: Whether the field is unconditionally required on this form.. Value must be one of true or false
        :param pulumi.Input[_builtins.str] required_operator: Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=required. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        """
        pulumi.set(__self__, "form", form)
        pulumi.set(__self__, "form_set_id", form_set_id)
        if form_field_id is not None:
            pulumi.set(__self__, "form_field_id", form_field_id)
        if form_field_placement_id is not None:
            pulumi.set(__self__, "form_field_placement_id", form_field_placement_id)
        if non_editable is not None:
            pulumi.set(__self__, "non_editable", non_editable)
        if placement_operator is not None:
            pulumi.set(__self__, "placement_operator", placement_operator)
        if position is not None:
            pulumi.set(__self__, "position", position)
        if required is not None:
            pulumi.set(__self__, "required", required)
        if required_operator is not None:
            pulumi.set(__self__, "required_operator", required_operator)

    @_builtins.property
    @pulumi.getter
    def form(self) -> pulumi.Input[_builtins.str]:
        """
        The form this field is placed on.
        """
        return pulumi.get(self, "form")

    @form.setter
    def form(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "form", value)

    @_builtins.property
    @pulumi.getter(name="formSetId")
    def form_set_id(self) -> pulumi.Input[_builtins.str]:
        """
        The form set this field is placed in.
        """
        return pulumi.get(self, "form_set_id")

    @form_set_id.setter
    def form_set_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "form_set_id", value)

    @_builtins.property
    @pulumi.getter(name="formFieldId")
    def form_field_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The form field that is placed.
        """
        return pulumi.get(self, "form_field_id")

    @form_field_id.setter
    def form_field_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "form_field_id", value)

    @_builtins.property
    @pulumi.getter(name="formFieldPlacementId")
    def form_field_placement_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "form_field_placement_id")

    @form_field_placement_id.setter
    def form_field_placement_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "form_field_placement_id", value)

    @_builtins.property
    @pulumi.getter(name="nonEditable")
    def non_editable(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the field is read-only and cannot be edited by users.. Value must be one of true or false
        """
        return pulumi.get(self, "non_editable")

    @non_editable.setter
    def non_editable(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "non_editable", value)

    @_builtins.property
    @pulumi.getter(name="placementOperator")
    def placement_operator(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=placement. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        """
        return pulumi.get(self, "placement_operator")

    @placement_operator.setter
    def placement_operator(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "placement_operator", value)

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The position of the field placement.
        """
        return pulumi.get(self, "position")

    @position.setter
    def position(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "position", value)

    @_builtins.property
    @pulumi.getter
    def required(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the field is unconditionally required on this form.. Value must be one of true or false
        """
        return pulumi.get(self, "required")

    @required.setter
    def required(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "required", value)

    @_builtins.property
    @pulumi.getter(name="requiredOperator")
    def required_operator(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=required. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        """
        return pulumi.get(self, "required_operator")

    @required_operator.setter
    def required_operator(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "required_operator", value)


@pulumi.input_type
class _FormFieldPlacementState:
    def __init__(__self__, *,
                 form: pulumi.Input[Optional[_builtins.str]] = None,
                 form_field_id: pulumi.Input[Optional[_builtins.str]] = None,
                 form_field_placement_id: pulumi.Input[Optional[_builtins.str]] = None,
                 form_set_id: pulumi.Input[Optional[_builtins.str]] = None,
                 non_editable: pulumi.Input[Optional[_builtins.bool]] = None,
                 placement_operator: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 required: pulumi.Input[Optional[_builtins.bool]] = None,
                 required_operator: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering FormFieldPlacement resources.

        :param pulumi.Input[_builtins.str] form: The form this field is placed on.
        :param pulumi.Input[_builtins.str] form_field_id: The form field that is placed.
        :param pulumi.Input[_builtins.str] form_set_id: The form set this field is placed in.
        :param pulumi.Input[_builtins.bool] non_editable: Whether the field is read-only and cannot be edited by users.. Value must be one of true or false
        :param pulumi.Input[_builtins.str] placement_operator: Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=placement. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        :param pulumi.Input[_builtins.float] position: The position of the field placement.
        :param pulumi.Input[_builtins.bool] required: Whether the field is unconditionally required on this form.. Value must be one of true or false
        :param pulumi.Input[_builtins.str] required_operator: Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=required. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        """
        if form is not None:
            pulumi.set(__self__, "form", form)
        if form_field_id is not None:
            pulumi.set(__self__, "form_field_id", form_field_id)
        if form_field_placement_id is not None:
            pulumi.set(__self__, "form_field_placement_id", form_field_placement_id)
        if form_set_id is not None:
            pulumi.set(__self__, "form_set_id", form_set_id)
        if non_editable is not None:
            pulumi.set(__self__, "non_editable", non_editable)
        if placement_operator is not None:
            pulumi.set(__self__, "placement_operator", placement_operator)
        if position is not None:
            pulumi.set(__self__, "position", position)
        if required is not None:
            pulumi.set(__self__, "required", required)
        if required_operator is not None:
            pulumi.set(__self__, "required_operator", required_operator)

    @_builtins.property
    @pulumi.getter
    def form(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The form this field is placed on.
        """
        return pulumi.get(self, "form")

    @form.setter
    def form(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "form", value)

    @_builtins.property
    @pulumi.getter(name="formFieldId")
    def form_field_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The form field that is placed.
        """
        return pulumi.get(self, "form_field_id")

    @form_field_id.setter
    def form_field_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "form_field_id", value)

    @_builtins.property
    @pulumi.getter(name="formFieldPlacementId")
    def form_field_placement_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "form_field_placement_id")

    @form_field_placement_id.setter
    def form_field_placement_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "form_field_placement_id", value)

    @_builtins.property
    @pulumi.getter(name="formSetId")
    def form_set_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The form set this field is placed in.
        """
        return pulumi.get(self, "form_set_id")

    @form_set_id.setter
    def form_set_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "form_set_id", value)

    @_builtins.property
    @pulumi.getter(name="nonEditable")
    def non_editable(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the field is read-only and cannot be edited by users.. Value must be one of true or false
        """
        return pulumi.get(self, "non_editable")

    @non_editable.setter
    def non_editable(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "non_editable", value)

    @_builtins.property
    @pulumi.getter(name="placementOperator")
    def placement_operator(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=placement. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        """
        return pulumi.get(self, "placement_operator")

    @placement_operator.setter
    def placement_operator(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "placement_operator", value)

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The position of the field placement.
        """
        return pulumi.get(self, "position")

    @position.setter
    def position(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "position", value)

    @_builtins.property
    @pulumi.getter
    def required(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the field is unconditionally required on this form.. Value must be one of true or false
        """
        return pulumi.get(self, "required")

    @required.setter
    def required(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "required", value)

    @_builtins.property
    @pulumi.getter(name="requiredOperator")
    def required_operator(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=required. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        """
        return pulumi.get(self, "required_operator")

    @required_operator.setter
    def required_operator(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "required_operator", value)


@pulumi.type_token("rootly:index/formFieldPlacement:FormFieldPlacement")
class FormFieldPlacement(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 form: pulumi.Input[Optional[_builtins.str]] = None,
                 form_field_id: pulumi.Input[Optional[_builtins.str]] = None,
                 form_field_placement_id: pulumi.Input[Optional[_builtins.str]] = None,
                 form_set_id: pulumi.Input[Optional[_builtins.str]] = None,
                 non_editable: pulumi.Input[Optional[_builtins.bool]] = None,
                 placement_operator: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 required: pulumi.Input[Optional[_builtins.bool]] = None,
                 required_operator: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a FormFieldPlacement resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] form: The form this field is placed on.
        :param pulumi.Input[_builtins.str] form_field_id: The form field that is placed.
        :param pulumi.Input[_builtins.str] form_set_id: The form set this field is placed in.
        :param pulumi.Input[_builtins.bool] non_editable: Whether the field is read-only and cannot be edited by users.. Value must be one of true or false
        :param pulumi.Input[_builtins.str] placement_operator: Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=placement. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        :param pulumi.Input[_builtins.float] position: The position of the field placement.
        :param pulumi.Input[_builtins.bool] required: Whether the field is unconditionally required on this form.. Value must be one of true or false
        :param pulumi.Input[_builtins.str] required_operator: Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=required. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: FormFieldPlacementArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a FormFieldPlacement resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param FormFieldPlacementArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(FormFieldPlacementArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 form: pulumi.Input[Optional[_builtins.str]] = None,
                 form_field_id: pulumi.Input[Optional[_builtins.str]] = None,
                 form_field_placement_id: pulumi.Input[Optional[_builtins.str]] = None,
                 form_set_id: pulumi.Input[Optional[_builtins.str]] = None,
                 non_editable: pulumi.Input[Optional[_builtins.bool]] = None,
                 placement_operator: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 required: pulumi.Input[Optional[_builtins.bool]] = None,
                 required_operator: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = FormFieldPlacementArgs.__new__(FormFieldPlacementArgs)

            if form is None and not opts.urn:
                raise TypeError("Missing required property 'form'")
            __props__.__dict__["form"] = form
            __props__.__dict__["form_field_id"] = form_field_id
            __props__.__dict__["form_field_placement_id"] = form_field_placement_id
            if form_set_id is None and not opts.urn:
                raise TypeError("Missing required property 'form_set_id'")
            __props__.__dict__["form_set_id"] = form_set_id
            __props__.__dict__["non_editable"] = non_editable
            __props__.__dict__["placement_operator"] = placement_operator
            __props__.__dict__["position"] = position
            __props__.__dict__["required"] = required
            __props__.__dict__["required_operator"] = required_operator
        super(FormFieldPlacement, __self__).__init__(
            'rootly:index/formFieldPlacement:FormFieldPlacement',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            form: pulumi.Input[Optional[_builtins.str]] = None,
            form_field_id: pulumi.Input[Optional[_builtins.str]] = None,
            form_field_placement_id: pulumi.Input[Optional[_builtins.str]] = None,
            form_set_id: pulumi.Input[Optional[_builtins.str]] = None,
            non_editable: pulumi.Input[Optional[_builtins.bool]] = None,
            placement_operator: pulumi.Input[Optional[_builtins.str]] = None,
            position: pulumi.Input[Optional[_builtins.float]] = None,
            required: pulumi.Input[Optional[_builtins.bool]] = None,
            required_operator: pulumi.Input[Optional[_builtins.str]] = None) -> 'FormFieldPlacement':
        """
        Get an existing FormFieldPlacement resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] form: The form this field is placed on.
        :param pulumi.Input[_builtins.str] form_field_id: The form field that is placed.
        :param pulumi.Input[_builtins.str] form_set_id: The form set this field is placed in.
        :param pulumi.Input[_builtins.bool] non_editable: Whether the field is read-only and cannot be edited by users.. Value must be one of true or false
        :param pulumi.Input[_builtins.str] placement_operator: Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=placement. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        :param pulumi.Input[_builtins.float] position: The position of the field placement.
        :param pulumi.Input[_builtins.bool] required: Whether the field is unconditionally required on this form.. Value must be one of true or false
        :param pulumi.Input[_builtins.str] required_operator: Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=required. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _FormFieldPlacementState.__new__(_FormFieldPlacementState)

        __props__.__dict__["form"] = form
        __props__.__dict__["form_field_id"] = form_field_id
        __props__.__dict__["form_field_placement_id"] = form_field_placement_id
        __props__.__dict__["form_set_id"] = form_set_id
        __props__.__dict__["non_editable"] = non_editable
        __props__.__dict__["placement_operator"] = placement_operator
        __props__.__dict__["position"] = position
        __props__.__dict__["required"] = required
        __props__.__dict__["required_operator"] = required_operator
        return FormFieldPlacement(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def form(self) -> pulumi.Output[_builtins.str]:
        """
        The form this field is placed on.
        """
        return pulumi.get(self, "form")

    @_builtins.property
    @pulumi.getter(name="formFieldId")
    def form_field_id(self) -> pulumi.Output[_builtins.str]:
        """
        The form field that is placed.
        """
        return pulumi.get(self, "form_field_id")

    @_builtins.property
    @pulumi.getter(name="formFieldPlacementId")
    def form_field_placement_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "form_field_placement_id")

    @_builtins.property
    @pulumi.getter(name="formSetId")
    def form_set_id(self) -> pulumi.Output[_builtins.str]:
        """
        The form set this field is placed in.
        """
        return pulumi.get(self, "form_set_id")

    @_builtins.property
    @pulumi.getter(name="nonEditable")
    def non_editable(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the field is read-only and cannot be edited by users.. Value must be one of true or false
        """
        return pulumi.get(self, "non_editable")

    @_builtins.property
    @pulumi.getter(name="placementOperator")
    def placement_operator(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=placement. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        """
        return pulumi.get(self, "placement_operator")

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Output[_builtins.float]:
        """
        The position of the field placement.
        """
        return pulumi.get(self, "position")

    @_builtins.property
    @pulumi.getter
    def required(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the field is unconditionally required on this form.. Value must be one of true or false
        """
        return pulumi.get(self, "required")

    @_builtins.property
    @pulumi.getter(name="requiredOperator")
    def required_operator(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Logical operator when evaluating multiple<span pulumi-lang-nodejs=" formFieldPlacementConditions " pulumi-lang-dotnet=" FormFieldPlacementConditions " pulumi-lang-go=" formFieldPlacementConditions " pulumi-lang-python=" form_field_placement_conditions " pulumi-lang-yaml=" formFieldPlacementConditions " pulumi-lang-java=" formFieldPlacementConditions " pulumi-lang-hcl=" form_field_placement_conditions "> formFieldPlacementConditions </span>with conditioned=required. Value must be one of <span pulumi-lang-nodejs="`and`" pulumi-lang-dotnet="`And`" pulumi-lang-go="`and`" pulumi-lang-python="`and`" pulumi-lang-yaml="`and`" pulumi-lang-java="`and`" pulumi-lang-hcl="`and`">`and`</span>, <span pulumi-lang-nodejs="`or`" pulumi-lang-dotnet="`Or`" pulumi-lang-go="`or`" pulumi-lang-python="`or`" pulumi-lang-yaml="`or`" pulumi-lang-java="`or`" pulumi-lang-hcl="`or`">`or`</span>.
        """
        return pulumi.get(self, "required_operator")

