# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetIncidentResult',
    'AwaitableGetIncidentResult',
    'get_incident',
    'get_incident_output',
]

@pulumi.output_type
class GetIncidentResult:
    """
    A collection of values returned by getIncident.
    """
    def __init__(__self__, acknowledged_at=None, closed_at=None, created_at=None, detected_at=None, environments=None, functionalities=None, id=None, in_triage_at=None, kind=None, labels=None, mitigated_at=None, private=None, resolved_at=None, services=None, severity=None, started_at=None, status=None, updated_at=None, user=None):
        if acknowledged_at and not isinstance(acknowledged_at, dict):
            raise TypeError("Expected argument 'acknowledged_at' to be a dict")
        pulumi.set(__self__, "acknowledged_at", acknowledged_at)
        if closed_at and not isinstance(closed_at, dict):
            raise TypeError("Expected argument 'closed_at' to be a dict")
        pulumi.set(__self__, "closed_at", closed_at)
        if created_at and not isinstance(created_at, dict):
            raise TypeError("Expected argument 'created_at' to be a dict")
        pulumi.set(__self__, "created_at", created_at)
        if detected_at and not isinstance(detected_at, dict):
            raise TypeError("Expected argument 'detected_at' to be a dict")
        pulumi.set(__self__, "detected_at", detected_at)
        if environments and not isinstance(environments, str):
            raise TypeError("Expected argument 'environments' to be a str")
        pulumi.set(__self__, "environments", environments)
        if functionalities and not isinstance(functionalities, str):
            raise TypeError("Expected argument 'functionalities' to be a str")
        pulumi.set(__self__, "functionalities", functionalities)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if in_triage_at and not isinstance(in_triage_at, dict):
            raise TypeError("Expected argument 'in_triage_at' to be a dict")
        pulumi.set(__self__, "in_triage_at", in_triage_at)
        if kind and not isinstance(kind, str):
            raise TypeError("Expected argument 'kind' to be a str")
        pulumi.set(__self__, "kind", kind)
        if labels and not isinstance(labels, str):
            raise TypeError("Expected argument 'labels' to be a str")
        pulumi.set(__self__, "labels", labels)
        if mitigated_at and not isinstance(mitigated_at, dict):
            raise TypeError("Expected argument 'mitigated_at' to be a dict")
        pulumi.set(__self__, "mitigated_at", mitigated_at)
        if private and not isinstance(private, bool):
            raise TypeError("Expected argument 'private' to be a bool")
        pulumi.set(__self__, "private", private)
        if resolved_at and not isinstance(resolved_at, dict):
            raise TypeError("Expected argument 'resolved_at' to be a dict")
        pulumi.set(__self__, "resolved_at", resolved_at)
        if services and not isinstance(services, str):
            raise TypeError("Expected argument 'services' to be a str")
        pulumi.set(__self__, "services", services)
        if severity and not isinstance(severity, str):
            raise TypeError("Expected argument 'severity' to be a str")
        pulumi.set(__self__, "severity", severity)
        if started_at and not isinstance(started_at, dict):
            raise TypeError("Expected argument 'started_at' to be a dict")
        pulumi.set(__self__, "started_at", started_at)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if updated_at and not isinstance(updated_at, dict):
            raise TypeError("Expected argument 'updated_at' to be a dict")
        pulumi.set(__self__, "updated_at", updated_at)
        if user and not isinstance(user, str):
            raise TypeError("Expected argument 'user' to be a str")
        pulumi.set(__self__, "user", user)

    @_builtins.property
    @pulumi.getter(name="acknowledgedAt")
    def acknowledged_at(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "acknowledged_at")

    @_builtins.property
    @pulumi.getter(name="closedAt")
    def closed_at(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "closed_at")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="detectedAt")
    def detected_at(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "detected_at")

    @_builtins.property
    @pulumi.getter
    def environments(self) -> _builtins.str:
        return pulumi.get(self, "environments")

    @_builtins.property
    @pulumi.getter
    def functionalities(self) -> _builtins.str:
        return pulumi.get(self, "functionalities")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="inTriageAt")
    def in_triage_at(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "in_triage_at")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> _builtins.str:
        return pulumi.get(self, "kind")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> _builtins.str:
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter(name="mitigatedAt")
    def mitigated_at(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "mitigated_at")

    @_builtins.property
    @pulumi.getter
    def private(self) -> _builtins.bool:
        return pulumi.get(self, "private")

    @_builtins.property
    @pulumi.getter(name="resolvedAt")
    def resolved_at(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "resolved_at")

    @_builtins.property
    @pulumi.getter
    def services(self) -> _builtins.str:
        return pulumi.get(self, "services")

    @_builtins.property
    @pulumi.getter
    def severity(self) -> _builtins.str:
        return pulumi.get(self, "severity")

    @_builtins.property
    @pulumi.getter(name="startedAt")
    def started_at(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "started_at")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter
    def user(self) -> _builtins.str:
        return pulumi.get(self, "user")


class AwaitableGetIncidentResult(GetIncidentResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetIncidentResult(
            acknowledged_at=self.acknowledged_at,
            closed_at=self.closed_at,
            created_at=self.created_at,
            detected_at=self.detected_at,
            environments=self.environments,
            functionalities=self.functionalities,
            id=self.id,
            in_triage_at=self.in_triage_at,
            kind=self.kind,
            labels=self.labels,
            mitigated_at=self.mitigated_at,
            private=self.private,
            resolved_at=self.resolved_at,
            services=self.services,
            severity=self.severity,
            started_at=self.started_at,
            status=self.status,
            updated_at=self.updated_at,
            user=self.user)


def get_incident(acknowledged_at: Optional[Mapping[str, _builtins.str]] = None,
                 closed_at: Optional[Mapping[str, _builtins.str]] = None,
                 created_at: Optional[Mapping[str, _builtins.str]] = None,
                 detected_at: Optional[Mapping[str, _builtins.str]] = None,
                 environments: Optional[_builtins.str] = None,
                 functionalities: Optional[_builtins.str] = None,
                 in_triage_at: Optional[Mapping[str, _builtins.str]] = None,
                 kind: Optional[_builtins.str] = None,
                 labels: Optional[_builtins.str] = None,
                 mitigated_at: Optional[Mapping[str, _builtins.str]] = None,
                 private: Optional[_builtins.bool] = None,
                 resolved_at: Optional[Mapping[str, _builtins.str]] = None,
                 services: Optional[_builtins.str] = None,
                 severity: Optional[_builtins.str] = None,
                 started_at: Optional[Mapping[str, _builtins.str]] = None,
                 status: Optional[_builtins.str] = None,
                 updated_at: Optional[Mapping[str, _builtins.str]] = None,
                 user: Optional[_builtins.str] = None,
                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetIncidentResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['acknowledgedAt'] = acknowledged_at
    __args__['closedAt'] = closed_at
    __args__['createdAt'] = created_at
    __args__['detectedAt'] = detected_at
    __args__['environments'] = environments
    __args__['functionalities'] = functionalities
    __args__['inTriageAt'] = in_triage_at
    __args__['kind'] = kind
    __args__['labels'] = labels
    __args__['mitigatedAt'] = mitigated_at
    __args__['private'] = private
    __args__['resolvedAt'] = resolved_at
    __args__['services'] = services
    __args__['severity'] = severity
    __args__['startedAt'] = started_at
    __args__['status'] = status
    __args__['updatedAt'] = updated_at
    __args__['user'] = user
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('rootly:index/getIncident:getIncident', __args__, opts=opts, typ=GetIncidentResult, package_ref=_utilities.get_package()).value

    return AwaitableGetIncidentResult(
        acknowledged_at=pulumi.get(__ret__, 'acknowledged_at'),
        closed_at=pulumi.get(__ret__, 'closed_at'),
        created_at=pulumi.get(__ret__, 'created_at'),
        detected_at=pulumi.get(__ret__, 'detected_at'),
        environments=pulumi.get(__ret__, 'environments'),
        functionalities=pulumi.get(__ret__, 'functionalities'),
        id=pulumi.get(__ret__, 'id'),
        in_triage_at=pulumi.get(__ret__, 'in_triage_at'),
        kind=pulumi.get(__ret__, 'kind'),
        labels=pulumi.get(__ret__, 'labels'),
        mitigated_at=pulumi.get(__ret__, 'mitigated_at'),
        private=pulumi.get(__ret__, 'private'),
        resolved_at=pulumi.get(__ret__, 'resolved_at'),
        services=pulumi.get(__ret__, 'services'),
        severity=pulumi.get(__ret__, 'severity'),
        started_at=pulumi.get(__ret__, 'started_at'),
        status=pulumi.get(__ret__, 'status'),
        updated_at=pulumi.get(__ret__, 'updated_at'),
        user=pulumi.get(__ret__, 'user'))
def get_incident_output(acknowledged_at: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                        closed_at: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                        created_at: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                        detected_at: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                        environments: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        functionalities: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        in_triage_at: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                        kind: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        labels: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        mitigated_at: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                        private: pulumi.Input[Optional[Optional[_builtins.bool]]] = None,
                        resolved_at: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                        services: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        severity: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        started_at: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                        status: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        updated_at: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                        user: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                        opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetIncidentResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['acknowledgedAt'] = acknowledged_at
    __args__['closedAt'] = closed_at
    __args__['createdAt'] = created_at
    __args__['detectedAt'] = detected_at
    __args__['environments'] = environments
    __args__['functionalities'] = functionalities
    __args__['inTriageAt'] = in_triage_at
    __args__['kind'] = kind
    __args__['labels'] = labels
    __args__['mitigatedAt'] = mitigated_at
    __args__['private'] = private
    __args__['resolvedAt'] = resolved_at
    __args__['services'] = services
    __args__['severity'] = severity
    __args__['startedAt'] = started_at
    __args__['status'] = status
    __args__['updatedAt'] = updated_at
    __args__['user'] = user
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('rootly:index/getIncident:getIncident', __args__, opts=opts, typ=GetIncidentResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetIncidentResult(
        acknowledged_at=pulumi.get(__response__, 'acknowledged_at'),
        closed_at=pulumi.get(__response__, 'closed_at'),
        created_at=pulumi.get(__response__, 'created_at'),
        detected_at=pulumi.get(__response__, 'detected_at'),
        environments=pulumi.get(__response__, 'environments'),
        functionalities=pulumi.get(__response__, 'functionalities'),
        id=pulumi.get(__response__, 'id'),
        in_triage_at=pulumi.get(__response__, 'in_triage_at'),
        kind=pulumi.get(__response__, 'kind'),
        labels=pulumi.get(__response__, 'labels'),
        mitigated_at=pulumi.get(__response__, 'mitigated_at'),
        private=pulumi.get(__response__, 'private'),
        resolved_at=pulumi.get(__response__, 'resolved_at'),
        services=pulumi.get(__response__, 'services'),
        severity=pulumi.get(__response__, 'severity'),
        started_at=pulumi.get(__response__, 'started_at'),
        status=pulumi.get(__response__, 'status'),
        updated_at=pulumi.get(__response__, 'updated_at'),
        user=pulumi.get(__response__, 'user')))
