# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetAlertRoutingRuleResult',
    'AwaitableGetAlertRoutingRuleResult',
    'get_alert_routing_rule',
    'get_alert_routing_rule_output',
]

@pulumi.output_type
class GetAlertRoutingRuleResult:
    """
    A collection of values returned by getAlertRoutingRule.
    """
    def __init__(__self__, created_at=None, id=None, name=None):
        if created_at and not isinstance(created_at, dict):
            raise TypeError("Expected argument 'created_at' to be a dict")
        pulumi.set(__self__, "created_at", created_at)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")


class AwaitableGetAlertRoutingRuleResult(GetAlertRoutingRuleResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAlertRoutingRuleResult(
            created_at=self.created_at,
            id=self.id,
            name=self.name)


def get_alert_routing_rule(created_at: Optional[Mapping[str, _builtins.str]] = None,
                           name: Optional[_builtins.str] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAlertRoutingRuleResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['createdAt'] = created_at
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('rootly:index/getAlertRoutingRule:getAlertRoutingRule', __args__, opts=opts, typ=GetAlertRoutingRuleResult, package_ref=_utilities.get_package()).value

    return AwaitableGetAlertRoutingRuleResult(
        created_at=pulumi.get(__ret__, 'created_at'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'))
def get_alert_routing_rule_output(created_at: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                                  name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAlertRoutingRuleResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['createdAt'] = created_at
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('rootly:index/getAlertRoutingRule:getAlertRoutingRule', __args__, opts=opts, typ=GetAlertRoutingRuleResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetAlertRoutingRuleResult(
        created_at=pulumi.get(__response__, 'created_at'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name')))
