# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetCustomFieldsResult',
    'AwaitableGetCustomFieldsResult',
    'get_custom_fields',
    'get_custom_fields_output',
]

@pulumi.output_type
class GetCustomFieldsResult:
    """
    A collection of values returned by getCustomFields.
    """
    def __init__(__self__, custom_fields=None, enabled=None, id=None, kind=None, label=None, slug=None):
        if custom_fields and not isinstance(custom_fields, list):
            raise TypeError("Expected argument 'custom_fields' to be a list")
        pulumi.set(__self__, "custom_fields", custom_fields)
        if enabled and not isinstance(enabled, bool):
            raise TypeError("Expected argument 'enabled' to be a bool")
        pulumi.set(__self__, "enabled", enabled)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if kind and not isinstance(kind, str):
            raise TypeError("Expected argument 'kind' to be a str")
        pulumi.set(__self__, "kind", kind)
        if label and not isinstance(label, str):
            raise TypeError("Expected argument 'label' to be a str")
        pulumi.set(__self__, "label", label)
        if slug and not isinstance(slug, str):
            raise TypeError("Expected argument 'slug' to be a str")
        pulumi.set(__self__, "slug", slug)

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> Sequence['outputs.GetCustomFieldsCustomFieldResult']:
        return pulumi.get(self, "custom_fields")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "kind")

    @_builtins.property
    @pulumi.getter
    def label(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "label")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "slug")


class AwaitableGetCustomFieldsResult(GetCustomFieldsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCustomFieldsResult(
            custom_fields=self.custom_fields,
            enabled=self.enabled,
            id=self.id,
            kind=self.kind,
            label=self.label,
            slug=self.slug)


def get_custom_fields(enabled: Optional[_builtins.bool] = None,
                      id: Optional[_builtins.str] = None,
                      kind: Optional[_builtins.str] = None,
                      label: Optional[_builtins.str] = None,
                      slug: Optional[_builtins.str] = None,
                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCustomFieldsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['enabled'] = enabled
    __args__['id'] = id
    __args__['kind'] = kind
    __args__['label'] = label
    __args__['slug'] = slug
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('rootly:index/getCustomFields:getCustomFields', __args__, opts=opts, typ=GetCustomFieldsResult, package_ref=_utilities.get_package()).value

    return AwaitableGetCustomFieldsResult(
        custom_fields=pulumi.get(__ret__, 'custom_fields'),
        enabled=pulumi.get(__ret__, 'enabled'),
        id=pulumi.get(__ret__, 'id'),
        kind=pulumi.get(__ret__, 'kind'),
        label=pulumi.get(__ret__, 'label'),
        slug=pulumi.get(__ret__, 'slug'))
def get_custom_fields_output(enabled: pulumi.Input[Optional[Optional[_builtins.bool]]] = None,
                             id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                             kind: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                             label: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                             slug: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                             opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCustomFieldsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['enabled'] = enabled
    __args__['id'] = id
    __args__['kind'] = kind
    __args__['label'] = label
    __args__['slug'] = slug
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('rootly:index/getCustomFields:getCustomFields', __args__, opts=opts, typ=GetCustomFieldsResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetCustomFieldsResult(
        custom_fields=pulumi.get(__response__, 'custom_fields'),
        enabled=pulumi.get(__response__, 'enabled'),
        id=pulumi.get(__response__, 'id'),
        kind=pulumi.get(__response__, 'kind'),
        label=pulumi.get(__response__, 'label'),
        slug=pulumi.get(__response__, 'slug')))
