# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetIncidentPermissionSetResourceResult',
    'AwaitableGetIncidentPermissionSetResourceResult',
    'get_incident_permission_set_resource',
    'get_incident_permission_set_resource_output',
]

@pulumi.output_type
class GetIncidentPermissionSetResourceResult:
    """
    A collection of values returned by getIncidentPermissionSetResource.
    """
    def __init__(__self__, created_at=None, id=None, incident_permission_set_id=None, kind=None):
        if created_at and not isinstance(created_at, dict):
            raise TypeError("Expected argument 'created_at' to be a dict")
        pulumi.set(__self__, "created_at", created_at)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if incident_permission_set_id and not isinstance(incident_permission_set_id, str):
            raise TypeError("Expected argument 'incident_permission_set_id' to be a str")
        pulumi.set(__self__, "incident_permission_set_id", incident_permission_set_id)
        if kind and not isinstance(kind, str):
            raise TypeError("Expected argument 'kind' to be a str")
        pulumi.set(__self__, "kind", kind)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> Optional[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="incidentPermissionSetId")
    def incident_permission_set_id(self) -> _builtins.str:
        return pulumi.get(self, "incident_permission_set_id")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> _builtins.str:
        return pulumi.get(self, "kind")


class AwaitableGetIncidentPermissionSetResourceResult(GetIncidentPermissionSetResourceResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetIncidentPermissionSetResourceResult(
            created_at=self.created_at,
            id=self.id,
            incident_permission_set_id=self.incident_permission_set_id,
            kind=self.kind)


def get_incident_permission_set_resource(created_at: Optional[Mapping[str, _builtins.str]] = None,
                                         incident_permission_set_id: Optional[_builtins.str] = None,
                                         kind: Optional[_builtins.str] = None,
                                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetIncidentPermissionSetResourceResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['createdAt'] = created_at
    __args__['incidentPermissionSetId'] = incident_permission_set_id
    __args__['kind'] = kind
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('rootly:index/getIncidentPermissionSetResource:getIncidentPermissionSetResource', __args__, opts=opts, typ=GetIncidentPermissionSetResourceResult, package_ref=_utilities.get_package()).value

    return AwaitableGetIncidentPermissionSetResourceResult(
        created_at=pulumi.get(__ret__, 'created_at'),
        id=pulumi.get(__ret__, 'id'),
        incident_permission_set_id=pulumi.get(__ret__, 'incident_permission_set_id'),
        kind=pulumi.get(__ret__, 'kind'))
def get_incident_permission_set_resource_output(created_at: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                                                incident_permission_set_id: pulumi.Input[Optional[_builtins.str]] = None,
                                                kind: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                                opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetIncidentPermissionSetResourceResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['createdAt'] = created_at
    __args__['incidentPermissionSetId'] = incident_permission_set_id
    __args__['kind'] = kind
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('rootly:index/getIncidentPermissionSetResource:getIncidentPermissionSetResource', __args__, opts=opts, typ=GetIncidentPermissionSetResourceResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetIncidentPermissionSetResourceResult(
        created_at=pulumi.get(__response__, 'created_at'),
        id=pulumi.get(__response__, 'id'),
        incident_permission_set_id=pulumi.get(__response__, 'incident_permission_set_id'),
        kind=pulumi.get(__response__, 'kind')))
