# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['SlaArgs', 'Sla']

@pulumi.input_type
class SlaArgs:
    def __init__(__self__, *,
                 assignment_deadline_days: pulumi.Input[_builtins.float],
                 assignment_deadline_parent_status: pulumi.Input[_builtins.str],
                 completion_deadline_days: pulumi.Input[_builtins.float],
                 completion_deadline_parent_status: pulumi.Input[_builtins.str],
                 assignment_deadline_sub_status_id: pulumi.Input[Optional[_builtins.str]] = None,
                 assignment_skip_weekends: pulumi.Input[Optional[_builtins.bool]] = None,
                 completion_deadline_sub_status_id: pulumi.Input[Optional[_builtins.str]] = None,
                 completion_skip_weekends: pulumi.Input[Optional[_builtins.bool]] = None,
                 condition_match_type: pulumi.Input[Optional[_builtins.str]] = None,
                 conditions: pulumi.Input[Optional[Sequence[pulumi.Input['SlaConditionArgs']]]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 entity_type: pulumi.Input[Optional[_builtins.str]] = None,
                 manager_role_id: pulumi.Input[Optional[_builtins.str]] = None,
                 manager_user_id: pulumi.Input[Optional[_builtins.float]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 notification_configurations: pulumi.Input[Optional[Sequence[pulumi.Input['SlaNotificationConfigurationArgs']]]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 sla_id: pulumi.Input[Optional[_builtins.str]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Sla resource.

        :param pulumi.Input[_builtins.float] assignment_deadline_days: Number of days for the assignment deadline
        :param pulumi.Input[_builtins.str] assignment_deadline_parent_status: The incident parent status that triggers the assignment deadline
        :param pulumi.Input[_builtins.float] completion_deadline_days: Number of days for the completion deadline
        :param pulumi.Input[_builtins.str] completion_deadline_parent_status: The incident parent status that triggers the completion deadline
        :param pulumi.Input[_builtins.str] assignment_deadline_sub_status_id: Sub-status for the assignment deadline. Required when custom lifecycle statuses are enabled on the team.
        :param pulumi.Input[_builtins.bool] assignment_skip_weekends: Whether to skip weekends when calculating the assignment deadline. Value must be one of true or false
        :param pulumi.Input[_builtins.str] completion_deadline_sub_status_id: Sub-status for the completion deadline. Required when custom lifecycle statuses are enabled on the team.
        :param pulumi.Input[_builtins.bool] completion_skip_weekends: Whether to skip weekends when calculating the completion deadline. Value must be one of true or false
        :param pulumi.Input[_builtins.str] condition_match_type: Whether all or any conditions must match. Value must be one of `ALL`, `ANY`.
        :param pulumi.Input[Sequence[pulumi.Input['SlaConditionArgs']]] conditions: Conditions that determine which incidents this SLA applies to
        :param pulumi.Input[_builtins.str] description: A description of the SLA
        :param pulumi.Input[_builtins.str] entity_type: The entity type this SLA applies to. Value must be one of <span pulumi-lang-nodejs="`followUp`" pulumi-lang-dotnet="`FollowUp`" pulumi-lang-go="`followUp`" pulumi-lang-python="`follow_up`" pulumi-lang-yaml="`followUp`" pulumi-lang-java="`followUp`" pulumi-lang-hcl="`follow_up`">`followUp`</span>.
        :param pulumi.Input[_builtins.str] manager_role_id: The ID of the manager incident role. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        :param pulumi.Input[_builtins.float] manager_user_id: The ID of the manager user. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        :param pulumi.Input[_builtins.str] name: The name of the SLA
        :param pulumi.Input[Sequence[pulumi.Input['SlaNotificationConfigurationArgs']]] notification_configurations: Notification timing configurations
        :param pulumi.Input[_builtins.float] position: Position of the SLA for ordering
        :param pulumi.Input[_builtins.str] slug: The slug of the SLA
        """
        pulumi.set(__self__, "assignment_deadline_days", assignment_deadline_days)
        pulumi.set(__self__, "assignment_deadline_parent_status", assignment_deadline_parent_status)
        pulumi.set(__self__, "completion_deadline_days", completion_deadline_days)
        pulumi.set(__self__, "completion_deadline_parent_status", completion_deadline_parent_status)
        if assignment_deadline_sub_status_id is not None:
            pulumi.set(__self__, "assignment_deadline_sub_status_id", assignment_deadline_sub_status_id)
        if assignment_skip_weekends is not None:
            pulumi.set(__self__, "assignment_skip_weekends", assignment_skip_weekends)
        if completion_deadline_sub_status_id is not None:
            pulumi.set(__self__, "completion_deadline_sub_status_id", completion_deadline_sub_status_id)
        if completion_skip_weekends is not None:
            pulumi.set(__self__, "completion_skip_weekends", completion_skip_weekends)
        if condition_match_type is not None:
            pulumi.set(__self__, "condition_match_type", condition_match_type)
        if conditions is not None:
            pulumi.set(__self__, "conditions", conditions)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if entity_type is not None:
            pulumi.set(__self__, "entity_type", entity_type)
        if manager_role_id is not None:
            pulumi.set(__self__, "manager_role_id", manager_role_id)
        if manager_user_id is not None:
            pulumi.set(__self__, "manager_user_id", manager_user_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if notification_configurations is not None:
            pulumi.set(__self__, "notification_configurations", notification_configurations)
        if position is not None:
            pulumi.set(__self__, "position", position)
        if sla_id is not None:
            pulumi.set(__self__, "sla_id", sla_id)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)

    @_builtins.property
    @pulumi.getter(name="assignmentDeadlineDays")
    def assignment_deadline_days(self) -> pulumi.Input[_builtins.float]:
        """
        Number of days for the assignment deadline
        """
        return pulumi.get(self, "assignment_deadline_days")

    @assignment_deadline_days.setter
    def assignment_deadline_days(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "assignment_deadline_days", value)

    @_builtins.property
    @pulumi.getter(name="assignmentDeadlineParentStatus")
    def assignment_deadline_parent_status(self) -> pulumi.Input[_builtins.str]:
        """
        The incident parent status that triggers the assignment deadline
        """
        return pulumi.get(self, "assignment_deadline_parent_status")

    @assignment_deadline_parent_status.setter
    def assignment_deadline_parent_status(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "assignment_deadline_parent_status", value)

    @_builtins.property
    @pulumi.getter(name="completionDeadlineDays")
    def completion_deadline_days(self) -> pulumi.Input[_builtins.float]:
        """
        Number of days for the completion deadline
        """
        return pulumi.get(self, "completion_deadline_days")

    @completion_deadline_days.setter
    def completion_deadline_days(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "completion_deadline_days", value)

    @_builtins.property
    @pulumi.getter(name="completionDeadlineParentStatus")
    def completion_deadline_parent_status(self) -> pulumi.Input[_builtins.str]:
        """
        The incident parent status that triggers the completion deadline
        """
        return pulumi.get(self, "completion_deadline_parent_status")

    @completion_deadline_parent_status.setter
    def completion_deadline_parent_status(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "completion_deadline_parent_status", value)

    @_builtins.property
    @pulumi.getter(name="assignmentDeadlineSubStatusId")
    def assignment_deadline_sub_status_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Sub-status for the assignment deadline. Required when custom lifecycle statuses are enabled on the team.
        """
        return pulumi.get(self, "assignment_deadline_sub_status_id")

    @assignment_deadline_sub_status_id.setter
    def assignment_deadline_sub_status_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "assignment_deadline_sub_status_id", value)

    @_builtins.property
    @pulumi.getter(name="assignmentSkipWeekends")
    def assignment_skip_weekends(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to skip weekends when calculating the assignment deadline. Value must be one of true or false
        """
        return pulumi.get(self, "assignment_skip_weekends")

    @assignment_skip_weekends.setter
    def assignment_skip_weekends(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "assignment_skip_weekends", value)

    @_builtins.property
    @pulumi.getter(name="completionDeadlineSubStatusId")
    def completion_deadline_sub_status_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Sub-status for the completion deadline. Required when custom lifecycle statuses are enabled on the team.
        """
        return pulumi.get(self, "completion_deadline_sub_status_id")

    @completion_deadline_sub_status_id.setter
    def completion_deadline_sub_status_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "completion_deadline_sub_status_id", value)

    @_builtins.property
    @pulumi.getter(name="completionSkipWeekends")
    def completion_skip_weekends(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to skip weekends when calculating the completion deadline. Value must be one of true or false
        """
        return pulumi.get(self, "completion_skip_weekends")

    @completion_skip_weekends.setter
    def completion_skip_weekends(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "completion_skip_weekends", value)

    @_builtins.property
    @pulumi.getter(name="conditionMatchType")
    def condition_match_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Whether all or any conditions must match. Value must be one of `ALL`, `ANY`.
        """
        return pulumi.get(self, "condition_match_type")

    @condition_match_type.setter
    def condition_match_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "condition_match_type", value)

    @_builtins.property
    @pulumi.getter
    def conditions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['SlaConditionArgs']]]]:
        """
        Conditions that determine which incidents this SLA applies to
        """
        return pulumi.get(self, "conditions")

    @conditions.setter
    def conditions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['SlaConditionArgs']]]]):
        pulumi.set(self, "conditions", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A description of the SLA
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="entityType")
    def entity_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The entity type this SLA applies to. Value must be one of <span pulumi-lang-nodejs="`followUp`" pulumi-lang-dotnet="`FollowUp`" pulumi-lang-go="`followUp`" pulumi-lang-python="`follow_up`" pulumi-lang-yaml="`followUp`" pulumi-lang-java="`followUp`" pulumi-lang-hcl="`follow_up`">`followUp`</span>.
        """
        return pulumi.get(self, "entity_type")

    @entity_type.setter
    def entity_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "entity_type", value)

    @_builtins.property
    @pulumi.getter(name="managerRoleId")
    def manager_role_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the manager incident role. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        """
        return pulumi.get(self, "manager_role_id")

    @manager_role_id.setter
    def manager_role_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "manager_role_id", value)

    @_builtins.property
    @pulumi.getter(name="managerUserId")
    def manager_user_id(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The ID of the manager user. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        """
        return pulumi.get(self, "manager_user_id")

    @manager_user_id.setter
    def manager_user_id(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "manager_user_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the SLA
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="notificationConfigurations")
    def notification_configurations(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['SlaNotificationConfigurationArgs']]]]:
        """
        Notification timing configurations
        """
        return pulumi.get(self, "notification_configurations")

    @notification_configurations.setter
    def notification_configurations(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['SlaNotificationConfigurationArgs']]]]):
        pulumi.set(self, "notification_configurations", value)

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Position of the SLA for ordering
        """
        return pulumi.get(self, "position")

    @position.setter
    def position(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "position", value)

    @_builtins.property
    @pulumi.getter(name="slaId")
    def sla_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "sla_id")

    @sla_id.setter
    def sla_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "sla_id", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The slug of the SLA
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "slug", value)


@pulumi.input_type
class _SlaState:
    def __init__(__self__, *,
                 assignment_deadline_days: pulumi.Input[Optional[_builtins.float]] = None,
                 assignment_deadline_parent_status: pulumi.Input[Optional[_builtins.str]] = None,
                 assignment_deadline_sub_status_id: pulumi.Input[Optional[_builtins.str]] = None,
                 assignment_skip_weekends: pulumi.Input[Optional[_builtins.bool]] = None,
                 completion_deadline_days: pulumi.Input[Optional[_builtins.float]] = None,
                 completion_deadline_parent_status: pulumi.Input[Optional[_builtins.str]] = None,
                 completion_deadline_sub_status_id: pulumi.Input[Optional[_builtins.str]] = None,
                 completion_skip_weekends: pulumi.Input[Optional[_builtins.bool]] = None,
                 condition_match_type: pulumi.Input[Optional[_builtins.str]] = None,
                 conditions: pulumi.Input[Optional[Sequence[pulumi.Input['SlaConditionArgs']]]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 entity_type: pulumi.Input[Optional[_builtins.str]] = None,
                 manager_role_id: pulumi.Input[Optional[_builtins.str]] = None,
                 manager_user_id: pulumi.Input[Optional[_builtins.float]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 notification_configurations: pulumi.Input[Optional[Sequence[pulumi.Input['SlaNotificationConfigurationArgs']]]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 sla_id: pulumi.Input[Optional[_builtins.str]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Sla resources.

        :param pulumi.Input[_builtins.float] assignment_deadline_days: Number of days for the assignment deadline
        :param pulumi.Input[_builtins.str] assignment_deadline_parent_status: The incident parent status that triggers the assignment deadline
        :param pulumi.Input[_builtins.str] assignment_deadline_sub_status_id: Sub-status for the assignment deadline. Required when custom lifecycle statuses are enabled on the team.
        :param pulumi.Input[_builtins.bool] assignment_skip_weekends: Whether to skip weekends when calculating the assignment deadline. Value must be one of true or false
        :param pulumi.Input[_builtins.float] completion_deadline_days: Number of days for the completion deadline
        :param pulumi.Input[_builtins.str] completion_deadline_parent_status: The incident parent status that triggers the completion deadline
        :param pulumi.Input[_builtins.str] completion_deadline_sub_status_id: Sub-status for the completion deadline. Required when custom lifecycle statuses are enabled on the team.
        :param pulumi.Input[_builtins.bool] completion_skip_weekends: Whether to skip weekends when calculating the completion deadline. Value must be one of true or false
        :param pulumi.Input[_builtins.str] condition_match_type: Whether all or any conditions must match. Value must be one of `ALL`, `ANY`.
        :param pulumi.Input[Sequence[pulumi.Input['SlaConditionArgs']]] conditions: Conditions that determine which incidents this SLA applies to
        :param pulumi.Input[_builtins.str] description: A description of the SLA
        :param pulumi.Input[_builtins.str] entity_type: The entity type this SLA applies to. Value must be one of <span pulumi-lang-nodejs="`followUp`" pulumi-lang-dotnet="`FollowUp`" pulumi-lang-go="`followUp`" pulumi-lang-python="`follow_up`" pulumi-lang-yaml="`followUp`" pulumi-lang-java="`followUp`" pulumi-lang-hcl="`follow_up`">`followUp`</span>.
        :param pulumi.Input[_builtins.str] manager_role_id: The ID of the manager incident role. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        :param pulumi.Input[_builtins.float] manager_user_id: The ID of the manager user. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        :param pulumi.Input[_builtins.str] name: The name of the SLA
        :param pulumi.Input[Sequence[pulumi.Input['SlaNotificationConfigurationArgs']]] notification_configurations: Notification timing configurations
        :param pulumi.Input[_builtins.float] position: Position of the SLA for ordering
        :param pulumi.Input[_builtins.str] slug: The slug of the SLA
        """
        if assignment_deadline_days is not None:
            pulumi.set(__self__, "assignment_deadline_days", assignment_deadline_days)
        if assignment_deadline_parent_status is not None:
            pulumi.set(__self__, "assignment_deadline_parent_status", assignment_deadline_parent_status)
        if assignment_deadline_sub_status_id is not None:
            pulumi.set(__self__, "assignment_deadline_sub_status_id", assignment_deadline_sub_status_id)
        if assignment_skip_weekends is not None:
            pulumi.set(__self__, "assignment_skip_weekends", assignment_skip_weekends)
        if completion_deadline_days is not None:
            pulumi.set(__self__, "completion_deadline_days", completion_deadline_days)
        if completion_deadline_parent_status is not None:
            pulumi.set(__self__, "completion_deadline_parent_status", completion_deadline_parent_status)
        if completion_deadline_sub_status_id is not None:
            pulumi.set(__self__, "completion_deadline_sub_status_id", completion_deadline_sub_status_id)
        if completion_skip_weekends is not None:
            pulumi.set(__self__, "completion_skip_weekends", completion_skip_weekends)
        if condition_match_type is not None:
            pulumi.set(__self__, "condition_match_type", condition_match_type)
        if conditions is not None:
            pulumi.set(__self__, "conditions", conditions)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if entity_type is not None:
            pulumi.set(__self__, "entity_type", entity_type)
        if manager_role_id is not None:
            pulumi.set(__self__, "manager_role_id", manager_role_id)
        if manager_user_id is not None:
            pulumi.set(__self__, "manager_user_id", manager_user_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if notification_configurations is not None:
            pulumi.set(__self__, "notification_configurations", notification_configurations)
        if position is not None:
            pulumi.set(__self__, "position", position)
        if sla_id is not None:
            pulumi.set(__self__, "sla_id", sla_id)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)

    @_builtins.property
    @pulumi.getter(name="assignmentDeadlineDays")
    def assignment_deadline_days(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Number of days for the assignment deadline
        """
        return pulumi.get(self, "assignment_deadline_days")

    @assignment_deadline_days.setter
    def assignment_deadline_days(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "assignment_deadline_days", value)

    @_builtins.property
    @pulumi.getter(name="assignmentDeadlineParentStatus")
    def assignment_deadline_parent_status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The incident parent status that triggers the assignment deadline
        """
        return pulumi.get(self, "assignment_deadline_parent_status")

    @assignment_deadline_parent_status.setter
    def assignment_deadline_parent_status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "assignment_deadline_parent_status", value)

    @_builtins.property
    @pulumi.getter(name="assignmentDeadlineSubStatusId")
    def assignment_deadline_sub_status_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Sub-status for the assignment deadline. Required when custom lifecycle statuses are enabled on the team.
        """
        return pulumi.get(self, "assignment_deadline_sub_status_id")

    @assignment_deadline_sub_status_id.setter
    def assignment_deadline_sub_status_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "assignment_deadline_sub_status_id", value)

    @_builtins.property
    @pulumi.getter(name="assignmentSkipWeekends")
    def assignment_skip_weekends(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to skip weekends when calculating the assignment deadline. Value must be one of true or false
        """
        return pulumi.get(self, "assignment_skip_weekends")

    @assignment_skip_weekends.setter
    def assignment_skip_weekends(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "assignment_skip_weekends", value)

    @_builtins.property
    @pulumi.getter(name="completionDeadlineDays")
    def completion_deadline_days(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Number of days for the completion deadline
        """
        return pulumi.get(self, "completion_deadline_days")

    @completion_deadline_days.setter
    def completion_deadline_days(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "completion_deadline_days", value)

    @_builtins.property
    @pulumi.getter(name="completionDeadlineParentStatus")
    def completion_deadline_parent_status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The incident parent status that triggers the completion deadline
        """
        return pulumi.get(self, "completion_deadline_parent_status")

    @completion_deadline_parent_status.setter
    def completion_deadline_parent_status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "completion_deadline_parent_status", value)

    @_builtins.property
    @pulumi.getter(name="completionDeadlineSubStatusId")
    def completion_deadline_sub_status_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Sub-status for the completion deadline. Required when custom lifecycle statuses are enabled on the team.
        """
        return pulumi.get(self, "completion_deadline_sub_status_id")

    @completion_deadline_sub_status_id.setter
    def completion_deadline_sub_status_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "completion_deadline_sub_status_id", value)

    @_builtins.property
    @pulumi.getter(name="completionSkipWeekends")
    def completion_skip_weekends(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to skip weekends when calculating the completion deadline. Value must be one of true or false
        """
        return pulumi.get(self, "completion_skip_weekends")

    @completion_skip_weekends.setter
    def completion_skip_weekends(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "completion_skip_weekends", value)

    @_builtins.property
    @pulumi.getter(name="conditionMatchType")
    def condition_match_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Whether all or any conditions must match. Value must be one of `ALL`, `ANY`.
        """
        return pulumi.get(self, "condition_match_type")

    @condition_match_type.setter
    def condition_match_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "condition_match_type", value)

    @_builtins.property
    @pulumi.getter
    def conditions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['SlaConditionArgs']]]]:
        """
        Conditions that determine which incidents this SLA applies to
        """
        return pulumi.get(self, "conditions")

    @conditions.setter
    def conditions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['SlaConditionArgs']]]]):
        pulumi.set(self, "conditions", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A description of the SLA
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="entityType")
    def entity_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The entity type this SLA applies to. Value must be one of <span pulumi-lang-nodejs="`followUp`" pulumi-lang-dotnet="`FollowUp`" pulumi-lang-go="`followUp`" pulumi-lang-python="`follow_up`" pulumi-lang-yaml="`followUp`" pulumi-lang-java="`followUp`" pulumi-lang-hcl="`follow_up`">`followUp`</span>.
        """
        return pulumi.get(self, "entity_type")

    @entity_type.setter
    def entity_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "entity_type", value)

    @_builtins.property
    @pulumi.getter(name="managerRoleId")
    def manager_role_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the manager incident role. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        """
        return pulumi.get(self, "manager_role_id")

    @manager_role_id.setter
    def manager_role_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "manager_role_id", value)

    @_builtins.property
    @pulumi.getter(name="managerUserId")
    def manager_user_id(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The ID of the manager user. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        """
        return pulumi.get(self, "manager_user_id")

    @manager_user_id.setter
    def manager_user_id(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "manager_user_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the SLA
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="notificationConfigurations")
    def notification_configurations(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['SlaNotificationConfigurationArgs']]]]:
        """
        Notification timing configurations
        """
        return pulumi.get(self, "notification_configurations")

    @notification_configurations.setter
    def notification_configurations(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['SlaNotificationConfigurationArgs']]]]):
        pulumi.set(self, "notification_configurations", value)

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Position of the SLA for ordering
        """
        return pulumi.get(self, "position")

    @position.setter
    def position(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "position", value)

    @_builtins.property
    @pulumi.getter(name="slaId")
    def sla_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "sla_id")

    @sla_id.setter
    def sla_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "sla_id", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The slug of the SLA
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "slug", value)


@pulumi.type_token("rootly:index/sla:Sla")
class Sla(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 assignment_deadline_days: pulumi.Input[Optional[_builtins.float]] = None,
                 assignment_deadline_parent_status: pulumi.Input[Optional[_builtins.str]] = None,
                 assignment_deadline_sub_status_id: pulumi.Input[Optional[_builtins.str]] = None,
                 assignment_skip_weekends: pulumi.Input[Optional[_builtins.bool]] = None,
                 completion_deadline_days: pulumi.Input[Optional[_builtins.float]] = None,
                 completion_deadline_parent_status: pulumi.Input[Optional[_builtins.str]] = None,
                 completion_deadline_sub_status_id: pulumi.Input[Optional[_builtins.str]] = None,
                 completion_skip_weekends: pulumi.Input[Optional[_builtins.bool]] = None,
                 condition_match_type: pulumi.Input[Optional[_builtins.str]] = None,
                 conditions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SlaConditionArgs', 'SlaConditionArgsDict']]]]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 entity_type: pulumi.Input[Optional[_builtins.str]] = None,
                 manager_role_id: pulumi.Input[Optional[_builtins.str]] = None,
                 manager_user_id: pulumi.Input[Optional[_builtins.float]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 notification_configurations: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SlaNotificationConfigurationArgs', 'SlaNotificationConfigurationArgsDict']]]]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 sla_id: pulumi.Input[Optional[_builtins.str]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Sla resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.float] assignment_deadline_days: Number of days for the assignment deadline
        :param pulumi.Input[_builtins.str] assignment_deadline_parent_status: The incident parent status that triggers the assignment deadline
        :param pulumi.Input[_builtins.str] assignment_deadline_sub_status_id: Sub-status for the assignment deadline. Required when custom lifecycle statuses are enabled on the team.
        :param pulumi.Input[_builtins.bool] assignment_skip_weekends: Whether to skip weekends when calculating the assignment deadline. Value must be one of true or false
        :param pulumi.Input[_builtins.float] completion_deadline_days: Number of days for the completion deadline
        :param pulumi.Input[_builtins.str] completion_deadline_parent_status: The incident parent status that triggers the completion deadline
        :param pulumi.Input[_builtins.str] completion_deadline_sub_status_id: Sub-status for the completion deadline. Required when custom lifecycle statuses are enabled on the team.
        :param pulumi.Input[_builtins.bool] completion_skip_weekends: Whether to skip weekends when calculating the completion deadline. Value must be one of true or false
        :param pulumi.Input[_builtins.str] condition_match_type: Whether all or any conditions must match. Value must be one of `ALL`, `ANY`.
        :param pulumi.Input[Sequence[pulumi.Input[Union['SlaConditionArgs', 'SlaConditionArgsDict']]]] conditions: Conditions that determine which incidents this SLA applies to
        :param pulumi.Input[_builtins.str] description: A description of the SLA
        :param pulumi.Input[_builtins.str] entity_type: The entity type this SLA applies to. Value must be one of <span pulumi-lang-nodejs="`followUp`" pulumi-lang-dotnet="`FollowUp`" pulumi-lang-go="`followUp`" pulumi-lang-python="`follow_up`" pulumi-lang-yaml="`followUp`" pulumi-lang-java="`followUp`" pulumi-lang-hcl="`follow_up`">`followUp`</span>.
        :param pulumi.Input[_builtins.str] manager_role_id: The ID of the manager incident role. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        :param pulumi.Input[_builtins.float] manager_user_id: The ID of the manager user. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        :param pulumi.Input[_builtins.str] name: The name of the SLA
        :param pulumi.Input[Sequence[pulumi.Input[Union['SlaNotificationConfigurationArgs', 'SlaNotificationConfigurationArgsDict']]]] notification_configurations: Notification timing configurations
        :param pulumi.Input[_builtins.float] position: Position of the SLA for ordering
        :param pulumi.Input[_builtins.str] slug: The slug of the SLA
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SlaArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Sla resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param SlaArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SlaArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 assignment_deadline_days: pulumi.Input[Optional[_builtins.float]] = None,
                 assignment_deadline_parent_status: pulumi.Input[Optional[_builtins.str]] = None,
                 assignment_deadline_sub_status_id: pulumi.Input[Optional[_builtins.str]] = None,
                 assignment_skip_weekends: pulumi.Input[Optional[_builtins.bool]] = None,
                 completion_deadline_days: pulumi.Input[Optional[_builtins.float]] = None,
                 completion_deadline_parent_status: pulumi.Input[Optional[_builtins.str]] = None,
                 completion_deadline_sub_status_id: pulumi.Input[Optional[_builtins.str]] = None,
                 completion_skip_weekends: pulumi.Input[Optional[_builtins.bool]] = None,
                 condition_match_type: pulumi.Input[Optional[_builtins.str]] = None,
                 conditions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SlaConditionArgs', 'SlaConditionArgsDict']]]]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 entity_type: pulumi.Input[Optional[_builtins.str]] = None,
                 manager_role_id: pulumi.Input[Optional[_builtins.str]] = None,
                 manager_user_id: pulumi.Input[Optional[_builtins.float]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 notification_configurations: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SlaNotificationConfigurationArgs', 'SlaNotificationConfigurationArgsDict']]]]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 sla_id: pulumi.Input[Optional[_builtins.str]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SlaArgs.__new__(SlaArgs)

            if assignment_deadline_days is None and not opts.urn:
                raise TypeError("Missing required property 'assignment_deadline_days'")
            __props__.__dict__["assignment_deadline_days"] = assignment_deadline_days
            if assignment_deadline_parent_status is None and not opts.urn:
                raise TypeError("Missing required property 'assignment_deadline_parent_status'")
            __props__.__dict__["assignment_deadline_parent_status"] = assignment_deadline_parent_status
            __props__.__dict__["assignment_deadline_sub_status_id"] = assignment_deadline_sub_status_id
            __props__.__dict__["assignment_skip_weekends"] = assignment_skip_weekends
            if completion_deadline_days is None and not opts.urn:
                raise TypeError("Missing required property 'completion_deadline_days'")
            __props__.__dict__["completion_deadline_days"] = completion_deadline_days
            if completion_deadline_parent_status is None and not opts.urn:
                raise TypeError("Missing required property 'completion_deadline_parent_status'")
            __props__.__dict__["completion_deadline_parent_status"] = completion_deadline_parent_status
            __props__.__dict__["completion_deadline_sub_status_id"] = completion_deadline_sub_status_id
            __props__.__dict__["completion_skip_weekends"] = completion_skip_weekends
            __props__.__dict__["condition_match_type"] = condition_match_type
            __props__.__dict__["conditions"] = conditions
            __props__.__dict__["description"] = description
            __props__.__dict__["entity_type"] = entity_type
            __props__.__dict__["manager_role_id"] = manager_role_id
            __props__.__dict__["manager_user_id"] = manager_user_id
            __props__.__dict__["name"] = name
            __props__.__dict__["notification_configurations"] = notification_configurations
            __props__.__dict__["position"] = position
            __props__.__dict__["sla_id"] = sla_id
            __props__.__dict__["slug"] = slug
        super(Sla, __self__).__init__(
            'rootly:index/sla:Sla',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            assignment_deadline_days: pulumi.Input[Optional[_builtins.float]] = None,
            assignment_deadline_parent_status: pulumi.Input[Optional[_builtins.str]] = None,
            assignment_deadline_sub_status_id: pulumi.Input[Optional[_builtins.str]] = None,
            assignment_skip_weekends: pulumi.Input[Optional[_builtins.bool]] = None,
            completion_deadline_days: pulumi.Input[Optional[_builtins.float]] = None,
            completion_deadline_parent_status: pulumi.Input[Optional[_builtins.str]] = None,
            completion_deadline_sub_status_id: pulumi.Input[Optional[_builtins.str]] = None,
            completion_skip_weekends: pulumi.Input[Optional[_builtins.bool]] = None,
            condition_match_type: pulumi.Input[Optional[_builtins.str]] = None,
            conditions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SlaConditionArgs', 'SlaConditionArgsDict']]]]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            entity_type: pulumi.Input[Optional[_builtins.str]] = None,
            manager_role_id: pulumi.Input[Optional[_builtins.str]] = None,
            manager_user_id: pulumi.Input[Optional[_builtins.float]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            notification_configurations: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SlaNotificationConfigurationArgs', 'SlaNotificationConfigurationArgsDict']]]]] = None,
            position: pulumi.Input[Optional[_builtins.float]] = None,
            sla_id: pulumi.Input[Optional[_builtins.str]] = None,
            slug: pulumi.Input[Optional[_builtins.str]] = None) -> 'Sla':
        """
        Get an existing Sla resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.float] assignment_deadline_days: Number of days for the assignment deadline
        :param pulumi.Input[_builtins.str] assignment_deadline_parent_status: The incident parent status that triggers the assignment deadline
        :param pulumi.Input[_builtins.str] assignment_deadline_sub_status_id: Sub-status for the assignment deadline. Required when custom lifecycle statuses are enabled on the team.
        :param pulumi.Input[_builtins.bool] assignment_skip_weekends: Whether to skip weekends when calculating the assignment deadline. Value must be one of true or false
        :param pulumi.Input[_builtins.float] completion_deadline_days: Number of days for the completion deadline
        :param pulumi.Input[_builtins.str] completion_deadline_parent_status: The incident parent status that triggers the completion deadline
        :param pulumi.Input[_builtins.str] completion_deadline_sub_status_id: Sub-status for the completion deadline. Required when custom lifecycle statuses are enabled on the team.
        :param pulumi.Input[_builtins.bool] completion_skip_weekends: Whether to skip weekends when calculating the completion deadline. Value must be one of true or false
        :param pulumi.Input[_builtins.str] condition_match_type: Whether all or any conditions must match. Value must be one of `ALL`, `ANY`.
        :param pulumi.Input[Sequence[pulumi.Input[Union['SlaConditionArgs', 'SlaConditionArgsDict']]]] conditions: Conditions that determine which incidents this SLA applies to
        :param pulumi.Input[_builtins.str] description: A description of the SLA
        :param pulumi.Input[_builtins.str] entity_type: The entity type this SLA applies to. Value must be one of <span pulumi-lang-nodejs="`followUp`" pulumi-lang-dotnet="`FollowUp`" pulumi-lang-go="`followUp`" pulumi-lang-python="`follow_up`" pulumi-lang-yaml="`followUp`" pulumi-lang-java="`followUp`" pulumi-lang-hcl="`follow_up`">`followUp`</span>.
        :param pulumi.Input[_builtins.str] manager_role_id: The ID of the manager incident role. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        :param pulumi.Input[_builtins.float] manager_user_id: The ID of the manager user. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        :param pulumi.Input[_builtins.str] name: The name of the SLA
        :param pulumi.Input[Sequence[pulumi.Input[Union['SlaNotificationConfigurationArgs', 'SlaNotificationConfigurationArgsDict']]]] notification_configurations: Notification timing configurations
        :param pulumi.Input[_builtins.float] position: Position of the SLA for ordering
        :param pulumi.Input[_builtins.str] slug: The slug of the SLA
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SlaState.__new__(_SlaState)

        __props__.__dict__["assignment_deadline_days"] = assignment_deadline_days
        __props__.__dict__["assignment_deadline_parent_status"] = assignment_deadline_parent_status
        __props__.__dict__["assignment_deadline_sub_status_id"] = assignment_deadline_sub_status_id
        __props__.__dict__["assignment_skip_weekends"] = assignment_skip_weekends
        __props__.__dict__["completion_deadline_days"] = completion_deadline_days
        __props__.__dict__["completion_deadline_parent_status"] = completion_deadline_parent_status
        __props__.__dict__["completion_deadline_sub_status_id"] = completion_deadline_sub_status_id
        __props__.__dict__["completion_skip_weekends"] = completion_skip_weekends
        __props__.__dict__["condition_match_type"] = condition_match_type
        __props__.__dict__["conditions"] = conditions
        __props__.__dict__["description"] = description
        __props__.__dict__["entity_type"] = entity_type
        __props__.__dict__["manager_role_id"] = manager_role_id
        __props__.__dict__["manager_user_id"] = manager_user_id
        __props__.__dict__["name"] = name
        __props__.__dict__["notification_configurations"] = notification_configurations
        __props__.__dict__["position"] = position
        __props__.__dict__["sla_id"] = sla_id
        __props__.__dict__["slug"] = slug
        return Sla(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="assignmentDeadlineDays")
    def assignment_deadline_days(self) -> pulumi.Output[_builtins.float]:
        """
        Number of days for the assignment deadline
        """
        return pulumi.get(self, "assignment_deadline_days")

    @_builtins.property
    @pulumi.getter(name="assignmentDeadlineParentStatus")
    def assignment_deadline_parent_status(self) -> pulumi.Output[_builtins.str]:
        """
        The incident parent status that triggers the assignment deadline
        """
        return pulumi.get(self, "assignment_deadline_parent_status")

    @_builtins.property
    @pulumi.getter(name="assignmentDeadlineSubStatusId")
    def assignment_deadline_sub_status_id(self) -> pulumi.Output[_builtins.str]:
        """
        Sub-status for the assignment deadline. Required when custom lifecycle statuses are enabled on the team.
        """
        return pulumi.get(self, "assignment_deadline_sub_status_id")

    @_builtins.property
    @pulumi.getter(name="assignmentSkipWeekends")
    def assignment_skip_weekends(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether to skip weekends when calculating the assignment deadline. Value must be one of true or false
        """
        return pulumi.get(self, "assignment_skip_weekends")

    @_builtins.property
    @pulumi.getter(name="completionDeadlineDays")
    def completion_deadline_days(self) -> pulumi.Output[_builtins.float]:
        """
        Number of days for the completion deadline
        """
        return pulumi.get(self, "completion_deadline_days")

    @_builtins.property
    @pulumi.getter(name="completionDeadlineParentStatus")
    def completion_deadline_parent_status(self) -> pulumi.Output[_builtins.str]:
        """
        The incident parent status that triggers the completion deadline
        """
        return pulumi.get(self, "completion_deadline_parent_status")

    @_builtins.property
    @pulumi.getter(name="completionDeadlineSubStatusId")
    def completion_deadline_sub_status_id(self) -> pulumi.Output[_builtins.str]:
        """
        Sub-status for the completion deadline. Required when custom lifecycle statuses are enabled on the team.
        """
        return pulumi.get(self, "completion_deadline_sub_status_id")

    @_builtins.property
    @pulumi.getter(name="completionSkipWeekends")
    def completion_skip_weekends(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether to skip weekends when calculating the completion deadline. Value must be one of true or false
        """
        return pulumi.get(self, "completion_skip_weekends")

    @_builtins.property
    @pulumi.getter(name="conditionMatchType")
    def condition_match_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Whether all or any conditions must match. Value must be one of `ALL`, `ANY`.
        """
        return pulumi.get(self, "condition_match_type")

    @_builtins.property
    @pulumi.getter
    def conditions(self) -> pulumi.Output[Optional[Sequence['outputs.SlaCondition']]]:
        """
        Conditions that determine which incidents this SLA applies to
        """
        return pulumi.get(self, "conditions")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        A description of the SLA
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="entityType")
    def entity_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The entity type this SLA applies to. Value must be one of <span pulumi-lang-nodejs="`followUp`" pulumi-lang-dotnet="`FollowUp`" pulumi-lang-go="`followUp`" pulumi-lang-python="`follow_up`" pulumi-lang-yaml="`followUp`" pulumi-lang-java="`followUp`" pulumi-lang-hcl="`follow_up`">`followUp`</span>.
        """
        return pulumi.get(self, "entity_type")

    @_builtins.property
    @pulumi.getter(name="managerRoleId")
    def manager_role_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the manager incident role. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        """
        return pulumi.get(self, "manager_role_id")

    @_builtins.property
    @pulumi.getter(name="managerUserId")
    def manager_user_id(self) -> pulumi.Output[_builtins.float]:
        """
        The ID of the manager user. Exactly one of <span pulumi-lang-nodejs="`managerRoleId`" pulumi-lang-dotnet="`ManagerRoleId`" pulumi-lang-go="`managerRoleId`" pulumi-lang-python="`manager_role_id`" pulumi-lang-yaml="`managerRoleId`" pulumi-lang-java="`managerRoleId`" pulumi-lang-hcl="`manager_role_id`">`managerRoleId`</span> or <span pulumi-lang-nodejs="`managerUserId`" pulumi-lang-dotnet="`ManagerUserId`" pulumi-lang-go="`managerUserId`" pulumi-lang-python="`manager_user_id`" pulumi-lang-yaml="`managerUserId`" pulumi-lang-java="`managerUserId`" pulumi-lang-hcl="`manager_user_id`">`managerUserId`</span> must be provided.
        """
        return pulumi.get(self, "manager_user_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the SLA
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="notificationConfigurations")
    def notification_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SlaNotificationConfiguration']]]:
        """
        Notification timing configurations
        """
        return pulumi.get(self, "notification_configurations")

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Output[_builtins.float]:
        """
        Position of the SLA for ordering
        """
        return pulumi.get(self, "position")

    @_builtins.property
    @pulumi.getter(name="slaId")
    def sla_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "sla_id")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Output[_builtins.str]:
        """
        The slug of the SLA
        """
        return pulumi.get(self, "slug")

