# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['StatusPageArgs', 'StatusPage']

@pulumi.input_type
class StatusPageArgs:
    def __init__(__self__, *,
                 title: pulumi.Input[_builtins.str],
                 allow_search_engine_index: pulumi.Input[Optional[_builtins.bool]] = None,
                 authentication_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 authentication_method: pulumi.Input[Optional[_builtins.str]] = None,
                 authentication_password: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 external_domain_names: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 failure_message: pulumi.Input[Optional[_builtins.str]] = None,
                 footer_color: pulumi.Input[Optional[_builtins.str]] = None,
                 functionality_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ga_tracking_id: pulumi.Input[Optional[_builtins.str]] = None,
                 header_color: pulumi.Input[Optional[_builtins.str]] = None,
                 public: pulumi.Input[Optional[_builtins.bool]] = None,
                 public_description: pulumi.Input[Optional[_builtins.str]] = None,
                 public_title: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_cert: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_cert_fingerprint: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_slo_service_url: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_sso_service_url: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_name_identifier_format: pulumi.Input[Optional[_builtins.str]] = None,
                 section_orders: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 service_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 show_uptime: pulumi.Input[Optional[_builtins.bool]] = None,
                 show_uptime_last_days: pulumi.Input[Optional[_builtins.float]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 status_page_id: pulumi.Input[Optional[_builtins.str]] = None,
                 success_message: pulumi.Input[Optional[_builtins.str]] = None,
                 time_zone: pulumi.Input[Optional[_builtins.str]] = None,
                 website_privacy_url: pulumi.Input[Optional[_builtins.str]] = None,
                 website_support_url: pulumi.Input[Optional[_builtins.str]] = None,
                 website_url: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a StatusPage resource.

        :param pulumi.Input[_builtins.str] title: The title of the status page
        :param pulumi.Input[_builtins.bool] allow_search_engine_index: Allow search engines to include your public status page in search results. Value must be one of true or false
        :param pulumi.Input[_builtins.bool] authentication_enabled: Enable authentication (deprecated - use<span pulumi-lang-nodejs=" authenticationMethod " pulumi-lang-dotnet=" AuthenticationMethod " pulumi-lang-go=" authenticationMethod " pulumi-lang-python=" authentication_method " pulumi-lang-yaml=" authenticationMethod " pulumi-lang-java=" authenticationMethod " pulumi-lang-hcl=" authentication_method "> authenticationMethod </span>instead). Value must be one of true or false
        :param pulumi.Input[_builtins.str] authentication_method: Authentication method. Value must be one of <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>, <span pulumi-lang-nodejs="`saml`" pulumi-lang-dotnet="`Saml`" pulumi-lang-go="`saml`" pulumi-lang-python="`saml`" pulumi-lang-yaml="`saml`" pulumi-lang-java="`saml`" pulumi-lang-hcl="`saml`">`saml`</span>.
        :param pulumi.Input[_builtins.str] authentication_password: Authentication password
        :param pulumi.Input[_builtins.str] description: The description of the status page
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] external_domain_names: External domain names attached to the status page
        :param pulumi.Input[_builtins.str] failure_message: Message showing when at least one component is not operational
        :param pulumi.Input[_builtins.str] footer_color: The color of the footer. Eg. "#1F2F41"
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] functionality_ids: Functionalities attached to the status page
        :param pulumi.Input[_builtins.str] ga_tracking_id: Google Analytics tracking ID
        :param pulumi.Input[_builtins.str] header_color: The color of the header. Eg. "#0061F2"
        :param pulumi.Input[_builtins.bool] public: Make the status page accessible to the public. Value must be one of true or false
        :param pulumi.Input[_builtins.str] public_description: The public description of the status page
        :param pulumi.Input[_builtins.str] public_title: The public title of the status page
        :param pulumi.Input[_builtins.str] saml_idp_cert: SAML IdP certificate
        :param pulumi.Input[_builtins.str] saml_idp_cert_fingerprint: SAML IdP certificate fingerprint
        :param pulumi.Input[_builtins.str] saml_idp_slo_service_url: SAML IdP SLO service URL
        :param pulumi.Input[_builtins.str] saml_idp_sso_service_url: SAML IdP SSO service URL
        :param pulumi.Input[_builtins.str] saml_name_identifier_format: SAML name identifier format. Value must be one of `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`, `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`, `urn:oasis:names:tc:SAML:2.0:nameid-format:transient`, `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] section_orders: Order of sections on the status page. Value must be a list of <span pulumi-lang-nodejs="`maintenance`" pulumi-lang-dotnet="`Maintenance`" pulumi-lang-go="`maintenance`" pulumi-lang-python="`maintenance`" pulumi-lang-yaml="`maintenance`" pulumi-lang-java="`maintenance`" pulumi-lang-hcl="`maintenance`">`maintenance`</span>, <span pulumi-lang-nodejs="`systemStatus`" pulumi-lang-dotnet="`SystemStatus`" pulumi-lang-go="`systemStatus`" pulumi-lang-python="`system_status`" pulumi-lang-yaml="`systemStatus`" pulumi-lang-java="`systemStatus`" pulumi-lang-hcl="`system_status`">`systemStatus`</span>, <span pulumi-lang-nodejs="`incidents`" pulumi-lang-dotnet="`Incidents`" pulumi-lang-go="`incidents`" pulumi-lang-python="`incidents`" pulumi-lang-yaml="`incidents`" pulumi-lang-java="`incidents`" pulumi-lang-hcl="`incidents`">`incidents`</span>.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] service_ids: Services attached to the status page
        :param pulumi.Input[_builtins.bool] show_uptime: Show uptime. Value must be one of true or false
        :param pulumi.Input[_builtins.float] show_uptime_last_days: Show uptime over x days. Value must be one of <span pulumi-lang-nodejs="`30`" pulumi-lang-dotnet="`30`" pulumi-lang-go="`30`" pulumi-lang-python="`30`" pulumi-lang-yaml="`30`" pulumi-lang-java="`30`" pulumi-lang-hcl="`30`">`30`</span>, <span pulumi-lang-nodejs="`60`" pulumi-lang-dotnet="`60`" pulumi-lang-go="`60`" pulumi-lang-python="`60`" pulumi-lang-yaml="`60`" pulumi-lang-java="`60`" pulumi-lang-hcl="`60`">`60`</span>, <span pulumi-lang-nodejs="`90`" pulumi-lang-dotnet="`90`" pulumi-lang-go="`90`" pulumi-lang-python="`90`" pulumi-lang-yaml="`90`" pulumi-lang-java="`90`" pulumi-lang-hcl="`90`">`90`</span>.
        :param pulumi.Input[_builtins.str] slug: The slug of the status page
        :param pulumi.Input[_builtins.str] success_message: Message showing when all components are operational
        :param pulumi.Input[_builtins.str] time_zone: A valid IANA time zone name.
        :param pulumi.Input[_builtins.str] website_privacy_url: Website Privacy URL
        :param pulumi.Input[_builtins.str] website_support_url: Website Support URL
        :param pulumi.Input[_builtins.str] website_url: Website URL
        """
        pulumi.set(__self__, "title", title)
        if allow_search_engine_index is not None:
            pulumi.set(__self__, "allow_search_engine_index", allow_search_engine_index)
        if authentication_enabled is not None:
            pulumi.set(__self__, "authentication_enabled", authentication_enabled)
        if authentication_method is not None:
            pulumi.set(__self__, "authentication_method", authentication_method)
        if authentication_password is not None:
            pulumi.set(__self__, "authentication_password", authentication_password)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if external_domain_names is not None:
            pulumi.set(__self__, "external_domain_names", external_domain_names)
        if failure_message is not None:
            pulumi.set(__self__, "failure_message", failure_message)
        if footer_color is not None:
            pulumi.set(__self__, "footer_color", footer_color)
        if functionality_ids is not None:
            pulumi.set(__self__, "functionality_ids", functionality_ids)
        if ga_tracking_id is not None:
            pulumi.set(__self__, "ga_tracking_id", ga_tracking_id)
        if header_color is not None:
            pulumi.set(__self__, "header_color", header_color)
        if public is not None:
            pulumi.set(__self__, "public", public)
        if public_description is not None:
            pulumi.set(__self__, "public_description", public_description)
        if public_title is not None:
            pulumi.set(__self__, "public_title", public_title)
        if saml_idp_cert is not None:
            pulumi.set(__self__, "saml_idp_cert", saml_idp_cert)
        if saml_idp_cert_fingerprint is not None:
            pulumi.set(__self__, "saml_idp_cert_fingerprint", saml_idp_cert_fingerprint)
        if saml_idp_slo_service_url is not None:
            pulumi.set(__self__, "saml_idp_slo_service_url", saml_idp_slo_service_url)
        if saml_idp_sso_service_url is not None:
            pulumi.set(__self__, "saml_idp_sso_service_url", saml_idp_sso_service_url)
        if saml_name_identifier_format is not None:
            pulumi.set(__self__, "saml_name_identifier_format", saml_name_identifier_format)
        if section_orders is not None:
            pulumi.set(__self__, "section_orders", section_orders)
        if service_ids is not None:
            pulumi.set(__self__, "service_ids", service_ids)
        if show_uptime is not None:
            pulumi.set(__self__, "show_uptime", show_uptime)
        if show_uptime_last_days is not None:
            pulumi.set(__self__, "show_uptime_last_days", show_uptime_last_days)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)
        if status_page_id is not None:
            pulumi.set(__self__, "status_page_id", status_page_id)
        if success_message is not None:
            pulumi.set(__self__, "success_message", success_message)
        if time_zone is not None:
            pulumi.set(__self__, "time_zone", time_zone)
        if website_privacy_url is not None:
            pulumi.set(__self__, "website_privacy_url", website_privacy_url)
        if website_support_url is not None:
            pulumi.set(__self__, "website_support_url", website_support_url)
        if website_url is not None:
            pulumi.set(__self__, "website_url", website_url)

    @_builtins.property
    @pulumi.getter
    def title(self) -> pulumi.Input[_builtins.str]:
        """
        The title of the status page
        """
        return pulumi.get(self, "title")

    @title.setter
    def title(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "title", value)

    @_builtins.property
    @pulumi.getter(name="allowSearchEngineIndex")
    def allow_search_engine_index(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Allow search engines to include your public status page in search results. Value must be one of true or false
        """
        return pulumi.get(self, "allow_search_engine_index")

    @allow_search_engine_index.setter
    def allow_search_engine_index(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "allow_search_engine_index", value)

    @_builtins.property
    @pulumi.getter(name="authenticationEnabled")
    def authentication_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable authentication (deprecated - use<span pulumi-lang-nodejs=" authenticationMethod " pulumi-lang-dotnet=" AuthenticationMethod " pulumi-lang-go=" authenticationMethod " pulumi-lang-python=" authentication_method " pulumi-lang-yaml=" authenticationMethod " pulumi-lang-java=" authenticationMethod " pulumi-lang-hcl=" authentication_method "> authenticationMethod </span>instead). Value must be one of true or false
        """
        return pulumi.get(self, "authentication_enabled")

    @authentication_enabled.setter
    def authentication_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "authentication_enabled", value)

    @_builtins.property
    @pulumi.getter(name="authenticationMethod")
    def authentication_method(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Authentication method. Value must be one of <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>, <span pulumi-lang-nodejs="`saml`" pulumi-lang-dotnet="`Saml`" pulumi-lang-go="`saml`" pulumi-lang-python="`saml`" pulumi-lang-yaml="`saml`" pulumi-lang-java="`saml`" pulumi-lang-hcl="`saml`">`saml`</span>.
        """
        return pulumi.get(self, "authentication_method")

    @authentication_method.setter
    def authentication_method(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "authentication_method", value)

    @_builtins.property
    @pulumi.getter(name="authenticationPassword")
    def authentication_password(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Authentication password
        """
        return pulumi.get(self, "authentication_password")

    @authentication_password.setter
    def authentication_password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "authentication_password", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The description of the status page
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="externalDomainNames")
    def external_domain_names(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        External domain names attached to the status page
        """
        return pulumi.get(self, "external_domain_names")

    @external_domain_names.setter
    def external_domain_names(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "external_domain_names", value)

    @_builtins.property
    @pulumi.getter(name="failureMessage")
    def failure_message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Message showing when at least one component is not operational
        """
        return pulumi.get(self, "failure_message")

    @failure_message.setter
    def failure_message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "failure_message", value)

    @_builtins.property
    @pulumi.getter(name="footerColor")
    def footer_color(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The color of the footer. Eg. "#1F2F41"
        """
        return pulumi.get(self, "footer_color")

    @footer_color.setter
    def footer_color(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "footer_color", value)

    @_builtins.property
    @pulumi.getter(name="functionalityIds")
    def functionality_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Functionalities attached to the status page
        """
        return pulumi.get(self, "functionality_ids")

    @functionality_ids.setter
    def functionality_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "functionality_ids", value)

    @_builtins.property
    @pulumi.getter(name="gaTrackingId")
    def ga_tracking_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Google Analytics tracking ID
        """
        return pulumi.get(self, "ga_tracking_id")

    @ga_tracking_id.setter
    def ga_tracking_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ga_tracking_id", value)

    @_builtins.property
    @pulumi.getter(name="headerColor")
    def header_color(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The color of the header. Eg. "#0061F2"
        """
        return pulumi.get(self, "header_color")

    @header_color.setter
    def header_color(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "header_color", value)

    @_builtins.property
    @pulumi.getter
    def public(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Make the status page accessible to the public. Value must be one of true or false
        """
        return pulumi.get(self, "public")

    @public.setter
    def public(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "public", value)

    @_builtins.property
    @pulumi.getter(name="publicDescription")
    def public_description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The public description of the status page
        """
        return pulumi.get(self, "public_description")

    @public_description.setter
    def public_description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "public_description", value)

    @_builtins.property
    @pulumi.getter(name="publicTitle")
    def public_title(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The public title of the status page
        """
        return pulumi.get(self, "public_title")

    @public_title.setter
    def public_title(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "public_title", value)

    @_builtins.property
    @pulumi.getter(name="samlIdpCert")
    def saml_idp_cert(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SAML IdP certificate
        """
        return pulumi.get(self, "saml_idp_cert")

    @saml_idp_cert.setter
    def saml_idp_cert(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "saml_idp_cert", value)

    @_builtins.property
    @pulumi.getter(name="samlIdpCertFingerprint")
    def saml_idp_cert_fingerprint(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SAML IdP certificate fingerprint
        """
        return pulumi.get(self, "saml_idp_cert_fingerprint")

    @saml_idp_cert_fingerprint.setter
    def saml_idp_cert_fingerprint(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "saml_idp_cert_fingerprint", value)

    @_builtins.property
    @pulumi.getter(name="samlIdpSloServiceUrl")
    def saml_idp_slo_service_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SAML IdP SLO service URL
        """
        return pulumi.get(self, "saml_idp_slo_service_url")

    @saml_idp_slo_service_url.setter
    def saml_idp_slo_service_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "saml_idp_slo_service_url", value)

    @_builtins.property
    @pulumi.getter(name="samlIdpSsoServiceUrl")
    def saml_idp_sso_service_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SAML IdP SSO service URL
        """
        return pulumi.get(self, "saml_idp_sso_service_url")

    @saml_idp_sso_service_url.setter
    def saml_idp_sso_service_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "saml_idp_sso_service_url", value)

    @_builtins.property
    @pulumi.getter(name="samlNameIdentifierFormat")
    def saml_name_identifier_format(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SAML name identifier format. Value must be one of `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`, `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`, `urn:oasis:names:tc:SAML:2.0:nameid-format:transient`, `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`.
        """
        return pulumi.get(self, "saml_name_identifier_format")

    @saml_name_identifier_format.setter
    def saml_name_identifier_format(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "saml_name_identifier_format", value)

    @_builtins.property
    @pulumi.getter(name="sectionOrders")
    def section_orders(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Order of sections on the status page. Value must be a list of <span pulumi-lang-nodejs="`maintenance`" pulumi-lang-dotnet="`Maintenance`" pulumi-lang-go="`maintenance`" pulumi-lang-python="`maintenance`" pulumi-lang-yaml="`maintenance`" pulumi-lang-java="`maintenance`" pulumi-lang-hcl="`maintenance`">`maintenance`</span>, <span pulumi-lang-nodejs="`systemStatus`" pulumi-lang-dotnet="`SystemStatus`" pulumi-lang-go="`systemStatus`" pulumi-lang-python="`system_status`" pulumi-lang-yaml="`systemStatus`" pulumi-lang-java="`systemStatus`" pulumi-lang-hcl="`system_status`">`systemStatus`</span>, <span pulumi-lang-nodejs="`incidents`" pulumi-lang-dotnet="`Incidents`" pulumi-lang-go="`incidents`" pulumi-lang-python="`incidents`" pulumi-lang-yaml="`incidents`" pulumi-lang-java="`incidents`" pulumi-lang-hcl="`incidents`">`incidents`</span>.
        """
        return pulumi.get(self, "section_orders")

    @section_orders.setter
    def section_orders(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "section_orders", value)

    @_builtins.property
    @pulumi.getter(name="serviceIds")
    def service_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Services attached to the status page
        """
        return pulumi.get(self, "service_ids")

    @service_ids.setter
    def service_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "service_ids", value)

    @_builtins.property
    @pulumi.getter(name="showUptime")
    def show_uptime(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Show uptime. Value must be one of true or false
        """
        return pulumi.get(self, "show_uptime")

    @show_uptime.setter
    def show_uptime(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "show_uptime", value)

    @_builtins.property
    @pulumi.getter(name="showUptimeLastDays")
    def show_uptime_last_days(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Show uptime over x days. Value must be one of <span pulumi-lang-nodejs="`30`" pulumi-lang-dotnet="`30`" pulumi-lang-go="`30`" pulumi-lang-python="`30`" pulumi-lang-yaml="`30`" pulumi-lang-java="`30`" pulumi-lang-hcl="`30`">`30`</span>, <span pulumi-lang-nodejs="`60`" pulumi-lang-dotnet="`60`" pulumi-lang-go="`60`" pulumi-lang-python="`60`" pulumi-lang-yaml="`60`" pulumi-lang-java="`60`" pulumi-lang-hcl="`60`">`60`</span>, <span pulumi-lang-nodejs="`90`" pulumi-lang-dotnet="`90`" pulumi-lang-go="`90`" pulumi-lang-python="`90`" pulumi-lang-yaml="`90`" pulumi-lang-java="`90`" pulumi-lang-hcl="`90`">`90`</span>.
        """
        return pulumi.get(self, "show_uptime_last_days")

    @show_uptime_last_days.setter
    def show_uptime_last_days(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "show_uptime_last_days", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The slug of the status page
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "slug", value)

    @_builtins.property
    @pulumi.getter(name="statusPageId")
    def status_page_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "status_page_id")

    @status_page_id.setter
    def status_page_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status_page_id", value)

    @_builtins.property
    @pulumi.getter(name="successMessage")
    def success_message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Message showing when all components are operational
        """
        return pulumi.get(self, "success_message")

    @success_message.setter
    def success_message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "success_message", value)

    @_builtins.property
    @pulumi.getter(name="timeZone")
    def time_zone(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A valid IANA time zone name.
        """
        return pulumi.get(self, "time_zone")

    @time_zone.setter
    def time_zone(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "time_zone", value)

    @_builtins.property
    @pulumi.getter(name="websitePrivacyUrl")
    def website_privacy_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Website Privacy URL
        """
        return pulumi.get(self, "website_privacy_url")

    @website_privacy_url.setter
    def website_privacy_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "website_privacy_url", value)

    @_builtins.property
    @pulumi.getter(name="websiteSupportUrl")
    def website_support_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Website Support URL
        """
        return pulumi.get(self, "website_support_url")

    @website_support_url.setter
    def website_support_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "website_support_url", value)

    @_builtins.property
    @pulumi.getter(name="websiteUrl")
    def website_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Website URL
        """
        return pulumi.get(self, "website_url")

    @website_url.setter
    def website_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "website_url", value)


@pulumi.input_type
class _StatusPageState:
    def __init__(__self__, *,
                 allow_search_engine_index: pulumi.Input[Optional[_builtins.bool]] = None,
                 authentication_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 authentication_method: pulumi.Input[Optional[_builtins.str]] = None,
                 authentication_password: pulumi.Input[Optional[_builtins.str]] = None,
                 cname_records: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 external_domain_names: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 failure_message: pulumi.Input[Optional[_builtins.str]] = None,
                 footer_color: pulumi.Input[Optional[_builtins.str]] = None,
                 functionality_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ga_tracking_id: pulumi.Input[Optional[_builtins.str]] = None,
                 header_color: pulumi.Input[Optional[_builtins.str]] = None,
                 public: pulumi.Input[Optional[_builtins.bool]] = None,
                 public_description: pulumi.Input[Optional[_builtins.str]] = None,
                 public_title: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_cert: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_cert_fingerprint: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_slo_service_url: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_sso_service_url: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_name_identifier_format: pulumi.Input[Optional[_builtins.str]] = None,
                 section_orders: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 service_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 show_uptime: pulumi.Input[Optional[_builtins.bool]] = None,
                 show_uptime_last_days: pulumi.Input[Optional[_builtins.float]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 status_page_id: pulumi.Input[Optional[_builtins.str]] = None,
                 success_message: pulumi.Input[Optional[_builtins.str]] = None,
                 time_zone: pulumi.Input[Optional[_builtins.str]] = None,
                 title: pulumi.Input[Optional[_builtins.str]] = None,
                 website_privacy_url: pulumi.Input[Optional[_builtins.str]] = None,
                 website_support_url: pulumi.Input[Optional[_builtins.str]] = None,
                 website_url: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering StatusPage resources.

        :param pulumi.Input[_builtins.bool] allow_search_engine_index: Allow search engines to include your public status page in search results. Value must be one of true or false
        :param pulumi.Input[_builtins.bool] authentication_enabled: Enable authentication (deprecated - use<span pulumi-lang-nodejs=" authenticationMethod " pulumi-lang-dotnet=" AuthenticationMethod " pulumi-lang-go=" authenticationMethod " pulumi-lang-python=" authentication_method " pulumi-lang-yaml=" authenticationMethod " pulumi-lang-java=" authenticationMethod " pulumi-lang-hcl=" authentication_method "> authenticationMethod </span>instead). Value must be one of true or false
        :param pulumi.Input[_builtins.str] authentication_method: Authentication method. Value must be one of <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>, <span pulumi-lang-nodejs="`saml`" pulumi-lang-dotnet="`Saml`" pulumi-lang-go="`saml`" pulumi-lang-python="`saml`" pulumi-lang-yaml="`saml`" pulumi-lang-java="`saml`" pulumi-lang-hcl="`saml`">`saml`</span>.
        :param pulumi.Input[_builtins.str] authentication_password: Authentication password
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] cname_records: CNAME records mapping external domain names to their DNS target values. Populated asynchronously after setting external_domain_names.
        :param pulumi.Input[_builtins.str] description: The description of the status page
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] external_domain_names: External domain names attached to the status page
        :param pulumi.Input[_builtins.str] failure_message: Message showing when at least one component is not operational
        :param pulumi.Input[_builtins.str] footer_color: The color of the footer. Eg. "#1F2F41"
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] functionality_ids: Functionalities attached to the status page
        :param pulumi.Input[_builtins.str] ga_tracking_id: Google Analytics tracking ID
        :param pulumi.Input[_builtins.str] header_color: The color of the header. Eg. "#0061F2"
        :param pulumi.Input[_builtins.bool] public: Make the status page accessible to the public. Value must be one of true or false
        :param pulumi.Input[_builtins.str] public_description: The public description of the status page
        :param pulumi.Input[_builtins.str] public_title: The public title of the status page
        :param pulumi.Input[_builtins.str] saml_idp_cert: SAML IdP certificate
        :param pulumi.Input[_builtins.str] saml_idp_cert_fingerprint: SAML IdP certificate fingerprint
        :param pulumi.Input[_builtins.str] saml_idp_slo_service_url: SAML IdP SLO service URL
        :param pulumi.Input[_builtins.str] saml_idp_sso_service_url: SAML IdP SSO service URL
        :param pulumi.Input[_builtins.str] saml_name_identifier_format: SAML name identifier format. Value must be one of `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`, `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`, `urn:oasis:names:tc:SAML:2.0:nameid-format:transient`, `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] section_orders: Order of sections on the status page. Value must be a list of <span pulumi-lang-nodejs="`maintenance`" pulumi-lang-dotnet="`Maintenance`" pulumi-lang-go="`maintenance`" pulumi-lang-python="`maintenance`" pulumi-lang-yaml="`maintenance`" pulumi-lang-java="`maintenance`" pulumi-lang-hcl="`maintenance`">`maintenance`</span>, <span pulumi-lang-nodejs="`systemStatus`" pulumi-lang-dotnet="`SystemStatus`" pulumi-lang-go="`systemStatus`" pulumi-lang-python="`system_status`" pulumi-lang-yaml="`systemStatus`" pulumi-lang-java="`systemStatus`" pulumi-lang-hcl="`system_status`">`systemStatus`</span>, <span pulumi-lang-nodejs="`incidents`" pulumi-lang-dotnet="`Incidents`" pulumi-lang-go="`incidents`" pulumi-lang-python="`incidents`" pulumi-lang-yaml="`incidents`" pulumi-lang-java="`incidents`" pulumi-lang-hcl="`incidents`">`incidents`</span>.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] service_ids: Services attached to the status page
        :param pulumi.Input[_builtins.bool] show_uptime: Show uptime. Value must be one of true or false
        :param pulumi.Input[_builtins.float] show_uptime_last_days: Show uptime over x days. Value must be one of <span pulumi-lang-nodejs="`30`" pulumi-lang-dotnet="`30`" pulumi-lang-go="`30`" pulumi-lang-python="`30`" pulumi-lang-yaml="`30`" pulumi-lang-java="`30`" pulumi-lang-hcl="`30`">`30`</span>, <span pulumi-lang-nodejs="`60`" pulumi-lang-dotnet="`60`" pulumi-lang-go="`60`" pulumi-lang-python="`60`" pulumi-lang-yaml="`60`" pulumi-lang-java="`60`" pulumi-lang-hcl="`60`">`60`</span>, <span pulumi-lang-nodejs="`90`" pulumi-lang-dotnet="`90`" pulumi-lang-go="`90`" pulumi-lang-python="`90`" pulumi-lang-yaml="`90`" pulumi-lang-java="`90`" pulumi-lang-hcl="`90`">`90`</span>.
        :param pulumi.Input[_builtins.str] slug: The slug of the status page
        :param pulumi.Input[_builtins.str] success_message: Message showing when all components are operational
        :param pulumi.Input[_builtins.str] time_zone: A valid IANA time zone name.
        :param pulumi.Input[_builtins.str] title: The title of the status page
        :param pulumi.Input[_builtins.str] website_privacy_url: Website Privacy URL
        :param pulumi.Input[_builtins.str] website_support_url: Website Support URL
        :param pulumi.Input[_builtins.str] website_url: Website URL
        """
        if allow_search_engine_index is not None:
            pulumi.set(__self__, "allow_search_engine_index", allow_search_engine_index)
        if authentication_enabled is not None:
            pulumi.set(__self__, "authentication_enabled", authentication_enabled)
        if authentication_method is not None:
            pulumi.set(__self__, "authentication_method", authentication_method)
        if authentication_password is not None:
            pulumi.set(__self__, "authentication_password", authentication_password)
        if cname_records is not None:
            pulumi.set(__self__, "cname_records", cname_records)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if external_domain_names is not None:
            pulumi.set(__self__, "external_domain_names", external_domain_names)
        if failure_message is not None:
            pulumi.set(__self__, "failure_message", failure_message)
        if footer_color is not None:
            pulumi.set(__self__, "footer_color", footer_color)
        if functionality_ids is not None:
            pulumi.set(__self__, "functionality_ids", functionality_ids)
        if ga_tracking_id is not None:
            pulumi.set(__self__, "ga_tracking_id", ga_tracking_id)
        if header_color is not None:
            pulumi.set(__self__, "header_color", header_color)
        if public is not None:
            pulumi.set(__self__, "public", public)
        if public_description is not None:
            pulumi.set(__self__, "public_description", public_description)
        if public_title is not None:
            pulumi.set(__self__, "public_title", public_title)
        if saml_idp_cert is not None:
            pulumi.set(__self__, "saml_idp_cert", saml_idp_cert)
        if saml_idp_cert_fingerprint is not None:
            pulumi.set(__self__, "saml_idp_cert_fingerprint", saml_idp_cert_fingerprint)
        if saml_idp_slo_service_url is not None:
            pulumi.set(__self__, "saml_idp_slo_service_url", saml_idp_slo_service_url)
        if saml_idp_sso_service_url is not None:
            pulumi.set(__self__, "saml_idp_sso_service_url", saml_idp_sso_service_url)
        if saml_name_identifier_format is not None:
            pulumi.set(__self__, "saml_name_identifier_format", saml_name_identifier_format)
        if section_orders is not None:
            pulumi.set(__self__, "section_orders", section_orders)
        if service_ids is not None:
            pulumi.set(__self__, "service_ids", service_ids)
        if show_uptime is not None:
            pulumi.set(__self__, "show_uptime", show_uptime)
        if show_uptime_last_days is not None:
            pulumi.set(__self__, "show_uptime_last_days", show_uptime_last_days)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)
        if status_page_id is not None:
            pulumi.set(__self__, "status_page_id", status_page_id)
        if success_message is not None:
            pulumi.set(__self__, "success_message", success_message)
        if time_zone is not None:
            pulumi.set(__self__, "time_zone", time_zone)
        if title is not None:
            pulumi.set(__self__, "title", title)
        if website_privacy_url is not None:
            pulumi.set(__self__, "website_privacy_url", website_privacy_url)
        if website_support_url is not None:
            pulumi.set(__self__, "website_support_url", website_support_url)
        if website_url is not None:
            pulumi.set(__self__, "website_url", website_url)

    @_builtins.property
    @pulumi.getter(name="allowSearchEngineIndex")
    def allow_search_engine_index(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Allow search engines to include your public status page in search results. Value must be one of true or false
        """
        return pulumi.get(self, "allow_search_engine_index")

    @allow_search_engine_index.setter
    def allow_search_engine_index(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "allow_search_engine_index", value)

    @_builtins.property
    @pulumi.getter(name="authenticationEnabled")
    def authentication_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable authentication (deprecated - use<span pulumi-lang-nodejs=" authenticationMethod " pulumi-lang-dotnet=" AuthenticationMethod " pulumi-lang-go=" authenticationMethod " pulumi-lang-python=" authentication_method " pulumi-lang-yaml=" authenticationMethod " pulumi-lang-java=" authenticationMethod " pulumi-lang-hcl=" authentication_method "> authenticationMethod </span>instead). Value must be one of true or false
        """
        return pulumi.get(self, "authentication_enabled")

    @authentication_enabled.setter
    def authentication_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "authentication_enabled", value)

    @_builtins.property
    @pulumi.getter(name="authenticationMethod")
    def authentication_method(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Authentication method. Value must be one of <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>, <span pulumi-lang-nodejs="`saml`" pulumi-lang-dotnet="`Saml`" pulumi-lang-go="`saml`" pulumi-lang-python="`saml`" pulumi-lang-yaml="`saml`" pulumi-lang-java="`saml`" pulumi-lang-hcl="`saml`">`saml`</span>.
        """
        return pulumi.get(self, "authentication_method")

    @authentication_method.setter
    def authentication_method(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "authentication_method", value)

    @_builtins.property
    @pulumi.getter(name="authenticationPassword")
    def authentication_password(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Authentication password
        """
        return pulumi.get(self, "authentication_password")

    @authentication_password.setter
    def authentication_password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "authentication_password", value)

    @_builtins.property
    @pulumi.getter(name="cnameRecords")
    def cname_records(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        CNAME records mapping external domain names to their DNS target values. Populated asynchronously after setting external_domain_names.
        """
        return pulumi.get(self, "cname_records")

    @cname_records.setter
    def cname_records(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "cname_records", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The description of the status page
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="externalDomainNames")
    def external_domain_names(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        External domain names attached to the status page
        """
        return pulumi.get(self, "external_domain_names")

    @external_domain_names.setter
    def external_domain_names(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "external_domain_names", value)

    @_builtins.property
    @pulumi.getter(name="failureMessage")
    def failure_message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Message showing when at least one component is not operational
        """
        return pulumi.get(self, "failure_message")

    @failure_message.setter
    def failure_message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "failure_message", value)

    @_builtins.property
    @pulumi.getter(name="footerColor")
    def footer_color(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The color of the footer. Eg. "#1F2F41"
        """
        return pulumi.get(self, "footer_color")

    @footer_color.setter
    def footer_color(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "footer_color", value)

    @_builtins.property
    @pulumi.getter(name="functionalityIds")
    def functionality_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Functionalities attached to the status page
        """
        return pulumi.get(self, "functionality_ids")

    @functionality_ids.setter
    def functionality_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "functionality_ids", value)

    @_builtins.property
    @pulumi.getter(name="gaTrackingId")
    def ga_tracking_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Google Analytics tracking ID
        """
        return pulumi.get(self, "ga_tracking_id")

    @ga_tracking_id.setter
    def ga_tracking_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ga_tracking_id", value)

    @_builtins.property
    @pulumi.getter(name="headerColor")
    def header_color(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The color of the header. Eg. "#0061F2"
        """
        return pulumi.get(self, "header_color")

    @header_color.setter
    def header_color(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "header_color", value)

    @_builtins.property
    @pulumi.getter
    def public(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Make the status page accessible to the public. Value must be one of true or false
        """
        return pulumi.get(self, "public")

    @public.setter
    def public(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "public", value)

    @_builtins.property
    @pulumi.getter(name="publicDescription")
    def public_description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The public description of the status page
        """
        return pulumi.get(self, "public_description")

    @public_description.setter
    def public_description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "public_description", value)

    @_builtins.property
    @pulumi.getter(name="publicTitle")
    def public_title(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The public title of the status page
        """
        return pulumi.get(self, "public_title")

    @public_title.setter
    def public_title(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "public_title", value)

    @_builtins.property
    @pulumi.getter(name="samlIdpCert")
    def saml_idp_cert(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SAML IdP certificate
        """
        return pulumi.get(self, "saml_idp_cert")

    @saml_idp_cert.setter
    def saml_idp_cert(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "saml_idp_cert", value)

    @_builtins.property
    @pulumi.getter(name="samlIdpCertFingerprint")
    def saml_idp_cert_fingerprint(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SAML IdP certificate fingerprint
        """
        return pulumi.get(self, "saml_idp_cert_fingerprint")

    @saml_idp_cert_fingerprint.setter
    def saml_idp_cert_fingerprint(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "saml_idp_cert_fingerprint", value)

    @_builtins.property
    @pulumi.getter(name="samlIdpSloServiceUrl")
    def saml_idp_slo_service_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SAML IdP SLO service URL
        """
        return pulumi.get(self, "saml_idp_slo_service_url")

    @saml_idp_slo_service_url.setter
    def saml_idp_slo_service_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "saml_idp_slo_service_url", value)

    @_builtins.property
    @pulumi.getter(name="samlIdpSsoServiceUrl")
    def saml_idp_sso_service_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SAML IdP SSO service URL
        """
        return pulumi.get(self, "saml_idp_sso_service_url")

    @saml_idp_sso_service_url.setter
    def saml_idp_sso_service_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "saml_idp_sso_service_url", value)

    @_builtins.property
    @pulumi.getter(name="samlNameIdentifierFormat")
    def saml_name_identifier_format(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SAML name identifier format. Value must be one of `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`, `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`, `urn:oasis:names:tc:SAML:2.0:nameid-format:transient`, `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`.
        """
        return pulumi.get(self, "saml_name_identifier_format")

    @saml_name_identifier_format.setter
    def saml_name_identifier_format(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "saml_name_identifier_format", value)

    @_builtins.property
    @pulumi.getter(name="sectionOrders")
    def section_orders(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Order of sections on the status page. Value must be a list of <span pulumi-lang-nodejs="`maintenance`" pulumi-lang-dotnet="`Maintenance`" pulumi-lang-go="`maintenance`" pulumi-lang-python="`maintenance`" pulumi-lang-yaml="`maintenance`" pulumi-lang-java="`maintenance`" pulumi-lang-hcl="`maintenance`">`maintenance`</span>, <span pulumi-lang-nodejs="`systemStatus`" pulumi-lang-dotnet="`SystemStatus`" pulumi-lang-go="`systemStatus`" pulumi-lang-python="`system_status`" pulumi-lang-yaml="`systemStatus`" pulumi-lang-java="`systemStatus`" pulumi-lang-hcl="`system_status`">`systemStatus`</span>, <span pulumi-lang-nodejs="`incidents`" pulumi-lang-dotnet="`Incidents`" pulumi-lang-go="`incidents`" pulumi-lang-python="`incidents`" pulumi-lang-yaml="`incidents`" pulumi-lang-java="`incidents`" pulumi-lang-hcl="`incidents`">`incidents`</span>.
        """
        return pulumi.get(self, "section_orders")

    @section_orders.setter
    def section_orders(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "section_orders", value)

    @_builtins.property
    @pulumi.getter(name="serviceIds")
    def service_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Services attached to the status page
        """
        return pulumi.get(self, "service_ids")

    @service_ids.setter
    def service_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "service_ids", value)

    @_builtins.property
    @pulumi.getter(name="showUptime")
    def show_uptime(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Show uptime. Value must be one of true or false
        """
        return pulumi.get(self, "show_uptime")

    @show_uptime.setter
    def show_uptime(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "show_uptime", value)

    @_builtins.property
    @pulumi.getter(name="showUptimeLastDays")
    def show_uptime_last_days(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Show uptime over x days. Value must be one of <span pulumi-lang-nodejs="`30`" pulumi-lang-dotnet="`30`" pulumi-lang-go="`30`" pulumi-lang-python="`30`" pulumi-lang-yaml="`30`" pulumi-lang-java="`30`" pulumi-lang-hcl="`30`">`30`</span>, <span pulumi-lang-nodejs="`60`" pulumi-lang-dotnet="`60`" pulumi-lang-go="`60`" pulumi-lang-python="`60`" pulumi-lang-yaml="`60`" pulumi-lang-java="`60`" pulumi-lang-hcl="`60`">`60`</span>, <span pulumi-lang-nodejs="`90`" pulumi-lang-dotnet="`90`" pulumi-lang-go="`90`" pulumi-lang-python="`90`" pulumi-lang-yaml="`90`" pulumi-lang-java="`90`" pulumi-lang-hcl="`90`">`90`</span>.
        """
        return pulumi.get(self, "show_uptime_last_days")

    @show_uptime_last_days.setter
    def show_uptime_last_days(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "show_uptime_last_days", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The slug of the status page
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "slug", value)

    @_builtins.property
    @pulumi.getter(name="statusPageId")
    def status_page_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "status_page_id")

    @status_page_id.setter
    def status_page_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status_page_id", value)

    @_builtins.property
    @pulumi.getter(name="successMessage")
    def success_message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Message showing when all components are operational
        """
        return pulumi.get(self, "success_message")

    @success_message.setter
    def success_message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "success_message", value)

    @_builtins.property
    @pulumi.getter(name="timeZone")
    def time_zone(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A valid IANA time zone name.
        """
        return pulumi.get(self, "time_zone")

    @time_zone.setter
    def time_zone(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "time_zone", value)

    @_builtins.property
    @pulumi.getter
    def title(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The title of the status page
        """
        return pulumi.get(self, "title")

    @title.setter
    def title(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "title", value)

    @_builtins.property
    @pulumi.getter(name="websitePrivacyUrl")
    def website_privacy_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Website Privacy URL
        """
        return pulumi.get(self, "website_privacy_url")

    @website_privacy_url.setter
    def website_privacy_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "website_privacy_url", value)

    @_builtins.property
    @pulumi.getter(name="websiteSupportUrl")
    def website_support_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Website Support URL
        """
        return pulumi.get(self, "website_support_url")

    @website_support_url.setter
    def website_support_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "website_support_url", value)

    @_builtins.property
    @pulumi.getter(name="websiteUrl")
    def website_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Website URL
        """
        return pulumi.get(self, "website_url")

    @website_url.setter
    def website_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "website_url", value)


@pulumi.type_token("rootly:index/statusPage:StatusPage")
class StatusPage(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_search_engine_index: pulumi.Input[Optional[_builtins.bool]] = None,
                 authentication_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 authentication_method: pulumi.Input[Optional[_builtins.str]] = None,
                 authentication_password: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 external_domain_names: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 failure_message: pulumi.Input[Optional[_builtins.str]] = None,
                 footer_color: pulumi.Input[Optional[_builtins.str]] = None,
                 functionality_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ga_tracking_id: pulumi.Input[Optional[_builtins.str]] = None,
                 header_color: pulumi.Input[Optional[_builtins.str]] = None,
                 public: pulumi.Input[Optional[_builtins.bool]] = None,
                 public_description: pulumi.Input[Optional[_builtins.str]] = None,
                 public_title: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_cert: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_cert_fingerprint: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_slo_service_url: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_sso_service_url: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_name_identifier_format: pulumi.Input[Optional[_builtins.str]] = None,
                 section_orders: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 service_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 show_uptime: pulumi.Input[Optional[_builtins.bool]] = None,
                 show_uptime_last_days: pulumi.Input[Optional[_builtins.float]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 status_page_id: pulumi.Input[Optional[_builtins.str]] = None,
                 success_message: pulumi.Input[Optional[_builtins.str]] = None,
                 time_zone: pulumi.Input[Optional[_builtins.str]] = None,
                 title: pulumi.Input[Optional[_builtins.str]] = None,
                 website_privacy_url: pulumi.Input[Optional[_builtins.str]] = None,
                 website_support_url: pulumi.Input[Optional[_builtins.str]] = None,
                 website_url: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a StatusPage resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_search_engine_index: Allow search engines to include your public status page in search results. Value must be one of true or false
        :param pulumi.Input[_builtins.bool] authentication_enabled: Enable authentication (deprecated - use<span pulumi-lang-nodejs=" authenticationMethod " pulumi-lang-dotnet=" AuthenticationMethod " pulumi-lang-go=" authenticationMethod " pulumi-lang-python=" authentication_method " pulumi-lang-yaml=" authenticationMethod " pulumi-lang-java=" authenticationMethod " pulumi-lang-hcl=" authentication_method "> authenticationMethod </span>instead). Value must be one of true or false
        :param pulumi.Input[_builtins.str] authentication_method: Authentication method. Value must be one of <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>, <span pulumi-lang-nodejs="`saml`" pulumi-lang-dotnet="`Saml`" pulumi-lang-go="`saml`" pulumi-lang-python="`saml`" pulumi-lang-yaml="`saml`" pulumi-lang-java="`saml`" pulumi-lang-hcl="`saml`">`saml`</span>.
        :param pulumi.Input[_builtins.str] authentication_password: Authentication password
        :param pulumi.Input[_builtins.str] description: The description of the status page
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] external_domain_names: External domain names attached to the status page
        :param pulumi.Input[_builtins.str] failure_message: Message showing when at least one component is not operational
        :param pulumi.Input[_builtins.str] footer_color: The color of the footer. Eg. "#1F2F41"
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] functionality_ids: Functionalities attached to the status page
        :param pulumi.Input[_builtins.str] ga_tracking_id: Google Analytics tracking ID
        :param pulumi.Input[_builtins.str] header_color: The color of the header. Eg. "#0061F2"
        :param pulumi.Input[_builtins.bool] public: Make the status page accessible to the public. Value must be one of true or false
        :param pulumi.Input[_builtins.str] public_description: The public description of the status page
        :param pulumi.Input[_builtins.str] public_title: The public title of the status page
        :param pulumi.Input[_builtins.str] saml_idp_cert: SAML IdP certificate
        :param pulumi.Input[_builtins.str] saml_idp_cert_fingerprint: SAML IdP certificate fingerprint
        :param pulumi.Input[_builtins.str] saml_idp_slo_service_url: SAML IdP SLO service URL
        :param pulumi.Input[_builtins.str] saml_idp_sso_service_url: SAML IdP SSO service URL
        :param pulumi.Input[_builtins.str] saml_name_identifier_format: SAML name identifier format. Value must be one of `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`, `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`, `urn:oasis:names:tc:SAML:2.0:nameid-format:transient`, `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] section_orders: Order of sections on the status page. Value must be a list of <span pulumi-lang-nodejs="`maintenance`" pulumi-lang-dotnet="`Maintenance`" pulumi-lang-go="`maintenance`" pulumi-lang-python="`maintenance`" pulumi-lang-yaml="`maintenance`" pulumi-lang-java="`maintenance`" pulumi-lang-hcl="`maintenance`">`maintenance`</span>, <span pulumi-lang-nodejs="`systemStatus`" pulumi-lang-dotnet="`SystemStatus`" pulumi-lang-go="`systemStatus`" pulumi-lang-python="`system_status`" pulumi-lang-yaml="`systemStatus`" pulumi-lang-java="`systemStatus`" pulumi-lang-hcl="`system_status`">`systemStatus`</span>, <span pulumi-lang-nodejs="`incidents`" pulumi-lang-dotnet="`Incidents`" pulumi-lang-go="`incidents`" pulumi-lang-python="`incidents`" pulumi-lang-yaml="`incidents`" pulumi-lang-java="`incidents`" pulumi-lang-hcl="`incidents`">`incidents`</span>.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] service_ids: Services attached to the status page
        :param pulumi.Input[_builtins.bool] show_uptime: Show uptime. Value must be one of true or false
        :param pulumi.Input[_builtins.float] show_uptime_last_days: Show uptime over x days. Value must be one of <span pulumi-lang-nodejs="`30`" pulumi-lang-dotnet="`30`" pulumi-lang-go="`30`" pulumi-lang-python="`30`" pulumi-lang-yaml="`30`" pulumi-lang-java="`30`" pulumi-lang-hcl="`30`">`30`</span>, <span pulumi-lang-nodejs="`60`" pulumi-lang-dotnet="`60`" pulumi-lang-go="`60`" pulumi-lang-python="`60`" pulumi-lang-yaml="`60`" pulumi-lang-java="`60`" pulumi-lang-hcl="`60`">`60`</span>, <span pulumi-lang-nodejs="`90`" pulumi-lang-dotnet="`90`" pulumi-lang-go="`90`" pulumi-lang-python="`90`" pulumi-lang-yaml="`90`" pulumi-lang-java="`90`" pulumi-lang-hcl="`90`">`90`</span>.
        :param pulumi.Input[_builtins.str] slug: The slug of the status page
        :param pulumi.Input[_builtins.str] success_message: Message showing when all components are operational
        :param pulumi.Input[_builtins.str] time_zone: A valid IANA time zone name.
        :param pulumi.Input[_builtins.str] title: The title of the status page
        :param pulumi.Input[_builtins.str] website_privacy_url: Website Privacy URL
        :param pulumi.Input[_builtins.str] website_support_url: Website Support URL
        :param pulumi.Input[_builtins.str] website_url: Website URL
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: StatusPageArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a StatusPage resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param StatusPageArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(StatusPageArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_search_engine_index: pulumi.Input[Optional[_builtins.bool]] = None,
                 authentication_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 authentication_method: pulumi.Input[Optional[_builtins.str]] = None,
                 authentication_password: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 external_domain_names: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 failure_message: pulumi.Input[Optional[_builtins.str]] = None,
                 footer_color: pulumi.Input[Optional[_builtins.str]] = None,
                 functionality_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ga_tracking_id: pulumi.Input[Optional[_builtins.str]] = None,
                 header_color: pulumi.Input[Optional[_builtins.str]] = None,
                 public: pulumi.Input[Optional[_builtins.bool]] = None,
                 public_description: pulumi.Input[Optional[_builtins.str]] = None,
                 public_title: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_cert: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_cert_fingerprint: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_slo_service_url: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_idp_sso_service_url: pulumi.Input[Optional[_builtins.str]] = None,
                 saml_name_identifier_format: pulumi.Input[Optional[_builtins.str]] = None,
                 section_orders: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 service_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 show_uptime: pulumi.Input[Optional[_builtins.bool]] = None,
                 show_uptime_last_days: pulumi.Input[Optional[_builtins.float]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 status_page_id: pulumi.Input[Optional[_builtins.str]] = None,
                 success_message: pulumi.Input[Optional[_builtins.str]] = None,
                 time_zone: pulumi.Input[Optional[_builtins.str]] = None,
                 title: pulumi.Input[Optional[_builtins.str]] = None,
                 website_privacy_url: pulumi.Input[Optional[_builtins.str]] = None,
                 website_support_url: pulumi.Input[Optional[_builtins.str]] = None,
                 website_url: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = StatusPageArgs.__new__(StatusPageArgs)

            __props__.__dict__["allow_search_engine_index"] = allow_search_engine_index
            __props__.__dict__["authentication_enabled"] = authentication_enabled
            __props__.__dict__["authentication_method"] = authentication_method
            __props__.__dict__["authentication_password"] = authentication_password
            __props__.__dict__["description"] = description
            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["external_domain_names"] = external_domain_names
            __props__.__dict__["failure_message"] = failure_message
            __props__.__dict__["footer_color"] = footer_color
            __props__.__dict__["functionality_ids"] = functionality_ids
            __props__.__dict__["ga_tracking_id"] = ga_tracking_id
            __props__.__dict__["header_color"] = header_color
            __props__.__dict__["public"] = public
            __props__.__dict__["public_description"] = public_description
            __props__.__dict__["public_title"] = public_title
            __props__.__dict__["saml_idp_cert"] = saml_idp_cert
            __props__.__dict__["saml_idp_cert_fingerprint"] = saml_idp_cert_fingerprint
            __props__.__dict__["saml_idp_slo_service_url"] = saml_idp_slo_service_url
            __props__.__dict__["saml_idp_sso_service_url"] = saml_idp_sso_service_url
            __props__.__dict__["saml_name_identifier_format"] = saml_name_identifier_format
            __props__.__dict__["section_orders"] = section_orders
            __props__.__dict__["service_ids"] = service_ids
            __props__.__dict__["show_uptime"] = show_uptime
            __props__.__dict__["show_uptime_last_days"] = show_uptime_last_days
            __props__.__dict__["slug"] = slug
            __props__.__dict__["status_page_id"] = status_page_id
            __props__.__dict__["success_message"] = success_message
            __props__.__dict__["time_zone"] = time_zone
            if title is None and not opts.urn:
                raise TypeError("Missing required property 'title'")
            __props__.__dict__["title"] = title
            __props__.__dict__["website_privacy_url"] = website_privacy_url
            __props__.__dict__["website_support_url"] = website_support_url
            __props__.__dict__["website_url"] = website_url
            __props__.__dict__["cname_records"] = None
        super(StatusPage, __self__).__init__(
            'rootly:index/statusPage:StatusPage',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            allow_search_engine_index: pulumi.Input[Optional[_builtins.bool]] = None,
            authentication_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            authentication_method: pulumi.Input[Optional[_builtins.str]] = None,
            authentication_password: pulumi.Input[Optional[_builtins.str]] = None,
            cname_records: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            external_domain_names: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            failure_message: pulumi.Input[Optional[_builtins.str]] = None,
            footer_color: pulumi.Input[Optional[_builtins.str]] = None,
            functionality_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            ga_tracking_id: pulumi.Input[Optional[_builtins.str]] = None,
            header_color: pulumi.Input[Optional[_builtins.str]] = None,
            public: pulumi.Input[Optional[_builtins.bool]] = None,
            public_description: pulumi.Input[Optional[_builtins.str]] = None,
            public_title: pulumi.Input[Optional[_builtins.str]] = None,
            saml_idp_cert: pulumi.Input[Optional[_builtins.str]] = None,
            saml_idp_cert_fingerprint: pulumi.Input[Optional[_builtins.str]] = None,
            saml_idp_slo_service_url: pulumi.Input[Optional[_builtins.str]] = None,
            saml_idp_sso_service_url: pulumi.Input[Optional[_builtins.str]] = None,
            saml_name_identifier_format: pulumi.Input[Optional[_builtins.str]] = None,
            section_orders: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            service_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            show_uptime: pulumi.Input[Optional[_builtins.bool]] = None,
            show_uptime_last_days: pulumi.Input[Optional[_builtins.float]] = None,
            slug: pulumi.Input[Optional[_builtins.str]] = None,
            status_page_id: pulumi.Input[Optional[_builtins.str]] = None,
            success_message: pulumi.Input[Optional[_builtins.str]] = None,
            time_zone: pulumi.Input[Optional[_builtins.str]] = None,
            title: pulumi.Input[Optional[_builtins.str]] = None,
            website_privacy_url: pulumi.Input[Optional[_builtins.str]] = None,
            website_support_url: pulumi.Input[Optional[_builtins.str]] = None,
            website_url: pulumi.Input[Optional[_builtins.str]] = None) -> 'StatusPage':
        """
        Get an existing StatusPage resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_search_engine_index: Allow search engines to include your public status page in search results. Value must be one of true or false
        :param pulumi.Input[_builtins.bool] authentication_enabled: Enable authentication (deprecated - use<span pulumi-lang-nodejs=" authenticationMethod " pulumi-lang-dotnet=" AuthenticationMethod " pulumi-lang-go=" authenticationMethod " pulumi-lang-python=" authentication_method " pulumi-lang-yaml=" authenticationMethod " pulumi-lang-java=" authenticationMethod " pulumi-lang-hcl=" authentication_method "> authenticationMethod </span>instead). Value must be one of true or false
        :param pulumi.Input[_builtins.str] authentication_method: Authentication method. Value must be one of <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>, <span pulumi-lang-nodejs="`saml`" pulumi-lang-dotnet="`Saml`" pulumi-lang-go="`saml`" pulumi-lang-python="`saml`" pulumi-lang-yaml="`saml`" pulumi-lang-java="`saml`" pulumi-lang-hcl="`saml`">`saml`</span>.
        :param pulumi.Input[_builtins.str] authentication_password: Authentication password
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] cname_records: CNAME records mapping external domain names to their DNS target values. Populated asynchronously after setting external_domain_names.
        :param pulumi.Input[_builtins.str] description: The description of the status page
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] external_domain_names: External domain names attached to the status page
        :param pulumi.Input[_builtins.str] failure_message: Message showing when at least one component is not operational
        :param pulumi.Input[_builtins.str] footer_color: The color of the footer. Eg. "#1F2F41"
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] functionality_ids: Functionalities attached to the status page
        :param pulumi.Input[_builtins.str] ga_tracking_id: Google Analytics tracking ID
        :param pulumi.Input[_builtins.str] header_color: The color of the header. Eg. "#0061F2"
        :param pulumi.Input[_builtins.bool] public: Make the status page accessible to the public. Value must be one of true or false
        :param pulumi.Input[_builtins.str] public_description: The public description of the status page
        :param pulumi.Input[_builtins.str] public_title: The public title of the status page
        :param pulumi.Input[_builtins.str] saml_idp_cert: SAML IdP certificate
        :param pulumi.Input[_builtins.str] saml_idp_cert_fingerprint: SAML IdP certificate fingerprint
        :param pulumi.Input[_builtins.str] saml_idp_slo_service_url: SAML IdP SLO service URL
        :param pulumi.Input[_builtins.str] saml_idp_sso_service_url: SAML IdP SSO service URL
        :param pulumi.Input[_builtins.str] saml_name_identifier_format: SAML name identifier format. Value must be one of `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`, `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`, `urn:oasis:names:tc:SAML:2.0:nameid-format:transient`, `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] section_orders: Order of sections on the status page. Value must be a list of <span pulumi-lang-nodejs="`maintenance`" pulumi-lang-dotnet="`Maintenance`" pulumi-lang-go="`maintenance`" pulumi-lang-python="`maintenance`" pulumi-lang-yaml="`maintenance`" pulumi-lang-java="`maintenance`" pulumi-lang-hcl="`maintenance`">`maintenance`</span>, <span pulumi-lang-nodejs="`systemStatus`" pulumi-lang-dotnet="`SystemStatus`" pulumi-lang-go="`systemStatus`" pulumi-lang-python="`system_status`" pulumi-lang-yaml="`systemStatus`" pulumi-lang-java="`systemStatus`" pulumi-lang-hcl="`system_status`">`systemStatus`</span>, <span pulumi-lang-nodejs="`incidents`" pulumi-lang-dotnet="`Incidents`" pulumi-lang-go="`incidents`" pulumi-lang-python="`incidents`" pulumi-lang-yaml="`incidents`" pulumi-lang-java="`incidents`" pulumi-lang-hcl="`incidents`">`incidents`</span>.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] service_ids: Services attached to the status page
        :param pulumi.Input[_builtins.bool] show_uptime: Show uptime. Value must be one of true or false
        :param pulumi.Input[_builtins.float] show_uptime_last_days: Show uptime over x days. Value must be one of <span pulumi-lang-nodejs="`30`" pulumi-lang-dotnet="`30`" pulumi-lang-go="`30`" pulumi-lang-python="`30`" pulumi-lang-yaml="`30`" pulumi-lang-java="`30`" pulumi-lang-hcl="`30`">`30`</span>, <span pulumi-lang-nodejs="`60`" pulumi-lang-dotnet="`60`" pulumi-lang-go="`60`" pulumi-lang-python="`60`" pulumi-lang-yaml="`60`" pulumi-lang-java="`60`" pulumi-lang-hcl="`60`">`60`</span>, <span pulumi-lang-nodejs="`90`" pulumi-lang-dotnet="`90`" pulumi-lang-go="`90`" pulumi-lang-python="`90`" pulumi-lang-yaml="`90`" pulumi-lang-java="`90`" pulumi-lang-hcl="`90`">`90`</span>.
        :param pulumi.Input[_builtins.str] slug: The slug of the status page
        :param pulumi.Input[_builtins.str] success_message: Message showing when all components are operational
        :param pulumi.Input[_builtins.str] time_zone: A valid IANA time zone name.
        :param pulumi.Input[_builtins.str] title: The title of the status page
        :param pulumi.Input[_builtins.str] website_privacy_url: Website Privacy URL
        :param pulumi.Input[_builtins.str] website_support_url: Website Support URL
        :param pulumi.Input[_builtins.str] website_url: Website URL
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _StatusPageState.__new__(_StatusPageState)

        __props__.__dict__["allow_search_engine_index"] = allow_search_engine_index
        __props__.__dict__["authentication_enabled"] = authentication_enabled
        __props__.__dict__["authentication_method"] = authentication_method
        __props__.__dict__["authentication_password"] = authentication_password
        __props__.__dict__["cname_records"] = cname_records
        __props__.__dict__["description"] = description
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["external_domain_names"] = external_domain_names
        __props__.__dict__["failure_message"] = failure_message
        __props__.__dict__["footer_color"] = footer_color
        __props__.__dict__["functionality_ids"] = functionality_ids
        __props__.__dict__["ga_tracking_id"] = ga_tracking_id
        __props__.__dict__["header_color"] = header_color
        __props__.__dict__["public"] = public
        __props__.__dict__["public_description"] = public_description
        __props__.__dict__["public_title"] = public_title
        __props__.__dict__["saml_idp_cert"] = saml_idp_cert
        __props__.__dict__["saml_idp_cert_fingerprint"] = saml_idp_cert_fingerprint
        __props__.__dict__["saml_idp_slo_service_url"] = saml_idp_slo_service_url
        __props__.__dict__["saml_idp_sso_service_url"] = saml_idp_sso_service_url
        __props__.__dict__["saml_name_identifier_format"] = saml_name_identifier_format
        __props__.__dict__["section_orders"] = section_orders
        __props__.__dict__["service_ids"] = service_ids
        __props__.__dict__["show_uptime"] = show_uptime
        __props__.__dict__["show_uptime_last_days"] = show_uptime_last_days
        __props__.__dict__["slug"] = slug
        __props__.__dict__["status_page_id"] = status_page_id
        __props__.__dict__["success_message"] = success_message
        __props__.__dict__["time_zone"] = time_zone
        __props__.__dict__["title"] = title
        __props__.__dict__["website_privacy_url"] = website_privacy_url
        __props__.__dict__["website_support_url"] = website_support_url
        __props__.__dict__["website_url"] = website_url
        return StatusPage(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allowSearchEngineIndex")
    def allow_search_engine_index(self) -> pulumi.Output[_builtins.bool]:
        """
        Allow search engines to include your public status page in search results. Value must be one of true or false
        """
        return pulumi.get(self, "allow_search_engine_index")

    @_builtins.property
    @pulumi.getter(name="authenticationEnabled")
    def authentication_enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Enable authentication (deprecated - use<span pulumi-lang-nodejs=" authenticationMethod " pulumi-lang-dotnet=" AuthenticationMethod " pulumi-lang-go=" authenticationMethod " pulumi-lang-python=" authentication_method " pulumi-lang-yaml=" authenticationMethod " pulumi-lang-java=" authenticationMethod " pulumi-lang-hcl=" authentication_method "> authenticationMethod </span>instead). Value must be one of true or false
        """
        return pulumi.get(self, "authentication_enabled")

    @_builtins.property
    @pulumi.getter(name="authenticationMethod")
    def authentication_method(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Authentication method. Value must be one of <span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`">`none`</span>, <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`" pulumi-lang-hcl="`password`">`password`</span>, <span pulumi-lang-nodejs="`saml`" pulumi-lang-dotnet="`Saml`" pulumi-lang-go="`saml`" pulumi-lang-python="`saml`" pulumi-lang-yaml="`saml`" pulumi-lang-java="`saml`" pulumi-lang-hcl="`saml`">`saml`</span>.
        """
        return pulumi.get(self, "authentication_method")

    @_builtins.property
    @pulumi.getter(name="authenticationPassword")
    def authentication_password(self) -> pulumi.Output[_builtins.str]:
        """
        Authentication password
        """
        return pulumi.get(self, "authentication_password")

    @_builtins.property
    @pulumi.getter(name="cnameRecords")
    def cname_records(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        CNAME records mapping external domain names to their DNS target values. Populated asynchronously after setting external_domain_names.
        """
        return pulumi.get(self, "cname_records")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        The description of the status page
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="externalDomainNames")
    def external_domain_names(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        External domain names attached to the status page
        """
        return pulumi.get(self, "external_domain_names")

    @_builtins.property
    @pulumi.getter(name="failureMessage")
    def failure_message(self) -> pulumi.Output[_builtins.str]:
        """
        Message showing when at least one component is not operational
        """
        return pulumi.get(self, "failure_message")

    @_builtins.property
    @pulumi.getter(name="footerColor")
    def footer_color(self) -> pulumi.Output[_builtins.str]:
        """
        The color of the footer. Eg. "#1F2F41"
        """
        return pulumi.get(self, "footer_color")

    @_builtins.property
    @pulumi.getter(name="functionalityIds")
    def functionality_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Functionalities attached to the status page
        """
        return pulumi.get(self, "functionality_ids")

    @_builtins.property
    @pulumi.getter(name="gaTrackingId")
    def ga_tracking_id(self) -> pulumi.Output[_builtins.str]:
        """
        Google Analytics tracking ID
        """
        return pulumi.get(self, "ga_tracking_id")

    @_builtins.property
    @pulumi.getter(name="headerColor")
    def header_color(self) -> pulumi.Output[_builtins.str]:
        """
        The color of the header. Eg. "#0061F2"
        """
        return pulumi.get(self, "header_color")

    @_builtins.property
    @pulumi.getter
    def public(self) -> pulumi.Output[_builtins.bool]:
        """
        Make the status page accessible to the public. Value must be one of true or false
        """
        return pulumi.get(self, "public")

    @_builtins.property
    @pulumi.getter(name="publicDescription")
    def public_description(self) -> pulumi.Output[_builtins.str]:
        """
        The public description of the status page
        """
        return pulumi.get(self, "public_description")

    @_builtins.property
    @pulumi.getter(name="publicTitle")
    def public_title(self) -> pulumi.Output[_builtins.str]:
        """
        The public title of the status page
        """
        return pulumi.get(self, "public_title")

    @_builtins.property
    @pulumi.getter(name="samlIdpCert")
    def saml_idp_cert(self) -> pulumi.Output[_builtins.str]:
        """
        SAML IdP certificate
        """
        return pulumi.get(self, "saml_idp_cert")

    @_builtins.property
    @pulumi.getter(name="samlIdpCertFingerprint")
    def saml_idp_cert_fingerprint(self) -> pulumi.Output[_builtins.str]:
        """
        SAML IdP certificate fingerprint
        """
        return pulumi.get(self, "saml_idp_cert_fingerprint")

    @_builtins.property
    @pulumi.getter(name="samlIdpSloServiceUrl")
    def saml_idp_slo_service_url(self) -> pulumi.Output[_builtins.str]:
        """
        SAML IdP SLO service URL
        """
        return pulumi.get(self, "saml_idp_slo_service_url")

    @_builtins.property
    @pulumi.getter(name="samlIdpSsoServiceUrl")
    def saml_idp_sso_service_url(self) -> pulumi.Output[_builtins.str]:
        """
        SAML IdP SSO service URL
        """
        return pulumi.get(self, "saml_idp_sso_service_url")

    @_builtins.property
    @pulumi.getter(name="samlNameIdentifierFormat")
    def saml_name_identifier_format(self) -> pulumi.Output[_builtins.str]:
        """
        SAML name identifier format. Value must be one of `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`, `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`, `urn:oasis:names:tc:SAML:2.0:nameid-format:transient`, `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`.
        """
        return pulumi.get(self, "saml_name_identifier_format")

    @_builtins.property
    @pulumi.getter(name="sectionOrders")
    def section_orders(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Order of sections on the status page. Value must be a list of <span pulumi-lang-nodejs="`maintenance`" pulumi-lang-dotnet="`Maintenance`" pulumi-lang-go="`maintenance`" pulumi-lang-python="`maintenance`" pulumi-lang-yaml="`maintenance`" pulumi-lang-java="`maintenance`" pulumi-lang-hcl="`maintenance`">`maintenance`</span>, <span pulumi-lang-nodejs="`systemStatus`" pulumi-lang-dotnet="`SystemStatus`" pulumi-lang-go="`systemStatus`" pulumi-lang-python="`system_status`" pulumi-lang-yaml="`systemStatus`" pulumi-lang-java="`systemStatus`" pulumi-lang-hcl="`system_status`">`systemStatus`</span>, <span pulumi-lang-nodejs="`incidents`" pulumi-lang-dotnet="`Incidents`" pulumi-lang-go="`incidents`" pulumi-lang-python="`incidents`" pulumi-lang-yaml="`incidents`" pulumi-lang-java="`incidents`" pulumi-lang-hcl="`incidents`">`incidents`</span>.
        """
        return pulumi.get(self, "section_orders")

    @_builtins.property
    @pulumi.getter(name="serviceIds")
    def service_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Services attached to the status page
        """
        return pulumi.get(self, "service_ids")

    @_builtins.property
    @pulumi.getter(name="showUptime")
    def show_uptime(self) -> pulumi.Output[_builtins.bool]:
        """
        Show uptime. Value must be one of true or false
        """
        return pulumi.get(self, "show_uptime")

    @_builtins.property
    @pulumi.getter(name="showUptimeLastDays")
    def show_uptime_last_days(self) -> pulumi.Output[_builtins.float]:
        """
        Show uptime over x days. Value must be one of <span pulumi-lang-nodejs="`30`" pulumi-lang-dotnet="`30`" pulumi-lang-go="`30`" pulumi-lang-python="`30`" pulumi-lang-yaml="`30`" pulumi-lang-java="`30`" pulumi-lang-hcl="`30`">`30`</span>, <span pulumi-lang-nodejs="`60`" pulumi-lang-dotnet="`60`" pulumi-lang-go="`60`" pulumi-lang-python="`60`" pulumi-lang-yaml="`60`" pulumi-lang-java="`60`" pulumi-lang-hcl="`60`">`60`</span>, <span pulumi-lang-nodejs="`90`" pulumi-lang-dotnet="`90`" pulumi-lang-go="`90`" pulumi-lang-python="`90`" pulumi-lang-yaml="`90`" pulumi-lang-java="`90`" pulumi-lang-hcl="`90`">`90`</span>.
        """
        return pulumi.get(self, "show_uptime_last_days")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Output[_builtins.str]:
        """
        The slug of the status page
        """
        return pulumi.get(self, "slug")

    @_builtins.property
    @pulumi.getter(name="statusPageId")
    def status_page_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "status_page_id")

    @_builtins.property
    @pulumi.getter(name="successMessage")
    def success_message(self) -> pulumi.Output[_builtins.str]:
        """
        Message showing when all components are operational
        """
        return pulumi.get(self, "success_message")

    @_builtins.property
    @pulumi.getter(name="timeZone")
    def time_zone(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A valid IANA time zone name.
        """
        return pulumi.get(self, "time_zone")

    @_builtins.property
    @pulumi.getter
    def title(self) -> pulumi.Output[_builtins.str]:
        """
        The title of the status page
        """
        return pulumi.get(self, "title")

    @_builtins.property
    @pulumi.getter(name="websitePrivacyUrl")
    def website_privacy_url(self) -> pulumi.Output[_builtins.str]:
        """
        Website Privacy URL
        """
        return pulumi.get(self, "website_privacy_url")

    @_builtins.property
    @pulumi.getter(name="websiteSupportUrl")
    def website_support_url(self) -> pulumi.Output[_builtins.str]:
        """
        Website Support URL
        """
        return pulumi.get(self, "website_support_url")

    @_builtins.property
    @pulumi.getter(name="websiteUrl")
    def website_url(self) -> pulumi.Output[_builtins.str]:
        """
        Website URL
        """
        return pulumi.get(self, "website_url")

