# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['WorkflowGroupArgs', 'WorkflowGroup']

@pulumi.input_type
class WorkflowGroupArgs:
    def __init__(__self__, *,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expanded: pulumi.Input[Optional[_builtins.bool]] = None,
                 icon: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 workflow_group_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a WorkflowGroup resource.

        :param pulumi.Input[_builtins.str] description: A description of the workflow group.
        :param pulumi.Input[_builtins.bool] expanded: Whether the group is expanded or collapsed.. Value must be one of true or false
        :param pulumi.Input[_builtins.str] icon: An emoji icon displayed next to the workflow group.
        :param pulumi.Input[_builtins.str] kind: The kind of the workflow group. Value must be one of <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span>, <span pulumi-lang-nodejs="`incident`" pulumi-lang-dotnet="`Incident`" pulumi-lang-go="`incident`" pulumi-lang-python="`incident`" pulumi-lang-yaml="`incident`" pulumi-lang-java="`incident`" pulumi-lang-hcl="`incident`">`incident`</span>, <span pulumi-lang-nodejs="`postMortem`" pulumi-lang-dotnet="`PostMortem`" pulumi-lang-go="`postMortem`" pulumi-lang-python="`post_mortem`" pulumi-lang-yaml="`postMortem`" pulumi-lang-java="`postMortem`" pulumi-lang-hcl="`post_mortem`">`postMortem`</span>, <span pulumi-lang-nodejs="`actionItem`" pulumi-lang-dotnet="`ActionItem`" pulumi-lang-go="`actionItem`" pulumi-lang-python="`action_item`" pulumi-lang-yaml="`actionItem`" pulumi-lang-java="`actionItem`" pulumi-lang-hcl="`action_item`">`actionItem`</span>, <span pulumi-lang-nodejs="`pulse`" pulumi-lang-dotnet="`Pulse`" pulumi-lang-go="`pulse`" pulumi-lang-python="`pulse`" pulumi-lang-yaml="`pulse`" pulumi-lang-java="`pulse`" pulumi-lang-hcl="`pulse`">`pulse`</span>, <span pulumi-lang-nodejs="`alert`" pulumi-lang-dotnet="`Alert`" pulumi-lang-go="`alert`" pulumi-lang-python="`alert`" pulumi-lang-yaml="`alert`" pulumi-lang-java="`alert`" pulumi-lang-hcl="`alert`">`alert`</span>.
        :param pulumi.Input[_builtins.str] name: The name of the workflow group.
        :param pulumi.Input[_builtins.float] position: The position of the workflow group
        :param pulumi.Input[_builtins.str] slug: The slug of the workflow group.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if expanded is not None:
            pulumi.set(__self__, "expanded", expanded)
        if icon is not None:
            pulumi.set(__self__, "icon", icon)
        if kind is not None:
            pulumi.set(__self__, "kind", kind)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if position is not None:
            pulumi.set(__self__, "position", position)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)
        if workflow_group_id is not None:
            pulumi.set(__self__, "workflow_group_id", workflow_group_id)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A description of the workflow group.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def expanded(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the group is expanded or collapsed.. Value must be one of true or false
        """
        return pulumi.get(self, "expanded")

    @expanded.setter
    def expanded(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "expanded", value)

    @_builtins.property
    @pulumi.getter
    def icon(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        An emoji icon displayed next to the workflow group.
        """
        return pulumi.get(self, "icon")

    @icon.setter
    def icon(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "icon", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The kind of the workflow group. Value must be one of <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span>, <span pulumi-lang-nodejs="`incident`" pulumi-lang-dotnet="`Incident`" pulumi-lang-go="`incident`" pulumi-lang-python="`incident`" pulumi-lang-yaml="`incident`" pulumi-lang-java="`incident`" pulumi-lang-hcl="`incident`">`incident`</span>, <span pulumi-lang-nodejs="`postMortem`" pulumi-lang-dotnet="`PostMortem`" pulumi-lang-go="`postMortem`" pulumi-lang-python="`post_mortem`" pulumi-lang-yaml="`postMortem`" pulumi-lang-java="`postMortem`" pulumi-lang-hcl="`post_mortem`">`postMortem`</span>, <span pulumi-lang-nodejs="`actionItem`" pulumi-lang-dotnet="`ActionItem`" pulumi-lang-go="`actionItem`" pulumi-lang-python="`action_item`" pulumi-lang-yaml="`actionItem`" pulumi-lang-java="`actionItem`" pulumi-lang-hcl="`action_item`">`actionItem`</span>, <span pulumi-lang-nodejs="`pulse`" pulumi-lang-dotnet="`Pulse`" pulumi-lang-go="`pulse`" pulumi-lang-python="`pulse`" pulumi-lang-yaml="`pulse`" pulumi-lang-java="`pulse`" pulumi-lang-hcl="`pulse`">`pulse`</span>, <span pulumi-lang-nodejs="`alert`" pulumi-lang-dotnet="`Alert`" pulumi-lang-go="`alert`" pulumi-lang-python="`alert`" pulumi-lang-yaml="`alert`" pulumi-lang-java="`alert`" pulumi-lang-hcl="`alert`">`alert`</span>.
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the workflow group.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The position of the workflow group
        """
        return pulumi.get(self, "position")

    @position.setter
    def position(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "position", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The slug of the workflow group.
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "slug", value)

    @_builtins.property
    @pulumi.getter(name="workflowGroupId")
    def workflow_group_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "workflow_group_id")

    @workflow_group_id.setter
    def workflow_group_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "workflow_group_id", value)


@pulumi.input_type
class _WorkflowGroupState:
    def __init__(__self__, *,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expanded: pulumi.Input[Optional[_builtins.bool]] = None,
                 icon: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 workflow_group_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering WorkflowGroup resources.

        :param pulumi.Input[_builtins.str] description: A description of the workflow group.
        :param pulumi.Input[_builtins.bool] expanded: Whether the group is expanded or collapsed.. Value must be one of true or false
        :param pulumi.Input[_builtins.str] icon: An emoji icon displayed next to the workflow group.
        :param pulumi.Input[_builtins.str] kind: The kind of the workflow group. Value must be one of <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span>, <span pulumi-lang-nodejs="`incident`" pulumi-lang-dotnet="`Incident`" pulumi-lang-go="`incident`" pulumi-lang-python="`incident`" pulumi-lang-yaml="`incident`" pulumi-lang-java="`incident`" pulumi-lang-hcl="`incident`">`incident`</span>, <span pulumi-lang-nodejs="`postMortem`" pulumi-lang-dotnet="`PostMortem`" pulumi-lang-go="`postMortem`" pulumi-lang-python="`post_mortem`" pulumi-lang-yaml="`postMortem`" pulumi-lang-java="`postMortem`" pulumi-lang-hcl="`post_mortem`">`postMortem`</span>, <span pulumi-lang-nodejs="`actionItem`" pulumi-lang-dotnet="`ActionItem`" pulumi-lang-go="`actionItem`" pulumi-lang-python="`action_item`" pulumi-lang-yaml="`actionItem`" pulumi-lang-java="`actionItem`" pulumi-lang-hcl="`action_item`">`actionItem`</span>, <span pulumi-lang-nodejs="`pulse`" pulumi-lang-dotnet="`Pulse`" pulumi-lang-go="`pulse`" pulumi-lang-python="`pulse`" pulumi-lang-yaml="`pulse`" pulumi-lang-java="`pulse`" pulumi-lang-hcl="`pulse`">`pulse`</span>, <span pulumi-lang-nodejs="`alert`" pulumi-lang-dotnet="`Alert`" pulumi-lang-go="`alert`" pulumi-lang-python="`alert`" pulumi-lang-yaml="`alert`" pulumi-lang-java="`alert`" pulumi-lang-hcl="`alert`">`alert`</span>.
        :param pulumi.Input[_builtins.str] name: The name of the workflow group.
        :param pulumi.Input[_builtins.float] position: The position of the workflow group
        :param pulumi.Input[_builtins.str] slug: The slug of the workflow group.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if expanded is not None:
            pulumi.set(__self__, "expanded", expanded)
        if icon is not None:
            pulumi.set(__self__, "icon", icon)
        if kind is not None:
            pulumi.set(__self__, "kind", kind)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if position is not None:
            pulumi.set(__self__, "position", position)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)
        if workflow_group_id is not None:
            pulumi.set(__self__, "workflow_group_id", workflow_group_id)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A description of the workflow group.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def expanded(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the group is expanded or collapsed.. Value must be one of true or false
        """
        return pulumi.get(self, "expanded")

    @expanded.setter
    def expanded(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "expanded", value)

    @_builtins.property
    @pulumi.getter
    def icon(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        An emoji icon displayed next to the workflow group.
        """
        return pulumi.get(self, "icon")

    @icon.setter
    def icon(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "icon", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The kind of the workflow group. Value must be one of <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span>, <span pulumi-lang-nodejs="`incident`" pulumi-lang-dotnet="`Incident`" pulumi-lang-go="`incident`" pulumi-lang-python="`incident`" pulumi-lang-yaml="`incident`" pulumi-lang-java="`incident`" pulumi-lang-hcl="`incident`">`incident`</span>, <span pulumi-lang-nodejs="`postMortem`" pulumi-lang-dotnet="`PostMortem`" pulumi-lang-go="`postMortem`" pulumi-lang-python="`post_mortem`" pulumi-lang-yaml="`postMortem`" pulumi-lang-java="`postMortem`" pulumi-lang-hcl="`post_mortem`">`postMortem`</span>, <span pulumi-lang-nodejs="`actionItem`" pulumi-lang-dotnet="`ActionItem`" pulumi-lang-go="`actionItem`" pulumi-lang-python="`action_item`" pulumi-lang-yaml="`actionItem`" pulumi-lang-java="`actionItem`" pulumi-lang-hcl="`action_item`">`actionItem`</span>, <span pulumi-lang-nodejs="`pulse`" pulumi-lang-dotnet="`Pulse`" pulumi-lang-go="`pulse`" pulumi-lang-python="`pulse`" pulumi-lang-yaml="`pulse`" pulumi-lang-java="`pulse`" pulumi-lang-hcl="`pulse`">`pulse`</span>, <span pulumi-lang-nodejs="`alert`" pulumi-lang-dotnet="`Alert`" pulumi-lang-go="`alert`" pulumi-lang-python="`alert`" pulumi-lang-yaml="`alert`" pulumi-lang-java="`alert`" pulumi-lang-hcl="`alert`">`alert`</span>.
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the workflow group.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The position of the workflow group
        """
        return pulumi.get(self, "position")

    @position.setter
    def position(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "position", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The slug of the workflow group.
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "slug", value)

    @_builtins.property
    @pulumi.getter(name="workflowGroupId")
    def workflow_group_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "workflow_group_id")

    @workflow_group_id.setter
    def workflow_group_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "workflow_group_id", value)


@pulumi.type_token("rootly:index/workflowGroup:WorkflowGroup")
class WorkflowGroup(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expanded: pulumi.Input[Optional[_builtins.bool]] = None,
                 icon: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 workflow_group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a WorkflowGroup resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: A description of the workflow group.
        :param pulumi.Input[_builtins.bool] expanded: Whether the group is expanded or collapsed.. Value must be one of true or false
        :param pulumi.Input[_builtins.str] icon: An emoji icon displayed next to the workflow group.
        :param pulumi.Input[_builtins.str] kind: The kind of the workflow group. Value must be one of <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span>, <span pulumi-lang-nodejs="`incident`" pulumi-lang-dotnet="`Incident`" pulumi-lang-go="`incident`" pulumi-lang-python="`incident`" pulumi-lang-yaml="`incident`" pulumi-lang-java="`incident`" pulumi-lang-hcl="`incident`">`incident`</span>, <span pulumi-lang-nodejs="`postMortem`" pulumi-lang-dotnet="`PostMortem`" pulumi-lang-go="`postMortem`" pulumi-lang-python="`post_mortem`" pulumi-lang-yaml="`postMortem`" pulumi-lang-java="`postMortem`" pulumi-lang-hcl="`post_mortem`">`postMortem`</span>, <span pulumi-lang-nodejs="`actionItem`" pulumi-lang-dotnet="`ActionItem`" pulumi-lang-go="`actionItem`" pulumi-lang-python="`action_item`" pulumi-lang-yaml="`actionItem`" pulumi-lang-java="`actionItem`" pulumi-lang-hcl="`action_item`">`actionItem`</span>, <span pulumi-lang-nodejs="`pulse`" pulumi-lang-dotnet="`Pulse`" pulumi-lang-go="`pulse`" pulumi-lang-python="`pulse`" pulumi-lang-yaml="`pulse`" pulumi-lang-java="`pulse`" pulumi-lang-hcl="`pulse`">`pulse`</span>, <span pulumi-lang-nodejs="`alert`" pulumi-lang-dotnet="`Alert`" pulumi-lang-go="`alert`" pulumi-lang-python="`alert`" pulumi-lang-yaml="`alert`" pulumi-lang-java="`alert`" pulumi-lang-hcl="`alert`">`alert`</span>.
        :param pulumi.Input[_builtins.str] name: The name of the workflow group.
        :param pulumi.Input[_builtins.float] position: The position of the workflow group
        :param pulumi.Input[_builtins.str] slug: The slug of the workflow group.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[WorkflowGroupArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a WorkflowGroup resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param WorkflowGroupArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(WorkflowGroupArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expanded: pulumi.Input[Optional[_builtins.bool]] = None,
                 icon: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 workflow_group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = WorkflowGroupArgs.__new__(WorkflowGroupArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["expanded"] = expanded
            __props__.__dict__["icon"] = icon
            __props__.__dict__["kind"] = kind
            __props__.__dict__["name"] = name
            __props__.__dict__["position"] = position
            __props__.__dict__["slug"] = slug
            __props__.__dict__["workflow_group_id"] = workflow_group_id
        super(WorkflowGroup, __self__).__init__(
            'rootly:index/workflowGroup:WorkflowGroup',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            expanded: pulumi.Input[Optional[_builtins.bool]] = None,
            icon: pulumi.Input[Optional[_builtins.str]] = None,
            kind: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            position: pulumi.Input[Optional[_builtins.float]] = None,
            slug: pulumi.Input[Optional[_builtins.str]] = None,
            workflow_group_id: pulumi.Input[Optional[_builtins.str]] = None) -> 'WorkflowGroup':
        """
        Get an existing WorkflowGroup resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: A description of the workflow group.
        :param pulumi.Input[_builtins.bool] expanded: Whether the group is expanded or collapsed.. Value must be one of true or false
        :param pulumi.Input[_builtins.str] icon: An emoji icon displayed next to the workflow group.
        :param pulumi.Input[_builtins.str] kind: The kind of the workflow group. Value must be one of <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span>, <span pulumi-lang-nodejs="`incident`" pulumi-lang-dotnet="`Incident`" pulumi-lang-go="`incident`" pulumi-lang-python="`incident`" pulumi-lang-yaml="`incident`" pulumi-lang-java="`incident`" pulumi-lang-hcl="`incident`">`incident`</span>, <span pulumi-lang-nodejs="`postMortem`" pulumi-lang-dotnet="`PostMortem`" pulumi-lang-go="`postMortem`" pulumi-lang-python="`post_mortem`" pulumi-lang-yaml="`postMortem`" pulumi-lang-java="`postMortem`" pulumi-lang-hcl="`post_mortem`">`postMortem`</span>, <span pulumi-lang-nodejs="`actionItem`" pulumi-lang-dotnet="`ActionItem`" pulumi-lang-go="`actionItem`" pulumi-lang-python="`action_item`" pulumi-lang-yaml="`actionItem`" pulumi-lang-java="`actionItem`" pulumi-lang-hcl="`action_item`">`actionItem`</span>, <span pulumi-lang-nodejs="`pulse`" pulumi-lang-dotnet="`Pulse`" pulumi-lang-go="`pulse`" pulumi-lang-python="`pulse`" pulumi-lang-yaml="`pulse`" pulumi-lang-java="`pulse`" pulumi-lang-hcl="`pulse`">`pulse`</span>, <span pulumi-lang-nodejs="`alert`" pulumi-lang-dotnet="`Alert`" pulumi-lang-go="`alert`" pulumi-lang-python="`alert`" pulumi-lang-yaml="`alert`" pulumi-lang-java="`alert`" pulumi-lang-hcl="`alert`">`alert`</span>.
        :param pulumi.Input[_builtins.str] name: The name of the workflow group.
        :param pulumi.Input[_builtins.float] position: The position of the workflow group
        :param pulumi.Input[_builtins.str] slug: The slug of the workflow group.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _WorkflowGroupState.__new__(_WorkflowGroupState)

        __props__.__dict__["description"] = description
        __props__.__dict__["expanded"] = expanded
        __props__.__dict__["icon"] = icon
        __props__.__dict__["kind"] = kind
        __props__.__dict__["name"] = name
        __props__.__dict__["position"] = position
        __props__.__dict__["slug"] = slug
        __props__.__dict__["workflow_group_id"] = workflow_group_id
        return WorkflowGroup(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        A description of the workflow group.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def expanded(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the group is expanded or collapsed.. Value must be one of true or false
        """
        return pulumi.get(self, "expanded")

    @_builtins.property
    @pulumi.getter
    def icon(self) -> pulumi.Output[_builtins.str]:
        """
        An emoji icon displayed next to the workflow group.
        """
        return pulumi.get(self, "icon")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Output[_builtins.str]:
        """
        The kind of the workflow group. Value must be one of <span pulumi-lang-nodejs="`simple`" pulumi-lang-dotnet="`Simple`" pulumi-lang-go="`simple`" pulumi-lang-python="`simple`" pulumi-lang-yaml="`simple`" pulumi-lang-java="`simple`" pulumi-lang-hcl="`simple`">`simple`</span>, <span pulumi-lang-nodejs="`incident`" pulumi-lang-dotnet="`Incident`" pulumi-lang-go="`incident`" pulumi-lang-python="`incident`" pulumi-lang-yaml="`incident`" pulumi-lang-java="`incident`" pulumi-lang-hcl="`incident`">`incident`</span>, <span pulumi-lang-nodejs="`postMortem`" pulumi-lang-dotnet="`PostMortem`" pulumi-lang-go="`postMortem`" pulumi-lang-python="`post_mortem`" pulumi-lang-yaml="`postMortem`" pulumi-lang-java="`postMortem`" pulumi-lang-hcl="`post_mortem`">`postMortem`</span>, <span pulumi-lang-nodejs="`actionItem`" pulumi-lang-dotnet="`ActionItem`" pulumi-lang-go="`actionItem`" pulumi-lang-python="`action_item`" pulumi-lang-yaml="`actionItem`" pulumi-lang-java="`actionItem`" pulumi-lang-hcl="`action_item`">`actionItem`</span>, <span pulumi-lang-nodejs="`pulse`" pulumi-lang-dotnet="`Pulse`" pulumi-lang-go="`pulse`" pulumi-lang-python="`pulse`" pulumi-lang-yaml="`pulse`" pulumi-lang-java="`pulse`" pulumi-lang-hcl="`pulse`">`pulse`</span>, <span pulumi-lang-nodejs="`alert`" pulumi-lang-dotnet="`Alert`" pulumi-lang-go="`alert`" pulumi-lang-python="`alert`" pulumi-lang-yaml="`alert`" pulumi-lang-java="`alert`" pulumi-lang-hcl="`alert`">`alert`</span>.
        """
        return pulumi.get(self, "kind")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the workflow group.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Output[_builtins.float]:
        """
        The position of the workflow group
        """
        return pulumi.get(self, "position")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Output[_builtins.str]:
        """
        The slug of the workflow group.
        """
        return pulumi.get(self, "slug")

    @_builtins.property
    @pulumi.getter(name="workflowGroupId")
    def workflow_group_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "workflow_group_id")

