# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['WorkflowTaskInviteToSlackChannelArgs', 'WorkflowTaskInviteToSlackChannel']

@pulumi.input_type
class WorkflowTaskInviteToSlackChannelArgs:
    def __init__(__self__, *,
                 task_params: pulumi.Input['WorkflowTaskInviteToSlackChannelTaskParamsArgs'],
                 workflow_id: pulumi.Input[_builtins.str],
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 skip_on_failure: pulumi.Input[Optional[_builtins.bool]] = None,
                 workflow_task_invite_to_slack_channel_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a WorkflowTaskInviteToSlackChannel resource.

        :param pulumi.Input['WorkflowTaskInviteToSlackChannelTaskParamsArgs'] task_params: The parameters for this workflow task.
        :param pulumi.Input[_builtins.str] workflow_id: The ID of the parent workflow
        :param pulumi.Input[_builtins.bool] enabled: Enable/disable this workflow task
        :param pulumi.Input[_builtins.str] name: Name of the workflow task
        :param pulumi.Input[_builtins.float] position: The position of the workflow task (1 being top of list)
        :param pulumi.Input[_builtins.bool] skip_on_failure: Skip workflow task if any failures
        """
        pulumi.set(__self__, "task_params", task_params)
        pulumi.set(__self__, "workflow_id", workflow_id)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if position is not None:
            pulumi.set(__self__, "position", position)
        if skip_on_failure is not None:
            pulumi.set(__self__, "skip_on_failure", skip_on_failure)
        if workflow_task_invite_to_slack_channel_id is not None:
            pulumi.set(__self__, "workflow_task_invite_to_slack_channel_id", workflow_task_invite_to_slack_channel_id)

    @_builtins.property
    @pulumi.getter(name="taskParams")
    def task_params(self) -> pulumi.Input['WorkflowTaskInviteToSlackChannelTaskParamsArgs']:
        """
        The parameters for this workflow task.
        """
        return pulumi.get(self, "task_params")

    @task_params.setter
    def task_params(self, value: pulumi.Input['WorkflowTaskInviteToSlackChannelTaskParamsArgs']):
        pulumi.set(self, "task_params", value)

    @_builtins.property
    @pulumi.getter(name="workflowId")
    def workflow_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the parent workflow
        """
        return pulumi.get(self, "workflow_id")

    @workflow_id.setter
    def workflow_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "workflow_id", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable/disable this workflow task
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the workflow task
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The position of the workflow task (1 being top of list)
        """
        return pulumi.get(self, "position")

    @position.setter
    def position(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "position", value)

    @_builtins.property
    @pulumi.getter(name="skipOnFailure")
    def skip_on_failure(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Skip workflow task if any failures
        """
        return pulumi.get(self, "skip_on_failure")

    @skip_on_failure.setter
    def skip_on_failure(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "skip_on_failure", value)

    @_builtins.property
    @pulumi.getter(name="workflowTaskInviteToSlackChannelId")
    def workflow_task_invite_to_slack_channel_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "workflow_task_invite_to_slack_channel_id")

    @workflow_task_invite_to_slack_channel_id.setter
    def workflow_task_invite_to_slack_channel_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "workflow_task_invite_to_slack_channel_id", value)


@pulumi.input_type
class _WorkflowTaskInviteToSlackChannelState:
    def __init__(__self__, *,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 skip_on_failure: pulumi.Input[Optional[_builtins.bool]] = None,
                 task_params: pulumi.Input[Optional['WorkflowTaskInviteToSlackChannelTaskParamsArgs']] = None,
                 workflow_id: pulumi.Input[Optional[_builtins.str]] = None,
                 workflow_task_invite_to_slack_channel_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering WorkflowTaskInviteToSlackChannel resources.

        :param pulumi.Input[_builtins.bool] enabled: Enable/disable this workflow task
        :param pulumi.Input[_builtins.str] name: Name of the workflow task
        :param pulumi.Input[_builtins.float] position: The position of the workflow task (1 being top of list)
        :param pulumi.Input[_builtins.bool] skip_on_failure: Skip workflow task if any failures
        :param pulumi.Input['WorkflowTaskInviteToSlackChannelTaskParamsArgs'] task_params: The parameters for this workflow task.
        :param pulumi.Input[_builtins.str] workflow_id: The ID of the parent workflow
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if position is not None:
            pulumi.set(__self__, "position", position)
        if skip_on_failure is not None:
            pulumi.set(__self__, "skip_on_failure", skip_on_failure)
        if task_params is not None:
            pulumi.set(__self__, "task_params", task_params)
        if workflow_id is not None:
            pulumi.set(__self__, "workflow_id", workflow_id)
        if workflow_task_invite_to_slack_channel_id is not None:
            pulumi.set(__self__, "workflow_task_invite_to_slack_channel_id", workflow_task_invite_to_slack_channel_id)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable/disable this workflow task
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the workflow task
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The position of the workflow task (1 being top of list)
        """
        return pulumi.get(self, "position")

    @position.setter
    def position(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "position", value)

    @_builtins.property
    @pulumi.getter(name="skipOnFailure")
    def skip_on_failure(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Skip workflow task if any failures
        """
        return pulumi.get(self, "skip_on_failure")

    @skip_on_failure.setter
    def skip_on_failure(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "skip_on_failure", value)

    @_builtins.property
    @pulumi.getter(name="taskParams")
    def task_params(self) -> pulumi.Input[Optional['WorkflowTaskInviteToSlackChannelTaskParamsArgs']]:
        """
        The parameters for this workflow task.
        """
        return pulumi.get(self, "task_params")

    @task_params.setter
    def task_params(self, value: pulumi.Input[Optional['WorkflowTaskInviteToSlackChannelTaskParamsArgs']]):
        pulumi.set(self, "task_params", value)

    @_builtins.property
    @pulumi.getter(name="workflowId")
    def workflow_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the parent workflow
        """
        return pulumi.get(self, "workflow_id")

    @workflow_id.setter
    def workflow_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "workflow_id", value)

    @_builtins.property
    @pulumi.getter(name="workflowTaskInviteToSlackChannelId")
    def workflow_task_invite_to_slack_channel_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "workflow_task_invite_to_slack_channel_id")

    @workflow_task_invite_to_slack_channel_id.setter
    def workflow_task_invite_to_slack_channel_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "workflow_task_invite_to_slack_channel_id", value)


@pulumi.type_token("rootly:index/workflowTaskInviteToSlackChannel:WorkflowTaskInviteToSlackChannel")
class WorkflowTaskInviteToSlackChannel(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 skip_on_failure: pulumi.Input[Optional[_builtins.bool]] = None,
                 task_params: pulumi.Input[Optional[Union['WorkflowTaskInviteToSlackChannelTaskParamsArgs', 'WorkflowTaskInviteToSlackChannelTaskParamsArgsDict']]] = None,
                 workflow_id: pulumi.Input[Optional[_builtins.str]] = None,
                 workflow_task_invite_to_slack_channel_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a WorkflowTaskInviteToSlackChannel resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] enabled: Enable/disable this workflow task
        :param pulumi.Input[_builtins.str] name: Name of the workflow task
        :param pulumi.Input[_builtins.float] position: The position of the workflow task (1 being top of list)
        :param pulumi.Input[_builtins.bool] skip_on_failure: Skip workflow task if any failures
        :param pulumi.Input[Union['WorkflowTaskInviteToSlackChannelTaskParamsArgs', 'WorkflowTaskInviteToSlackChannelTaskParamsArgsDict']] task_params: The parameters for this workflow task.
        :param pulumi.Input[_builtins.str] workflow_id: The ID of the parent workflow
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: WorkflowTaskInviteToSlackChannelArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a WorkflowTaskInviteToSlackChannel resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param WorkflowTaskInviteToSlackChannelArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(WorkflowTaskInviteToSlackChannelArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 position: pulumi.Input[Optional[_builtins.float]] = None,
                 skip_on_failure: pulumi.Input[Optional[_builtins.bool]] = None,
                 task_params: pulumi.Input[Optional[Union['WorkflowTaskInviteToSlackChannelTaskParamsArgs', 'WorkflowTaskInviteToSlackChannelTaskParamsArgsDict']]] = None,
                 workflow_id: pulumi.Input[Optional[_builtins.str]] = None,
                 workflow_task_invite_to_slack_channel_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = WorkflowTaskInviteToSlackChannelArgs.__new__(WorkflowTaskInviteToSlackChannelArgs)

            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["name"] = name
            __props__.__dict__["position"] = position
            __props__.__dict__["skip_on_failure"] = skip_on_failure
            if task_params is None and not opts.urn:
                raise TypeError("Missing required property 'task_params'")
            __props__.__dict__["task_params"] = task_params
            if workflow_id is None and not opts.urn:
                raise TypeError("Missing required property 'workflow_id'")
            __props__.__dict__["workflow_id"] = workflow_id
            __props__.__dict__["workflow_task_invite_to_slack_channel_id"] = workflow_task_invite_to_slack_channel_id
        super(WorkflowTaskInviteToSlackChannel, __self__).__init__(
            'rootly:index/workflowTaskInviteToSlackChannel:WorkflowTaskInviteToSlackChannel',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            position: pulumi.Input[Optional[_builtins.float]] = None,
            skip_on_failure: pulumi.Input[Optional[_builtins.bool]] = None,
            task_params: pulumi.Input[Optional[Union['WorkflowTaskInviteToSlackChannelTaskParamsArgs', 'WorkflowTaskInviteToSlackChannelTaskParamsArgsDict']]] = None,
            workflow_id: pulumi.Input[Optional[_builtins.str]] = None,
            workflow_task_invite_to_slack_channel_id: pulumi.Input[Optional[_builtins.str]] = None) -> 'WorkflowTaskInviteToSlackChannel':
        """
        Get an existing WorkflowTaskInviteToSlackChannel resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] enabled: Enable/disable this workflow task
        :param pulumi.Input[_builtins.str] name: Name of the workflow task
        :param pulumi.Input[_builtins.float] position: The position of the workflow task (1 being top of list)
        :param pulumi.Input[_builtins.bool] skip_on_failure: Skip workflow task if any failures
        :param pulumi.Input[Union['WorkflowTaskInviteToSlackChannelTaskParamsArgs', 'WorkflowTaskInviteToSlackChannelTaskParamsArgsDict']] task_params: The parameters for this workflow task.
        :param pulumi.Input[_builtins.str] workflow_id: The ID of the parent workflow
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _WorkflowTaskInviteToSlackChannelState.__new__(_WorkflowTaskInviteToSlackChannelState)

        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["name"] = name
        __props__.__dict__["position"] = position
        __props__.__dict__["skip_on_failure"] = skip_on_failure
        __props__.__dict__["task_params"] = task_params
        __props__.__dict__["workflow_id"] = workflow_id
        __props__.__dict__["workflow_task_invite_to_slack_channel_id"] = workflow_task_invite_to_slack_channel_id
        return WorkflowTaskInviteToSlackChannel(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Enable/disable this workflow task
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the workflow task
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def position(self) -> pulumi.Output[_builtins.float]:
        """
        The position of the workflow task (1 being top of list)
        """
        return pulumi.get(self, "position")

    @_builtins.property
    @pulumi.getter(name="skipOnFailure")
    def skip_on_failure(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Skip workflow task if any failures
        """
        return pulumi.get(self, "skip_on_failure")

    @_builtins.property
    @pulumi.getter(name="taskParams")
    def task_params(self) -> pulumi.Output['outputs.WorkflowTaskInviteToSlackChannelTaskParams']:
        """
        The parameters for this workflow task.
        """
        return pulumi.get(self, "task_params")

    @_builtins.property
    @pulumi.getter(name="workflowId")
    def workflow_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the parent workflow
        """
        return pulumi.get(self, "workflow_id")

    @_builtins.property
    @pulumi.getter(name="workflowTaskInviteToSlackChannelId")
    def workflow_task_invite_to_slack_channel_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "workflow_task_invite_to_slack_channel_id")

