---
secretsprovider: awskms://alias/infrastructure-secrets-production
encryptedkey: AQICAHjksIVfl1VtAHpBda/1YYjj6tSeS2o4TXgvEEyBIXLjjwG4tBva161e0ucBCCXDrIE0AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCwVqXQPcOnnWj2pXAgEQgDtsiON1HfCMzrDGGoOvkO+5PYHe12k24s6E6Sv0PqVuCTdZDIEbCVYOEVawgsdRYH/a0W0gjVZGDSRtnQ==
