---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHhMkpkBpCvmFjhyfy75ENALRrbg42uOs9cUsFNLXqPnagEqrkzp6cnQ0aYHWqyg3esKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMt5cCKS9BMIatKbEhAgEQgDtpLDNKXo6qc1mauPc2tVetS0ynqdfN3HtDVmQgSnVt+dA+maMvKPNqnDBFhA75ugTmy8oHn2y9SPYM9A==
