VERSION 0.7
FROM python:3.11-slim
WORKDIR /app


requirements:
  RUN python3 -m pip install poetry
  COPY ../../pyproject.toml .
  COPY ../../poetry.lock .
  RUN poetry export --only superset-customize --without-hashes --format=requirements.txt > requirements.txt
  SAVE ARTIFACT requirements.txt
customize:
  FROM apachesuperset.docker.scarf.sh/apache/superset:${SUPERSET_TAG:-latest}
  COPY +requirements/requirements.txt requirements.txt
  COPY superset_config.py /app
  RUN pip install --no-cache -r requirements.txt
