---
config:
  consul:address: https://consul-data-ci.odl.mit.edu
  clickhouse:hot_data_days: '1'
  clickhouse:hot_storage_size: 100Gi
  clickhouse:storage_class: ebs-gp3-sc
  clickhouse:replicas: '1'
  clickhouse:keeper_replicas: '1'
  clickhouse:version: 25.8.1.2953.altinitystable
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
