# odl-video-service Tiltfile

APP_DIR = os.path.abspath('../../../odl-video-service')
IMAGE = 'odlvideo-app'
NAMESPACE = 'odl-video-service'
DEPLOY_NAME = 'odlvideo-webapp'

docker_build(
    IMAGE,
    context=APP_DIR,
    dockerfile=APP_DIR + '/Dockerfile',
    live_update=[
        sync(APP_DIR + '/odl_video', '/src/odl_video'),
        run(
            'cd /src && pip install -r requirements.txt',
            trigger=[APP_DIR + '/requirements.txt'],
        ),
    ],
)

k8s_yaml([
    'configmaps/app-env.yaml',
    'configmaps/nginx.yaml',
    'secrets.yaml',
    'deployment.yaml',
    'apisix-routes.yaml',
])

k8s_resource(
    DEPLOY_NAME,
    port_forwards=['8088:8088'],
    labels=['odl-video-service'],
)

k8s_resource('odlvideo-celery', labels=['odl-video-service'])
k8s_resource('odlvideo-celery-beat', labels=['odl-video-service'])
