build_environment    = "mitx-ci"
edx_platform_version = "open-release/nutmeg.master"
edx_ansible_branch   = "open-release/nutmeg.master"
installation_target  = "mitx"
business_unit        = "residential"
