"""
Module of meaningful integer values.

This module consists of constants that are used to provide meaningful representations of
integer values used in infrastructure management.
"""

CONCOURSE_WEB_HOST_COMMUNICATION_PORT = 2222
CONSUL_DNS_PORT = 8600
DAYS_IN_MONTH = 30
DEFAULT_DNS_PORT = 53
DEFAULT_HTTPS_PORT = 443
DEFAULT_HTTP_PORT = 80
DEFAULT_MEMCACHED_PORT = 11211
DEFAULT_MONGODB_PORT = 27017
DEFAULT_MYSQL_PORT = 3306
DEFAULT_POSTGRES_PORT = 5432
DEFAULT_REDIS_PORT = 6379
HOURS_IN_DAY = 24
HOURS_IN_MONTH = HOURS_IN_DAY * DAYS_IN_MONTH
MAXIMUM_PORT_NUMBER = 65535
VAULT_CLUSTER_PORT = 8201
VAULT_HTTP_PORT = 8200
