"""Project ``versions.py`` into one tiny file per pin under ``version_pins/``.

``versions.py`` is the single readable record of every version this
infrastructure runs, and it must stay that way -- annotated, grouped, and
Renovate-managed in one place.  But Concourse ``git`` resources trigger on
*file* paths, so a pipeline that cares about exactly one constant in that file
has to watch the whole thing, and every unrelated bump anywhere in it
re-triggers that pipeline's AMI/image build and its CI->QA->Production deploy
chain.

The fix is to keep ``versions.py`` authoritative and derive a machine-watchable
projection of it: one extensionless file per constant, containing just that
constant's value.  A pipeline then watches ``version_pins/KEYCLOAK_VERSION``
and re-triggers only when *that* pin moves -- not when a comment is reflowed,
not when an unrelated chart is bumped.  See
``ol_concourse.pipelines.versions_map`` for which pipeline watches what.

The projection is regenerated by a pre-commit hook and re-derived by
``tests/ol_concourse/test_versions_map.py``, so it cannot drift from
``versions.py``.  Renovate keeps bumping ``versions.py`` alone -- pre-commit.ci
regenerates the pins inside the Renovate PR, so the two land in the same commit
and no second ``customManagers`` entry is needed.
"""

import ast
import sys
from pathlib import Path

VERSIONS_FILE = Path(__file__).parent / "versions.py"
PINS_DIR = Path(__file__).parent / "version_pins"
# Written by hand, not derived from versions.py, so the sync must leave it be.
PINS_README = "README.md"


def parse_pins(versions_source: str) -> dict[str, str]:
    """Extract every module-level ``NAME = "value"`` binding from ``versions.py``.

    Parsed rather than imported so that this stays usable as a standalone
    pre-commit hook with nothing but the standard library on the path.

    :param versions_source: Contents of ``src/bridge/lib/versions.py``.
    :returns: Constant name -> literal string value, in file order.
    """
    return {
        node.targets[0].id: node.value.value
        for node in ast.parse(versions_source).body
        if isinstance(node, ast.Assign)
        and len(node.targets) == 1
        and isinstance(node.targets[0], ast.Name)
        and isinstance(node.value, ast.Constant)
        and isinstance(node.value.value, str)
    }


def sync_pins(pins: dict[str, str], pins_dir: Path) -> list[str]:
    """Make ``pins_dir`` match ``pins`` exactly, and report what changed.

    :param pins: Constant name -> value, as returned by :func:`parse_pins`.
    :param pins_dir: Directory holding the projection.
    :returns: Human-readable descriptions of every file written or removed.
    """
    pins_dir.mkdir(parents=True, exist_ok=True)
    changed = []
    for name, value in pins.items():
        pin_file = pins_dir / name
        contents = f"{value}\n"
        if not pin_file.exists() or pin_file.read_text() != contents:
            pin_file.write_text(contents)
            changed.append(f"wrote {name}")
    for stale in pins_dir.iterdir():
        if stale.name != PINS_README and stale.name not in pins:
            stale.unlink()
            changed.append(f"removed {stale.name}")
    return changed


def main() -> int:
    """Regenerate the pin files, returning nonzero if any of them moved."""
    changed = sync_pins(parse_pins(VERSIONS_FILE.read_text()), PINS_DIR)
    for change in changed:
        sys.stdout.write(f"{PINS_DIR.name}: {change}\n")
    return 1 if changed else 0


if __name__ == "__main__":
    sys.exit(main())
