from pathlib import Path

import pulumi
import pulumi_fastly as fastly
from pulumi import Config
from pulumi_aws import route53

from bridge.lib.constants import FASTLY_A_TLS_1_3, FASTLY_CNAME_TLS_1_3
from ol_infrastructure.lib.aws.route53_helper import (
    fastly_certificate_validation_records,
    is_root_domain,
    lookup_zone_id_from_domain,
)
from ol_infrastructure.lib.fastly import get_fastly_provider
from ol_infrastructure.lib.pulumi_helper import parse_stack

stack_info = parse_stack()
redirect_config = Config("redirects")
fastly_provider = get_fastly_provider()
redirect_domains: list[str] = redirect_config.require_object("domains")
ol_redirect_service = fastly.ServiceVcl(
    "ol-redirect-service",
    backends=[
        {
            "address": "ol-redirect-service.s3.us-east-1.amazonaws.com",
            "name": "Empty Bucket for Fastly distribution to work",
            "override_host": "ol-redirect-service.s3.us-east-1.amazonaws.com",
            "port": 443,
            "ssl_cert_hostname": "ol-redirect-service.s3.us-east-1.amazonaws.com",
            "ssl_sni_hostname": "ol-redirect-service.s3.us-east-1.amazonaws.com",
            "use_ssl": True,
        }
    ],
    comment="Managed by Pulumi",
    dictionaries=[fastly.ServiceVclDictionaryArgs(name="redirects")],
    domains=[fastly.ServiceVclDomainArgs(name=domain) for domain in redirect_domains],
    headers=[
        {
            "action": "set",
            "destination": "http.Strict-Transport-Security",
            "name": "Generated by force TLS and enable HSTS",
            "source": '"max-age=300"',
            "type": "response",
        }
    ],
    name="ol-redirect-service",
    request_settings=[
        {
            "force_ssl": True,
            "name": "Generated by force TLS and enable HSTS",
            "xff": "",
        }
    ],
    snippets=[
        {
            "content": Path("snippets/recv_redirects.vcl").read_text(),
            "name": "recvRedirects",
            "type": "recv",
        },
        {
            "content": Path("snippets/route_redirects.vcl").read_text(),
            "name": "routeRedirects",
            "type": "error",
        },
    ],
    opts=pulumi.ResourceOptions(protect=True).merge(fastly_provider),
)

ol_redirect_service_redirects_dictionary = fastly.ServiceDictionaryItems(
    "ol-redirect-service-redirects-dictionary",
    dictionary_id=ol_redirect_service.dictionaries.apply(
        lambda dicts: next(
            (d["id"] for d in dicts if d["name"] == "redirects"),
            None
        )
    ),
    items={
        "/": "301|keep|https://docs.google.com/forms/d/e/1FAIpQLSdvkI2cPG1iMM4gN_KyKem4fNLh4irWzrmjX-JhcFXa51su5g/viewform?fbzx=2658557852628862500",
        "/courses/6/6.045/2015spring/L01/MIT-6.045-lec-mit-0000-2015apr07-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/65da1d1388ce400983c9447f75883760/?start=278",
        "/courses/6/6.045/2015spring/L01/MIT-6.045-lec-mit-0000-2015apr09-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/33abf21f4e174e6e8f21a5071c30a66f/?start=250",
        "/courses/6/6.045/2015spring/L01/MIT-6.045-lec-mit-0000-2015apr14-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/b5cc48724aa5405c9fd7b1211a2b0b3c/",
        "/courses/6/6.045/2015spring/L01/MIT-6.045-lec-mit-0000-2015apr16-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/201c33a2dab349359f5af23a293d9c5a/?start=333",
        "/courses/6/6.045/2015spring/L01/MIT-6.045-lec-mit-0000-2015apr23-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/9ea370cd18b14656a712e7cc723cf7a9/?start=393",
        "/courses/6/6.045/2015spring/L01/MIT-6.045-lec-mit-0000-2015apr28-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/59219f99dd30490e9586ad960ad2691f/?start=463",
        "/courses/6/6.045/2015spring/L01/MIT-6.045-lec-mit-0000-2015apr30-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/4656112ede89496fb100fe10b02fa304/?start=396",
        "/courses/6/6.045/2015spring/L01/MIT-6.045-lec-mit-0000-2015may05-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/b5cc48724aa5405c9fd7b1211a2b0b3c/",
        "/courses/6/6.045/2015spring/L01/MIT-6.045-lec-mit-0000-2015may07-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/c5691b38739d4a43a232bf3ef07f1646/?start=504",
        "/courses/6/6.045/2015spring/L01/MIT-6.045-lec-mit-0000-2015may14-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/ef3aa2b5dbb14adc9c15452b0d27c436/?start=398",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015feb03-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/7a11f55dd99d49349f377d2d87f0aef2/?start=341",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015feb05-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/2f043945501941e9a0fe35e5a4bbf782/",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015feb12-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/5d64d5e504c140a19efb1b69b5385482/",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015feb19-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/9178561d53b5460db360c72bd9dec2b5/?start=430",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015feb24-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/c973ebdcbca34ecf868cc12a0344d8f5/?start=268",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015feb26-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/7dcf75a64fa54356bc2e6f0a8e38fc79/?start=272",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015mar03-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/bc78f4af98e9492cbef7278d92156b92/?start=170",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015mar05-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/bc78f4af98e9492cbef7278d92156b92/?start=170",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015mar10-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/d7248606616240dca81337d163a28055/?start=172",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015mar12-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/08eaaeb932d54d119e529deac416e804/?start=331",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015mar17-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/3d86fd1c074840988b4480356e2d4746/?start=290",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015mar19-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/4c89dc64071f4c5ea5f948b80a2201bc/?start=128",
        "/courses/6/6.045/2015spring/MIT-6.045-lec-mit-0000-2015mar31-0929-L01/": "301|keep|https://video.odl.mit.edu/videos/5605b2609dcc4661b7aeb0c18645d5c9/?start=301",
    },
    service_id=ol_redirect_service.id,
    opts=pulumi.ResourceOptions(protect=True).merge(fastly_provider),
)

ol_redirect_service_tls = fastly.TlsSubscription(
    "ol-redirect-service-tls-subscription",
    # valid values are certainly, lets-encrypt, or globalsign
    certificate_authority="certainly",
    domains=list(redirect_domains),
    opts=fastly_provider,
)

ol_redirect_service_tls.managed_dns_challenges.apply(
    fastly_certificate_validation_records
)

validated_tls_subscription = fastly.TlsSubscriptionValidation(
    "ol-redirect-service-tls-subscription-validation",
    subscription_id=ol_redirect_service.id,
)

for domain in redirect_domains:
    if zone_id := lookup_zone_id_from_domain(domain):
        record_type = "A" if is_root_domain(domain) else "CNAME"
        record_map = {"A": FASTLY_A_TLS_1_3, "CNAME": [FASTLY_CNAME_TLS_1_3]}
        route53.Record(
            f"fastly-target-for-domain-{domain}",
            name=domain,
            type=record_type,
            records=[str(record) for record in record_map[record_type]],
            allow_overwrite=True,
            zone_id=zone_id,
        )
