import hashlib
import json
from pathlib import Path

import pulumi
import pulumi_fastly as fastly
from pulumi import Config

from ol_infrastructure.components.services.fastly import (
    OLFastlyDNSRecordConfig,
    OLFastlyTLS,
    OLFastlyTLSConfig,
)
from ol_infrastructure.lib.aws.route53_helper import (
    is_root_domain,
    lookup_zone_id_from_domain,
)
from ol_infrastructure.lib.fastly import get_fastly_provider
from ol_infrastructure.lib.pulumi_helper import parse_stack

stack_info = parse_stack()
redirect_config = Config("redirects")
fastly_provider = get_fastly_provider()
# Ensure we always have a ResourceOptions object for opts usage (typing convenience)
fastly_opts = (
    fastly_provider
    if isinstance(fastly_provider, pulumi.ResourceOptions)
    else pulumi.ResourceOptions(provider=fastly_provider)
)
"""Fastly redirector service

Now supports a domain->target mapping provided via Pulumi config.  The previous
configuration accepted a list of domains in `redirects:domains`.  Update your
stack config so that `redirects:domains` is now an object/map whose keys are
source domains and values are fully-qualified target origins (including
scheme).  Paths and query parameters from the original request will be
preserved when performing the redirect.

Backward compatibility: if the value is still a list, we fall back to the old
behaviour (no automatic host redirects) so existing stacks won't break until
their config is updated.
"""

_domains_config = redirect_config.require_object("domains")
redirect_domain_map: dict[str, str]
redirect_domains: list[str]
if isinstance(_domains_config, dict):  # new behaviour
    redirect_domain_map = _domains_config  # {source_host: target_base_url}
    redirect_domains = list(redirect_domain_map.keys())
else:  # legacy list behaviour
    redirect_domain_map = {}
    redirect_domains = list(_domains_config)
ol_redirect_service = fastly.ServiceVcl(
    "ol-redirect-service",
    backends=[
        {
            "address": "ol-redirect-service.s3.us-east-1.amazonaws.com",
            "name": "Empty Bucket for Fastly distribution to work",
            "override_host": "ol-redirect-service.s3.us-east-1.amazonaws.com",
            "port": 443,
            "ssl_cert_hostname": "ol-redirect-service.s3.us-east-1.amazonaws.com",
            "ssl_sni_hostname": "ol-redirect-service.s3.us-east-1.amazonaws.com",
            "use_ssl": True,
        }
    ],
    comment="Managed by Pulumi",
    dictionaries=[
        fastly.ServiceVclDictionaryArgs(name="redirects"),  # path level redirects
        fastly.ServiceVclDictionaryArgs(name="domain_redirects"),  # host -> target
    ],
    domains=[fastly.ServiceVclDomainArgs(name=domain) for domain in redirect_domains],
    headers=[
        {
            "action": "set",
            "destination": "http.Strict-Transport-Security",
            "name": "Generated by force TLS and enable HSTS",
            "source": '"max-age=300"',
            "type": "response",
        }
    ],
    name=f"ol-redirect-service-{stack_info.env_suffix}",
    request_settings=[
        {
            "force_ssl": True,
            "name": "Generated by force TLS and enable HSTS",
            "xff": "leave",
        }
    ],
    snippets=[
        {
            "content": Path(__file__)
            .parent.joinpath("snippets/recv_redirects.vcl")
            .read_text(),
            "name": "recvRedirects",
            "type": "recv",
        },
        {
            "content": Path(__file__)
            .parent.joinpath("snippets/route_redirects.vcl")
            .read_text(),
            "name": "routeRedirects",
            "type": "error",
        },
    ],
    # fastly_provider is already a ResourceOptions wrapper; add protect flag
    opts=fastly_opts.merge(pulumi.ResourceOptions(protect=True)),
)

if stack_info.env_suffix == "production":
    # Existing path-based redirect dictionary (unchanged semantics)
    redirects_dict_id = ol_redirect_service.dictionaries.apply(
        lambda dicts: str(
            next(d.dictionary_id for d in (dicts or []) if d.name == "redirects")
        )
    )
    ol_redirect_service_redirects_dictionary = fastly.ServiceDictionaryItems(
        "ol-redirect-service-redirects-dictionary",
        dictionary_id=redirects_dict_id,
        items=json.loads(
            Path(__file__).parent.joinpath("ovs_redirect_dict.json").read_text()
        ),
        service_id=ol_redirect_service.id,
        manage_items=True,
        opts=fastly_opts,
    )

# New domain redirect dictionary (created whenever mapping provided)
if redirect_domain_map:
    domain_redirects_dict_id = ol_redirect_service.dictionaries.apply(
        lambda dicts: str(
            next(d.dictionary_id for d in (dicts or []) if d.name == "domain_redirects")
        )
    )
    ol_redirect_service_domain_redirects_dictionary = fastly.ServiceDictionaryItems(
        "ol-redirect-service-domain-redirects-dictionary",
        dictionary_id=domain_redirects_dict_id,
        items=redirect_domain_map,
        service_id=ol_redirect_service.id,
        manage_items=True,
        opts=fastly_opts,
    )

# Generate hash of domains to identify subscription version
# When domains change, a new subscription will be created with a unique name
tls_domains = sorted(
    [domain for domain in redirect_domains if lookup_zone_id_from_domain(domain)]
)
domains_hash = hashlib.sha256(",".join(sorted(tls_domains)).encode()).hexdigest()[:8]
subscription_name = f"ol-redirect-service-tls-subscription-{domains_hash}"

ol_redirect_service_tls = OLFastlyTLS(
    f"ol-redirect-service-tls-{stack_info.env_suffix}",
    tls_config=OLFastlyTLSConfig(
        subscription_resource_name=subscription_name,
        validation_resource_name=f"{subscription_name}-validation",
        domains=tls_domains,
        dns_records=[
            OLFastlyDNSRecordConfig(
                resource_name=f"fastly-target-for-domain-{domain}",
                domain=domain,
                zone_id=zone_id,
                record_type="A" if is_root_domain(domain) else "CNAME",
                region="global",
            )
            for domain in redirect_domains
            if (zone_id := lookup_zone_id_from_domain(domain))
        ],
    ),
    opts=fastly_opts,
)
