from ol_concourse.pipelines.open_edx.mfe.pipeline import OpenEdxVars

mitx = [
    OpenEdxVars(
        environment="mitx-ci",
        environment_stage="CI",
        deployment_name="mitx",
        favicon_url="https://raw.githubusercontent.com/mitodl/mitx-theme/master/lms/static/images/favicon.ico",
        lms_domain="lms-ci.mitx.mit.edu",
        logo_url="https://raw.githubusercontent.com/mitodl/mitx-theme/master/lms/static/images/logo.png",
        marketing_site_domain="lms-ci.mitx.mit.edu",
        schedule_email_section="true",  # Because the communication MFE treats this boolean as string  # noqa: E501
        site_name="MITx Residential CI",
        studio_domain="studio-ci.mitx.mit.edu",
        support_url="odl.zendesk.com/hc/en-us/requests/new",
        terms_of_service_url="https://lms-ci.mitx.mit.edu/tos",
    ),
    OpenEdxVars(
        environment="mitx-qa",
        environment_stage="QA",
        deployment_name="mitx",
        favicon_url="https://raw.githubusercontent.com/mitodl/mitx-theme/master/lms/static/images/favicon.ico",
        lms_domain="mitx-qa.mitx.mit.edu",
        logo_url="https://raw.githubusercontent.com/mitodl/mitx-theme/master/lms/static/images/logo.png",
        marketing_site_domain="mitx-qa.mitx.mit.edu",
        site_name="MITx Residential QA",
        studio_domain="studio-mitx-qa.mitx.mit.edu",
        support_url="odl.zendesk.com/hc/en-us/requests/new",
        terms_of_service_url="https://mitx-qa.mitx.mit.edu/tos",
    ),
    OpenEdxVars(
        environment="mitx-production",
        environment_stage="Production",
        deployment_name="mitx",
        favicon_url="https://raw.githubusercontent.com/mitodl/mitx-theme/master/lms/static/images/favicon.ico",
        lms_domain="lms.mitx.mit.edu",
        logo_url="https://raw.githubusercontent.com/mitodl/mitx-theme/master/lms/static/images/logo.png",
        marketing_site_domain="lms.mitx.mit.edu",
        site_name="MITx Residential",
        studio_domain="studio.mitx.mit.edu",
        support_url="odl.zendesk.com/hc/en-us/requests/new",
        terms_of_service_url="https://lms.mitx.mit.edu/tos",
    ),
]

mitx_staging = [
    OpenEdxVars(
        deployment_name="mitx-staging",
        environment="mitx-staging-ci",
        environment_stage="CI",
        favicon_url="https://raw.githubusercontent.com/mitodl/mitx-theme/master/lms/static/images/favicon.ico",
        lms_domain="staging-ci.mitx.mit.edu",
        logo_url="https://raw.githubusercontent.com/mitodl/mitx-theme/master/lms/static/images/logo.png",
        marketing_site_domain="staging-ci.mitx.mit.edu",
        schedule_email_section="true",  # Because the communication MFE treats this boolean as string  # noqa: E501
        site_name="MITx Residential Staging CI",
        studio_domain="studio-staging-ci.mitx.mit.edu",
        support_url="odl.zendesk.com/hc/en-us/requests/new",
        terms_of_service_url="https://staging-ci.mitx.mit.edu/tos",
    ),
    OpenEdxVars(
        deployment_name="mitx-staging",
        environment="mitx-staging-qa",
        environment_stage="QA",
        favicon_url="https://raw.githubusercontent.com/mitodl/mitx-theme/master/lms/static/images/favicon.ico",
        lms_domain="mitx-qa-draft.mitx.mit.edu",
        logo_url="https://raw.githubusercontent.com/mitodl/mitx-theme/master/lms/static/images/logo.png",
        marketing_site_domain="mitx-qa-draft.mitx.mit.edu",
        site_name="MITx Residential Staging QA",
        studio_domain="studio-mitx-qa-draft.mitx.mit.edu",
        support_url="odl.zendesk.com/hc/en-us/requests/new",
        terms_of_service_url="https://mitx-qa-draft.mitx.mit.edu/tos",
    ),
    OpenEdxVars(
        deployment_name="mitx-staging",
        environment="mitx-staging-production",
        environment_stage="Production",
        favicon_url="https://raw.githubusercontent.com/mitodl/mitx-theme/master/lms/static/images/favicon.ico",
        lms_domain="staging.mitx.mit.edu",
        logo_url="https://raw.githubusercontent.com/mitodl/mitx-theme/master/lms/static/images/logo.png",
        marketing_site_domain="staging.mitx.mit.edu",
        site_name="MITx Residential Staging",
        studio_domain="studio-staging.mitx.mit.edu",
        support_url="odl.zendesk.com/hc/en-us/requests/new",
        terms_of_service_url="https://staging.mitx.mit.edu/tos",
    ),
]

mitxonline = [
    OpenEdxVars(
        about_us_url="https://rc.mitxonline.mit.edu/about-us/",
        accessibility_url="https://accessibility.mit.edu/",
        account_settings_url="https://rc.mitxonline.mit.edu/account-settings",
        contact_url="https://mitxonline.zendesk.com/hc/en-us/requests/new",
        deployment_name="mitxonline",
        display_feedback_widget="false",
        environment="mitxonline-qa",
        environment_stage="QA",
        favicon_url="https://raw.githubusercontent.com/mitodl/mitxonline-theme/main/lms/static/images/favicon.ico",
        honor_code_url="https://rc.mitxonline.mit.edu/honor-code/",
        lms_domain="courses-qa.mitxonline.mit.edu",
        logo_url="https://raw.githubusercontent.com/mitodl/mitxonline-theme/main/lms/static/images/logo.png",
        marketing_site_domain="rc.mitxonline.mit.edu",
        privacy_policy_url="https://rc.mitxonline.mit.edu/privacy-policy/",
        schedule_email_section="true",  # Because the communication MFE treats this boolean as string  # noqa: E501
        site_name="MITx Online QA",
        studio_domain="studio-qa.mitxonline.mit.edu",
        support_url="mitxonline.zendesk.com/hc/",
        terms_of_service_url="https://rc.mitxonline.mit.edu/terms-of-service/",
        trademark_text="© MITx Online. All rights reserved except where noted.",
    ),
    OpenEdxVars(
        about_us_url="https://mitxonline.mit.edu/about-us/",
        accessibility_url="https://accessibility.mit.edu/",
        account_settings_url="https://mitxonline.mit.edu/account-settings/",
        contact_url="https://mitxonline.zendesk.com/hc/en-us/requests/new",
        deployment_name="mitxonline",
        display_feedback_widget="false",
        environment="mitxonline-production",
        environment_stage="Production",
        favicon_url="https://raw.githubusercontent.com/mitodl/mitxonline-theme/main/lms/static/images/favicon.ico",
        honor_code_url="https://mitxonline.mit.edu/honor-code/",
        lms_domain="courses.mitxonline.mit.edu",
        logo_url="https://raw.githubusercontent.com/mitodl/mitxonline-theme/main/lms/static/images/logo.png",
        marketing_site_domain="mitxonline.mit.edu",
        privacy_policy_url="https://mitxonline.mit.edu/privacy-policy/",
        schedule_email_section="true",  # Because the communication MFE treats this boolean as string  # noqa: E501
        site_name="MITx Online",
        studio_domain="studio.mitxonline.mit.edu",
        support_url="mitxonline.zendesk.com/hc/",
        terms_of_service_url="https://mitxonline.mit.edu/terms-of-service/",
        trademark_text="© MITx Online. All rights reserved except where noted.",
    ),
]

xpro = [
    OpenEdxVars(
        about_us_url="https://ci.xpro.mit.edu/about-us/",
        accessibility_url="https://accessibility.mit.edu/",
        account_settings_url="https://ci.xpro.mit.edu/account-settings/",
        deployment_name="xpro",
        environment="xpro-ci",
        environment_stage="CI",
        favicon_url="https://raw.githubusercontent.com/mitodl/mitxpro-theme/master/lms/static/images/favicon.ico",
        honor_code_url="https://ci.xpro.mit.edu/honor-code/",
        lms_domain="courses-ci.xpro.mit.edu",
        logo_url="https://raw.githubusercontent.com/mitodl/mitxpro-theme/master/lms/static/images/logo.png",
        marketing_site_domain="ci.xpro.mit.edu",
        privacy_policy_url="https://ci.xpro.mit.edu/privacy-policy/",
        site_name="MIT xPRO CI",
        studio_domain="studio-ci.xpro.mit.edu",
        support_url="xpro.zendesk.com/hc",
        terms_of_service_url="https://ci.xpro.mit.edu/terms-of-service/",
        trademark_text="© MIT xPRO. All rights reserved except where noted.",
    ),
    OpenEdxVars(
        about_us_url="https://rc.xpro.mit.edu/about-us/",
        accessibility_url="https://accessibility.mit.edu/",
        account_settings_url="https://rc.xpro.mit.edu/account-settings/",
        deployment_name="xpro",
        environment="xpro-qa",
        environment_stage="QA",
        favicon_url="https://raw.githubusercontent.com/mitodl/mitxpro-theme/master/lms/static/images/favicon.ico",
        honor_code_url="https://rc.xpro.mit.edu/honor-code/",
        lms_domain="courses-rc.xpro.mit.edu",
        logo_url="https://raw.githubusercontent.com/mitodl/mitxpro-theme/master/lms/static/images/logo.png",
        marketing_site_domain="rc.xpro.mit.edu",
        privacy_policy_url="https://rc.xpro.mit.edu/privacy-policy/",
        site_name="MIT xPRO RC",
        studio_domain="studio-rc.xpro.mit.edu",
        support_url="xpro.zendesk.com/hc",
        terms_of_service_url="https://rc.xpro.mit.edu/terms-of-service/",
        trademark_text="© MIT xPRO. All rights reserved except where noted.",
    ),
    OpenEdxVars(
        about_us_url="https://xpro.mit.edu/about-us/",
        accessibility_url="https://accessibility.mit.edu/",
        account_settings_url="https://xpro.mit.edu/account-settings/",
        deployment_name="xpro",
        environment="xpro-production",
        environment_stage="Production",
        favicon_url="https://raw.githubusercontent.com/mitodl/mitxpro-theme/master/lms/static/images/favicon.ico",
        honor_code_url="https://xpro.mit.edu/honor-code/",
        lms_domain="courses.xpro.mit.edu",
        logo_url="https://raw.githubusercontent.com/mitodl/mitxpro-theme/master/lms/static/images/logo.png",
        marketing_site_domain="xpro.mit.edu",
        privacy_policy_url="https://xpro.mit.edu/privacy-policy/",
        site_name="MIT xPRO",
        studio_domain="studio.xpro.mit.edu",
        support_url="xpro.zendesk.com/hc",
        terms_of_service_url="https://xpro.mit.edu/terms-of-service/",
        trademark_text="© MIT xPRO. All rights reserved except where noted.",
    ),
]

deployments: dict[str, list[OpenEdxVars]] = {
    "mitx": mitx,
    "mitx-staging": mitx_staging,
    "mitxonline": mitxonline,
    "xpro": xpro,
}
