baseURL = 'https://pe.ol.mit.edu'
languageCode = 'en-us'
title = 'MIT Online Learning Platform Engineering Site'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

theme = 'hugo-book'
