baseURL = 'https://pe.ol.mit.edu'
languageCode = 'en-us'
title = 'MIT Online Learning Platform Engineering Site'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

theme = 'hugo-book'

# Hugo Book theme
[params]
  BookRepo = "https://github.com/mitodl/ol-infrastructure/pe-handbook"
  BookTheme = "dark"
