#!/usr/bin/env bash
# tutor-reset.sh — wipe every scrap of local-dev Open edX state.
#
# BREAK-GLASS. This deletes every Open edX course, account, enrollment, grade
# and uploaded file. Reach for it when the platform's state has drifted past
# repair — most often stale accounts, because Open edX's user table is the one
# piece of this stack that outlives a `teardown.sh` and has no seed script to
# reconcile it against mitxonline.
#
# Usage:
#   ./local-dev/scripts/tutor-reset.sh [--yes] [--keep-config]
#
# Why a script and not `tutor dev dc down -v`: that command deletes almost
# nothing. In tutor 22 the dev compose project bind-mounts its databases out of
# $(tutor config printroot)/data — the only true volume is mongo's
# /data/configdb — so `down -v` leaves MySQL, MongoDB and the course assets
# exactly where they were. Confirm for yourself with:
#
#     docker inspect tutor_dev-mysql-1 --format '{{range .Mounts}}{{.Type}} {{.Source}}{{"\n"}}{{end}}'
#
# What it removes:
#   1. the `tutor_dev` and `tutor_local` compose projects, containers and volumes
#   2. everything under $(tutor config printroot)/data — the actual state
#   3. $(tutor config printroot)/env, regenerated by the `tutor config save`
#      that tutor-configure.sh runs on the next `tilt up`
#   4. the .ol-local-dev-launched fingerprint, so tutor-up.sh re-runs
#      `tutor dev launch` (migrations + tutor's own OAuth init)
#   5. unless --keep-config: config.yml, which holds the generated secrets AND
#      the enabled-plugin list. Dropping it is how you shake off a stale
#      hand-installed plugin; tutor-configure.sh puts back every host value and
#      re-enables ol_local_dev.
#
# What it deliberately keeps: every Docker image and the BuildKit cache. It has
# to be said plainly that coming back is still slow — `tutor dev launch` builds
# openedx-dev on every run in dev mode, so a reset always pays for a rebuild —
# but the cache makes that minutes rather than the tens of minutes of a cold
# build. Dropping config.yml adds to it: OPENEDX_EXTRA_PIP_REQUIREMENTS is
# regenerated without ol-social-auth, and tutor-configure.sh re-appending it
# invalidates the requirements layer. `--keep-config` avoids that part.
#
# Tilt owns `tutor dev start` (the openedx-tutor resource's serve_cmd), so it
# will restart the platform underneath this script. Disable the resources first
# — the script tells you how and refuses to continue if it sees them come back.
set -euo pipefail

TUTOR="${TUTOR_BIN:-tutor}"
ASSUME_YES=false
KEEP_CONFIG=false

OPENEDX_RESOURCES="openedx-tutor-config openedx-tutor openedx-tutor-seed openedx-tutor-sso"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --yes|-y)      ASSUME_YES=true;  shift ;;
        --keep-config) KEEP_CONFIG=true; shift ;;
        -h|--help)
            echo "Usage: tutor-reset.sh [--yes] [--keep-config]"
            echo ""
            echo "Options:"
            echo "  -y, --yes        Skip the confirmation prompt"
            echo "      --keep-config  Keep config.yml (generated secrets and enabled plugins)"
            echo "  -h, --help       Show this help message"
            exit 0
            ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

log()  { echo "▶ $*"; }
ok()   { echo "  ✓ $*"; }
warn() { echo "  ⚠ $*"; }

# Runs it rather than just looking for it — see the note in tutor-configure.sh.
# Checked before anything is destroyed, so a broken tutor cannot leave the
# platform half-wiped.
"${TUTOR}" --version &>/dev/null || {
    echo "  ✗ '${TUTOR}' is not a working tutor. Set TUTOR_BIN to the real one;" >&2
    echo "    ./local-dev/scripts/tutor-configure.sh explains the options." >&2
    exit 1
}

TUTOR_ROOT=$("${TUTOR}" config printroot)
[[ -n "${TUTOR_ROOT}" && "${TUTOR_ROOT}" != "/" ]] || {
    echo "  ✗ '${TUTOR} config printroot' returned '${TUTOR_ROOT}'; refusing to delete." >&2
    exit 1
}

if ! ${ASSUME_YES}; then
    echo "This deletes EVERY Open edX course, account and enrollment in:"
    echo "    ${TUTOR_ROOT}"
    ${KEEP_CONFIG} || echo "…and config.yml, so its generated secrets and enabled plugins go too."
    echo ""
    read -r -p "Type 'wipe' to continue: " reply
    [[ "${reply}" == "wipe" ]] || { echo "Aborted."; exit 1; }
fi

# ---------------------------------------------------------------------------
# 1. Compose projects. `tutor local` is here because a machine that ran the
#    production-mode stack before this one keeps those containers around
#    forever, holding the same bind mounts open.
# ---------------------------------------------------------------------------
log "Stopping the compose projects"
for mode in dev local; do
    if "${TUTOR}" "${mode}" dc down --remove-orphans -v >/dev/null 2>&1; then
        ok "tutor ${mode}: down"
    else
        # Never launched in this mode, or its compose file is not rendered —
        # nothing to stop either way.
        warn "tutor ${mode}: nothing to stop"
    fi
done

# Tilt restarts openedx-tutor the moment its serve_cmd exits, which would bring
# MySQL back up on top of the directory we are about to delete. Catch that here
# rather than half way through. Asked of docker directly, by compose project
# label: `tutor dev dc ps` prefixes its output with the docker compose command
# line it is about to run, which is never empty and so always looks like a hit.
if docker ps --quiet --filter label=com.docker.compose.project=tutor_dev | grep -q .; then
    echo "  ✗ tutor dev containers are running again — Tilt is restarting them." >&2
    echo "    Hand the platform back first:" >&2
    echo "        tilt disable ${OPENEDX_RESOURCES}" >&2
    echo "    (or stop Tilt: ./local-dev/scripts/stop.sh --keep-running), then re-run this." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# 2. The state itself. These directories belong to the uids the database
#    containers run as, not to the developer, so deleting them from the host
#    needs root. Borrowing a container's root instead of asking for sudo keeps
#    this runnable from a Tilt resource — the same reason prune-docker.sh wipes
#    the registry through a container. Pulls `alpine` if you do not have it.
#
#    The mount is the data directory itself, so a bad TUTOR_ROOT can only
#    destroy what tutor owns. The three globs cover dotfiles, which the plain
#    one misses.
# ---------------------------------------------------------------------------
if [[ -d "${TUTOR_ROOT}/data" ]]; then
    log "Deleting ${TUTOR_ROOT}/data"
    docker run --rm -v "${TUTOR_ROOT}/data:/data" alpine \
        sh -c 'rm -rf /data/* /data/.[!.]* /data/..?* 2>/dev/null; exit 0'
    ok "databases, media and course assets removed"
else
    warn "${TUTOR_ROOT}/data does not exist"
fi

# ---------------------------------------------------------------------------
# 3. Rendered settings and the launch fingerprint. env/ is pure output of
#    `tutor config save`; the fingerprint is what makes tutor-up.sh choose
#    `launch` over `start` (see its LAUNCH_MARKER).
# ---------------------------------------------------------------------------
log "Clearing the rendered environment"
rm -rf "${TUTOR_ROOT}/env"
rm -f "${TUTOR_ROOT}/.ol-local-dev-launched"
ok "env/ and the launch fingerprint removed"

if ${KEEP_CONFIG}; then
    warn "kept config.yml — its enabled plugins still patch the LMS settings."
    warn "  Review them with: ${TUTOR} plugins list"
else
    rm -f "${TUTOR_ROOT}/config.yml"
    ok "config.yml removed (new secrets, and only ol_local_dev re-enabled)"
fi

echo ""
log "Done. Open edX is empty. To bring it back:"
echo "      tilt enable ${OPENEDX_RESOURCES}"
echo "  The first pass re-runs every migration (~10-20 minutes; the openedx-dev"
echo "  image was kept). Courses went with the databases, so re-seed them once"
echo "  the platform is green:"
echo "      tilt trigger seed-courseware"
