"""Slack Bolt async app — all command and action handlers for the release bot."""

import asyncio
import logging
import os
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from functools import partial
from typing import Any

import bot_config as config
import concourse_client as concourse
import github_client as github
import slack_channels
import slack_users
from slack_bolt.adapter.socket_mode.async_handler import AsyncSocketModeHandler
from slack_bolt.async_app import AsyncApp

log = logging.getLogger(__name__)

# Set by create_app(). Background tasks started from a slash command need to
# post to a configured channel rather than reply to the command, because a
# checklist watch outlives the 30-minute window a `respond` URL stays valid.
# A module global is safe here: Socket Mode connections are not multiplexed,
# so this process runs exactly one AsyncApp (see __main__.py's replicas=1).
_slack_app: AsyncApp | None = None


# app name -> Slack user id of whoever last ran `/doof release` for it, so the
# ready-to-promote notification can ping the person who owns the release
# rather than posting into the channel addressed to no one (Doof pinged "the
# Merginator" there). Process-local and deliberately not persisted: a bot
# restart costs one mention, and the message is still posted either way.
_release_requesters: dict[str, str] = {}


# Publishable libraries, and the libraries Doof could publish that have no
# Concourse pipeline. Set by create_app() from the environment. Module globals
# for the same reason as _slack_app: one process, one AsyncApp. They are not
# threaded through the handler signature because `publish` is the only
# subcommand that has anything to do with libraries -- every other one is
# about apps and takes `repos`.
_libraries: dict[str, "config.LibraryConfig"] = {}
_unpublishable_libraries: dict[str, str] = {}


_USAGE = (
    "Usage:\n"
    "• `/doof release <app>` — cut a release\n"
    "• `/doof preview <app>` — show what the next release would contain "
    "(changes nothing)\n"
    "• `/doof release-notes <app>` — show unreleased commits\n"
    "• `/doof release-status [app]` — check release issue status\n"
    "• `/doof wait-for-checkboxes <app>` — watch a release checklist and "
    "report progress\n"
    "• `/doof promote <app>` — promote to production\n"
    "• `/doof publish <library> [package]` — publish a library to PyPI or npm "
    "(no argument lists them)\n"
    "• `/doof abandon <app>` — abandon an in-progress release\n"
)


def _describe_in_flight(in_flight: dict[str, Any]) -> str:
    """Render an in-flight release as a one-line Slack summary."""
    cut_at = in_flight.get("cut_at")
    when = ""
    if cut_at is not None:
        days = (datetime.now(tz=UTC) - cut_at).days
        when = " (cut today)" if days == 0 else f" (cut {days}d ago)"
    return f"<{in_flight['url']}|{in_flight['version']}>{when}"


async def _cmd_release(repos, ack, respond, command, context):
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]

    # Report a release that was cut but never finished. Cutting a new one
    # supersedes it on action=create, so say so rather than letting a branch
    # (and possibly a tag) be deleted silently.
    in_flight = None
    try:
        in_flight = await github.in_flight_release(cfg.repo)
    except Exception:
        log.exception("Failed to check in-flight release for %s", app_name)

    try:
        # The release resource is configured `check_every: never` with no
        # webhook, so Concourse only checks it when explicitly asked.
        # Triggering the build job without this makes the job bind whatever
        # version Concourse last recorded -- the *previous* release -- so the
        # new release reuses its version number and its commit list.
        await concourse.check_resource(cfg.pipeline, f"{app_name}-release")
    except Exception:
        log.exception("Failed to force release resource check for %s", app_name)
        await respond(
            f"❌ Could not refresh the release version for `{app_name}`. "
            "Refusing to trigger — the build would have reused the previous "
            "release's version and commits."
        )
        return

    try:
        # Matches the release-image build job name generated by
        # k8s_apps/pipeline.py's release-resource workflow
        # (_build_release_resource_app_pipeline / _build_release_image_job).
        build_url = await concourse.trigger_job(
            cfg.pipeline, f"build-{app_name}-release-image"
        )
    except Exception:
        log.exception("Failed to trigger release for %s", app_name)
        await respond(f"❌ Failed to trigger release for `{app_name}`. Check logs.")
        return

    requester = (context or {}).get("user_id")
    if requester:
        _release_requesters[app_name] = requester

    message = f"🚀 Release triggered for `{app_name}`. Build: {build_url}"
    if in_flight:
        # The tag is only deleted when that release never reached production;
        # one whose deploy succeeded and whose `finish` failed keeps its tag,
        # since it is the only marker of what production is running.
        message += (
            f"\n⚠️ Superseding in-flight release {_describe_in_flight(in_flight)} — "
            "its release branch will be deleted, and its tag too if it never "
            "reached production."
        )
    await respond(message)


async def _cmd_preview(repos, ack, respond, command, _context):
    """Show what the next release would contain, without triggering anything."""
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]
    try:
        preview = await github.release_preview(cfg.repo)
    except Exception:
        log.exception("Failed to build release preview for %s", app_name)
        await respond(f"❌ Failed to preview a release for `{app_name}`.")
        return

    commits = preview["commits"]
    since = preview["since"] or "the start of history"
    lines = [
        f"*Release preview for `{app_name}`* — next version would be "
        f"`{preview['version']}`",
        f"_{len(commits)} commit(s) since {since}_",
    ]
    if preview["in_flight"]:
        lines.append(
            f"⚠️ In flight: {_describe_in_flight(preview['in_flight'])} — cut but "
            "not finished. Cutting a new release supersedes it."
        )
    if commits:
        lines += [
            f"• `{c['sha'][:8]}` {c['message'].splitlines()[0]} — {c['author']}"
            for c in commits
        ]
    else:
        lines.append("_Nothing to release._")
    lines.append("_Preview only — nothing was triggered._")
    await respond("\n".join(lines))


async def _cmd_release_notes(repos, ack, respond, command, _context):
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]
    try:
        commits = await github.commits_since_last_tag(cfg.repo)
    except Exception:
        log.exception("Failed to fetch release notes for %s", app_name)
        await respond(f"❌ Failed to fetch release notes for `{app_name}`.")
        return
    if not commits:
        await respond(
            f"*Release notes for `{app_name}`*\n_(no commits since last release)_"
        )
        return
    lines = [f"• `{c['sha'][:8]}` {c['message'].splitlines()[0]}" for c in commits]
    await respond(f"*Release notes for `{app_name}`*\n" + "\n".join(lines))


async def _cmd_release_status(repos, ack, respond, command, _context):
    await ack()
    app_filter = command["text"].strip() or None
    if app_filter and app_filter not in repos:
        await respond(f"Unknown app `{app_filter}`. Known apps: {', '.join(repos)}")
        return
    targets = {app_filter: repos[app_filter]} if app_filter else repos
    lines = []
    for name, cfg in targets.items():
        try:
            issues = await github.open_release_issues(cfg.repo)
        except Exception:
            log.exception("Failed to fetch release status for %s", name)
            lines.append(f"• *{name}*: ⚠️ error fetching status")
            continue
        if issues:
            checked, total = github.checklist_status(issues[0]["body"])
            status = f"🟡 {issues[0]['title']} ({checked}/{total} checked)"
        else:
            status = "✅ no open release"
        # A release branch outliving its production deploy means the finish
        # step never completed. That used to be invisible -- and it froze the
        # release version until someone noticed -- so report it here.
        try:
            in_flight = await github.in_flight_release(cfg.repo)
        except Exception:
            log.exception("Failed to fetch in-flight release for %s", name)
            in_flight = None
        if in_flight:
            status += f" · 🚧 in flight: {_describe_in_flight(in_flight)}"
        lines.append(f"• *{name}*: {status}")
    await respond("\n".join(lines))


async def _cmd_promote(repos, ack, respond, command, context):
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]
    try:
        issues = await github.open_release_issues(cfg.repo)
    except Exception:
        log.exception("Failed to fetch release issues for %s", app_name)
        await respond(f"❌ Failed to fetch release issues for `{app_name}`.")
        return
    if not issues:
        await respond(f"No open release issue found for `{app_name}`.")
        return
    user = context["user_id"]
    try:
        await github.close_release_issue(
            cfg.repo,
            issues[0]["number"],
            comment=f"Promoted to Production by <@{user}> via `/doof promote`.",
        )
    except Exception:
        log.exception("Failed to promote %s", app_name)
        await respond(f"❌ Failed to promote `{app_name}`.")
        return
    try:
        # Don't make the deploy wait for the release-gate resource's normal
        # poll interval (default 60m) to notice the issue just closed.
        await concourse.check_resource(cfg.pipeline, f"{app_name}-release-gate")
    except Exception:
        log.exception("Failed to force release-gate check for %s", app_name)
    _release_requesters.pop(app_name, None)
    await respond(
        f"✅ `{app_name}` {issues[0]['title']} promoted. Production deploy triggered."
    )


def _known_libraries() -> str:
    return ", ".join(f"`{name}`" for name in sorted(_libraries)) or "(none configured)"


async def _monorepo_package_job(respond, library: str, cfg, package: str | None):
    """Resolve a monorepo package to its publish job, or explain and return None.

    The packages come from the pipeline's live job list rather than from the
    registry: the publish pipelines discover them by walking the source
    checkout at generation time, so anything written down separately goes
    stale as soon as a package is added to the monorepo.
    """
    try:
        jobs = await concourse.list_jobs(cfg.pipeline, cfg.team)
    except Exception:
        log.exception("Failed to list jobs for %s", cfg.pipeline)
        await respond(
            f"❌ Could not read `{cfg.pipeline}`'s packages from Concourse. Check logs."
        )
        return None

    packages = sorted(
        job.removeprefix(cfg.package_job_prefix)
        for job in jobs
        if job.startswith(cfg.package_job_prefix)
    )
    if not package:
        await respond(
            f"`{library}` is a monorepo — name the package to publish: "
            f"`/doof publish {library} <package>`.\n"
            f"Packages: {', '.join(f'`{p}`' for p in packages)}"
        )
        return None
    if package not in packages:
        await respond(
            f"Unknown package `{package}` in `{library}`.\n"
            f"Packages: {', '.join(f'`{p}`' for p in packages)}"
        )
        return None
    return f"{cfg.package_job_prefix}{package}"


async def _resolve_library(repos, respond, library: str):
    """Return the LibraryConfig for *library*, or explain why there isn't one."""
    if library in _libraries:
        return _libraries[library]

    if library in _unpublishable_libraries:
        # Doof could publish these; Concourse cannot. Saying why beats
        # "unknown", which reads as a typo.
        await respond(
            f"`{library}` is not published from Concourse: "
            f"{_unpublishable_libraries[library]}"
        )
        return None

    # Apps and libraries are separate registries and separate verbs; an app
    # name here is a wrong-verb mistake, not an unknown name.
    hint = (
        f"`{library}` is an app, not a library — use `/doof release {library}`."
        if library in repos
        else f"Unknown library `{library}`."
    )
    await respond(f"{hint} Known libraries: {_known_libraries()}")
    return None


async def _cmd_publish(repos, ack, respond, command, _context):
    await ack()
    library, _, package = command["text"].strip().partition(" ")
    package = package.strip() or None

    if not library:
        await respond(
            f"Usage: `/doof publish <library> [package]`.\n"
            f"Known libraries: {_known_libraries()}"
        )
        return

    cfg = await _resolve_library(repos, respond, library)
    if cfg is None:
        return

    if cfg.package_job_prefix:
        job = await _monorepo_package_job(respond, library, cfg, package)
        if job is None:
            return
    else:
        if package:
            await respond(
                f"`{library}` publishes a single artifact — drop the "
                f"`{package}` argument."
            )
            return
        job = cfg.publish_job

    # A build triggered into a paused pipeline is created and then never
    # scheduled, so reporting its URL would look like success and sit at
    # "pending" forever. Say so instead of triggering.
    try:
        if await concourse.pipeline_is_paused(cfg.pipeline, cfg.team):
            await respond(
                f"⏸️ `{cfg.pipeline}` is paused, so a build would never run. "
                f"Unpause it (`fly -t pr-main unpause-pipeline -p "
                f"{cfg.pipeline}`) and try again."
            )
            return
    except Exception:
        # Not worth blocking a publish on: worst case the user sees a build
        # that never starts, which is where they were before this check.
        log.exception("Failed to read paused state of %s", cfg.pipeline)

    what = f"{library} {package}" if package else library
    try:
        build_url = await concourse.trigger_job(cfg.pipeline, job, cfg.team)
    except Exception:
        log.exception("Failed to trigger publish for %s", what)
        await respond(f"❌ Failed to trigger publish for `{what}`. Check logs.")
        return
    await respond(
        f"📦 Publish to {cfg.registry} triggered for `{what}`. Build: {build_url}"
    )


async def _cmd_abandon(repos, ack, respond, command, _context):
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]
    try:
        build_url = await concourse.trigger_job(
            cfg.pipeline, f"abandon-{app_name}-release"
        )
    except Exception:
        log.exception("Failed to trigger abandon for %s", app_name)
        await respond(f"❌ Failed to trigger release abandon for `{app_name}`.")
        return
    _release_requesters.pop(app_name, None)
    await respond(f"🗑️ Release abandon triggered for `{app_name}`. Build: {build_url}")


async def _handle_promote_button(repos, ack, body, say):
    await ack()
    value = body["actions"][0]["value"]
    app_name, version = value.split(":", 1)
    if app_name not in repos:
        await say(f"⚠️ Unknown app `{app_name}`.")
        return
    cfg = repos[app_name]
    user_id = body["user"]["id"]
    try:
        issues = await github.open_release_issues(cfg.repo)
    except Exception:
        log.exception("Failed to fetch issues for promote button: %s", app_name)
        await say(f"⚠️ Failed to fetch release issues for `{app_name}`.")
        return
    # The issue title is always just "Release {app_name}" -- the version only
    # ever appears in the body's "## Release <version>" header.
    matching = [i for i in issues if github.extract_version(i["body"]) == version]
    if not matching:
        await say(f"⚠️ Could not find open release issue for `{app_name}` `{version}`.")
        return
    try:
        await github.close_release_issue(
            cfg.repo,
            matching[0]["number"],
            comment=f"Promoted to Production by <@{user_id}> via Slack button.",
        )
    except Exception:
        log.exception("Failed to close issue for %s %s", app_name, version)
        await say(f"⚠️ Failed to promote `{app_name}` `{version}`.")
        return
    try:
        # Don't make the deploy wait for the release-gate resource's normal
        # poll interval (default 60m) to notice the issue just closed.
        await concourse.check_resource(cfg.pipeline, f"{app_name}-release-gate")
    except Exception:
        log.exception("Failed to force release-gate check for %s", app_name)
    _release_requesters.pop(app_name, None)
    await say(
        f"🚀 <@{user_id}> promoted `{app_name}` `{version}` to Production. "
        "Concourse deploy triggered."
    )


_CHECKBOX_POLL_SECONDS = 60

# Apps with a checkbox watcher already running, so a second
# `/doof wait-for-checkboxes` for the same app doesn't start a duplicate loop
# posting every progress message twice.
_checkbox_watchers: set[str] = set()


async def _watch_checkboxes(app, app_name, cfg, channel) -> None:
    """Poll a release checklist, reporting each author as they finish.

    Ported from the release-script bot's `wait for checkboxes`: the useful
    part is naming *who* is still outstanding, so the release manager can
    chase them, rather than reporting a bare unchecked count.

    Stops once everything is checked. The final "ready to promote" message and
    its button are left to `_notify_ready_to_promote`, which already covers
    every open release and dedupes on a label -- posting them here as well
    would double up.
    """
    try:
        while True:
            try:
                issues = await github.open_release_issues(cfg.repo)
            except Exception:
                log.exception("Checkbox watch: failed to poll issues for %s", app_name)
                await asyncio.sleep(_CHECKBOX_POLL_SECONDS)
                continue
            if not issues:
                await app.client.chat_postMessage(
                    channel=await slack_channels.resolve(app.client, channel),
                    text=(
                        f"`{app_name}`: no open release issue any more — "
                        "no longer watching checkboxes."
                    ),
                )
                return

            issue = issues[0]
            outstanding = github.unchecked_authors(issue["body"])
            if not outstanding:
                # Stop silently. `_notify_ready_to_promote` polls every open
                # release issue and posts the ready message *with the promote
                # button*, deduped by label -- announcing it here as well would
                # put two ready notifications in the channel, one of them
                # without the button.
                log.info(
                    "Checkbox watch: %s is fully checked; leaving the "
                    "ready-to-promote notification to the poller",
                    app_name,
                )
                return

            await asyncio.sleep(_CHECKBOX_POLL_SECONDS)

            try:
                refreshed = await github.open_release_issues(cfg.repo)
            except Exception:
                log.exception("Checkbox watch: failed to refresh %s", app_name)
                await asyncio.sleep(_CHECKBOX_POLL_SECONDS)
                continue
            if not refreshed:
                await asyncio.sleep(_CHECKBOX_POLL_SECONDS)
                continue
            still_outstanding = github.unchecked_authors(refreshed[0]["body"])
            newly_done = outstanding - still_outstanding
            if newly_done:
                await app.client.chat_postMessage(
                    channel=await slack_channels.resolve(app.client, channel),
                    text=(
                        f"Thanks for checking off your boxes, "
                        f"{await slack_users.format_authors(app.client, newly_done)}!"
                    ),
                )
    finally:
        _checkbox_watchers.discard(app_name)


def _checkbox_watch_preflight(repos, app_name):
    """Return (app, channel, None) if a watcher can start, else (None, None, error).

    The app is handed back rather than re-read from the module global by the
    caller, so the `_slack_app is None` check below is what narrows the type
    for everything downstream.
    """
    if app_name not in repos:
        return None, None, f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}"
    channel = repos[app_name].channel or os.environ.get("RELEASE_ANNOUNCE_CHANNEL")
    if not channel:
        return (
            None,
            None,
            f"No Slack channel configured for `{app_name}`, so there is nowhere "
            "to post checklist progress.",
        )
    if _slack_app is None:
        return None, None, "Bot is still starting up; try again in a moment."
    if app_name in _checkbox_watchers:
        return None, None, f"Already watching `{app_name}`'s release checklist."
    # Reserve the slot here rather than after the GitHub lookup below. Nothing
    # awaits between this check and the add, so it is atomic on the event loop;
    # claiming it later would let two concurrent invocations both pass this
    # check, interleave at open_release_issues, and start duplicate watchers
    # that post every progress message twice.
    _checkbox_watchers.add(app_name)
    return _slack_app, channel, None


async def _cmd_wait_for_checkboxes(repos, ack, respond, command, _context):
    """Watch a release checklist and report who is still outstanding."""
    await ack()
    app_name = command["text"].strip()
    app, channel, error = _checkbox_watch_preflight(repos, app_name)
    if error or app is None:
        await respond(error)
        return
    cfg = repos[app_name]

    try:
        issues = await github.open_release_issues(cfg.repo)
    except Exception:
        log.exception("Failed to fetch release issues for %s", app_name)
        _checkbox_watchers.discard(app_name)
        await respond(f"❌ Failed to fetch release issues for `{app_name}`.")
        return
    if not issues:
        _checkbox_watchers.discard(app_name)
        await respond(f"No open release issue found for `{app_name}`.")
        return

    issue = issues[0]
    outstanding = github.unchecked_authors(issue["body"])
    checked, total = github.checklist_status(issue["body"])
    if not outstanding:
        _checkbox_watchers.discard(app_name)
        await respond(
            f"✅ `{app_name}`: all {total} checkboxes are already checked off. "
            f"<{issue['url']}|Release issue> is ready to promote."
        )
        return

    asyncio.create_task(  # noqa: RUF006
        _watch_checkboxes(app, app_name, cfg, channel)
    )
    await respond(
        f"👀 Watching `{app_name}`'s <{issue['url']}|release checklist> "
        f"({checked}/{total} checked).\n"
        f"Still waiting on: "
        f"{await slack_users.format_authors(app.client, outstanding)}"
    )


_SUBCOMMANDS = {
    "release": _cmd_release,
    "preview": _cmd_preview,
    "release-notes": _cmd_release_notes,
    "release-status": _cmd_release_status,
    "wait-for-checkboxes": _cmd_wait_for_checkboxes,
    "promote": _cmd_promote,
    "publish": _cmd_publish,
    "abandon": _cmd_abandon,
}


def _in_channel(respond):
    """Wrap `respond` so its message posts visibly to the channel.

    Slash command responses are ephemeral (visible only to the invoker) by
    default; release state needs to be visible to the whole team.
    """

    async def wrapped(*args, **kwargs):
        kwargs.setdefault("response_type", "in_channel")
        await respond(*args, **kwargs)

    return wrapped


async def _cmd_doof(repos, ack, respond, command, context):
    parts = command["text"].split(None, 1)
    if not parts or parts[0] not in _SUBCOMMANDS:
        await ack()
        await respond(_USAGE)
        return
    subcommand, *rest = parts
    sub_command = dict(command, text=rest[0] if rest else "")
    await _SUBCOMMANDS[subcommand](
        repos, ack, _in_channel(respond), sub_command, context
    )


def create_app():
    global _slack_app  # noqa: PLW0603
    repos = config.load_repos_config()
    _libraries.update(config.load_libraries_config())
    _unpublishable_libraries.update(config.load_unpublishable_libraries())
    app = AsyncApp(token=os.environ["SLACK_BOT_TOKEN"])
    app.command("/doof")(partial(_cmd_doof, repos))
    app.action("promote_production")(partial(_handle_promote_button, repos))
    _slack_app = app
    return app, repos


_READY_TO_PROMOTE_POLL_SECONDS = 120


def _announce_channel(cfg) -> str | None:
    """Return the Slack channel for proactive posts about *cfg*'s app, if any."""
    return cfg.channel or os.environ.get("RELEASE_ANNOUNCE_CHANNEL")


def _ready_to_promote_blocks(
    app_name: str, version: str, issue_url: str, requester: str | None = None
) -> list[dict[str, object]]:
    cc = f" cc <@{requester}>" if requester else ""
    return [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"✅ *`{app_name}` {version}* — all checklist items are "
                    f"checked off. <{issue_url}|Release issue> ready for "
                    f"promotion.{cc}"
                ),
            },
        },
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "🚀 Promote to Production"},
                    "style": "primary",
                    "action_id": "promote_production",
                    "value": f"{app_name}:{version}",
                }
            ],
        },
    ]


async def _notify_ready_to_promote(app, repos) -> None:
    """Notify Slack for any open release issue whose checklist is now fully checked.

    Marks each notified issue with `github.PROMOTE_READY_LABEL` so repeated
    polls don't re-send the same notification every cycle.
    """
    for app_name, cfg in repos.items():
        channel = _announce_channel(cfg)
        if not channel:
            continue
        try:
            issues = await github.open_release_issues(cfg.repo)
        except Exception:
            log.exception("Failed to poll release issues for %s", app_name)
            continue
        for issue in issues:
            if github.PROMOTE_READY_LABEL in issue["labels"]:
                continue
            if not github.is_fully_checked(issue["body"]):
                continue
            version = github.extract_version(issue["body"])
            if not version:
                # The promote button's value is "{app_name}:{version}", and
                # _handle_promote_button matches it back to an issue via
                # extract_version(issue["body"]). Falling back to the title
                # here (which never contains a version -- it's always just
                # "Release {app_name}") would produce a button that can never
                # find its issue. Skip rather than send a broken button.
                log.warning(
                    "Release issue #%s for %s has no version header; skipping"
                    " ready-to-promote notification",
                    issue["number"],
                    app_name,
                )
                continue
            try:
                await app.client.chat_postMessage(
                    channel=await slack_channels.resolve(app.client, channel),
                    text=f"✅ `{app_name}` {version} is ready to promote.",
                    blocks=_ready_to_promote_blocks(
                        app_name,
                        version,
                        issue["url"],
                        _release_requesters.get(app_name),
                    ),
                )
            except Exception:
                log.exception(
                    "Failed to send ready-to-promote notification for %s", app_name
                )
                continue
            # The mention has been delivered. Dropping it here keeps a failed
            # add_issue_label below -- which leaves the issue eligible on
            # every 120s poll -- from re-pinging the same person on each
            # repeat; the duplicate message is a nuisance, a repeating
            # notification is not.
            _release_requesters.pop(app_name, None)
            try:
                await github.add_issue_label(
                    cfg.repo, issue["number"], github.PROMOTE_READY_LABEL
                )
            except Exception:
                # The notification already went out -- only the "don't repeat
                # this" bookkeeping failed. Log distinctly from a notify
                # failure so the two aren't conflated; worst case this issue
                # gets re-notified next poll cycle, which is a minor nuisance
                # next to silently never notifying at all.
                log.exception(
                    "Sent ready-to-promote notification for %s but failed to"
                    " apply %s label; issue #%s may be re-notified next poll",
                    app_name,
                    github.PROMOTE_READY_LABEL,
                    issue["number"],
                )


async def _poll_ready_to_promote_loop(app, repos) -> None:
    # Check-then-sleep, not sleep-then-check: a release can already be fully
    # checked and waiting at the moment the bot starts (e.g. after a
    # deploy/restart), and sleeping first would delay that notification by up
    # to _READY_TO_PROMOTE_POLL_SECONDS for no reason.
    while True:
        try:
            await _notify_ready_to_promote(app, repos)
        except Exception:
            # Without this, any unexpected exception here kills the
            # background task permanently and silently -- the feature stops
            # working with no log until someone notices and restarts the pod.
            log.exception("ready-to-promote poll iteration failed")
        await asyncio.sleep(_READY_TO_PROMOTE_POLL_SECONDS)


_RELEASE_PROGRESS_POLL_SECONDS = 120
# Doof nagged when a deploy had not landed within a timeout and then repeated
# every 24h; that nag was the only thing in Slack that made a stalled release
# visible. ol-analytics-api's releases/2026.8.3.1 sat cut-but-unfinished from
# 2026-08-03 with no red build and no message anywhere.
_STUCK_RENAG_INTERVAL = timedelta(hours=24)
_DEFAULT_STUCK_AFTER_HOURS = 24.0


def _stuck_release_after() -> timedelta:
    raw = os.environ.get("RELEASE_STUCK_AFTER_HOURS", "").strip()
    if not raw:
        return timedelta(hours=_DEFAULT_STUCK_AFTER_HOURS)
    try:
        return timedelta(hours=float(raw))
    except ValueError:
        log.warning(
            "RELEASE_STUCK_AFTER_HOURS=%r is not a number; using %sh",
            raw,
            _DEFAULT_STUCK_AFTER_HOURS,
        )
        return timedelta(hours=_DEFAULT_STUCK_AFTER_HOURS)


@dataclass
class ReleaseProgressState:
    """What the release-progress poller has already said, held in process.

    `last_deployment` is seeded on first observation rather than starting
    empty, because the poller announces *transitions*: an empty map would
    replay every app's current RC and Production deployment into Slack on
    every bot restart. The cost of seeding is at most one missed announcement,
    when the bot restarts in the window between a deploy landing and the next
    poll -- much cheaper than a release channel that repeats itself, which is
    the failure that makes people mute it.

    `nagged_at` is deliberately not seeded: a stuck release is still stuck
    after a restart, and re-reporting it once is the point.
    """

    # None means "polled and confirmed no successful deployment yet" -- a real
    # baseline, distinct from a (app, environment) pair never having been
    # polled at all (absent from the dict). See _announce_deployments.
    last_deployment: dict[tuple[str, str], int | None] = field(default_factory=dict)
    nagged_at: dict[tuple[str, str], datetime] = field(default_factory=dict)


def _format_age(age: timedelta) -> str:
    hours = int(age.total_seconds() // 3600)
    return f"{hours}h" if hours < 24 else f"{hours // 24}d"  # noqa: PLR2004


async def _milestone_text(app_name, cfg, environment, deployment) -> str:
    """Render the Slack message for a deployment that just reached success."""
    version = deployment["version"]
    issue = None
    try:
        issue = await github.release_issue_for_version(cfg.repo, version)
    except Exception:
        # The milestone still goes out without the link; "what is in this
        # release" is one click worse, not missing.
        log.exception("Failed to find the release issue for %s %s", app_name, version)
    link = f" <{issue['url']}|Release issue>" if issue else ""
    if environment == github.PRODUCTION_ENVIRONMENT:
        return f"🎉 `{app_name}` {version} is live in production.{link}"
    return (
        f"🚢 `{app_name}` {version} is deployed to RC.{link}"
        " Check off your items once you have verified them."
    )


async def _announce_deployments(app, repos, state: ReleaseProgressState) -> None:
    """Post to Slack when an app's RC or Production deployment changes.

    Reads GitHub Deployments rather than watching the cluster: the pipeline
    already records one per environment (`_define_release_resources`), and
    they carry the release version and therefore the release issue, which a
    Kubernetes rollout event does not.

    This does not replace kubewatch-webhook-handler, and does not duplicate it
    either. kubewatch reports *rollouts* -- every workload, including infra
    changes that are not releases -- routed by the `ol.mit.edu/slack-channel`
    pod label, which most workloads do not set, so it lands in the ops
    channel. This reports *releases*, in the product channel from
    bridge.settings.apps, naming the version and linking what is in it. The
    two only collide if a team labels its workload with the same product
    channel; that is a per-workload choice, not something to arbitrate here.
    """
    for app_name, cfg in repos.items():
        channel = _announce_channel(cfg)
        if not channel:
            continue
        for environment in (github.RC_ENVIRONMENT, github.PRODUCTION_ENVIRONMENT):
            try:
                deployment = await github.latest_successful_deployment(
                    cfg.repo, environment
                )
            except Exception:
                log.exception(
                    "Failed to read %s deployments for %s", environment, app_name
                )
                continue
            key = (app_name, environment)
            # Distinguish "never polled this (app, environment)" from "polled
            # it and there was no successful deployment yet" -- both leave
            # `.get(key)` as None, but only the former should suppress the
            # announcement. Collapsing them missed a brand-new app's very
            # first deployment: it would poll None once (recording nothing),
            # then see a real id with no key present and treat that first
            # real deployment as the restart-seed case instead of a genuine
            # no-deployment -> deployed transition.
            first_observation = key not in state.last_deployment
            if deployment is None:
                state.last_deployment.setdefault(key, None)
                continue
            previous = state.last_deployment.get(key)
            state.last_deployment[key] = deployment["id"]
            if first_observation or previous == deployment["id"]:
                # First observation seeds the watcher; an unchanged id is the
                # steady state between releases.
                continue
            try:
                await app.client.chat_postMessage(
                    channel=await slack_channels.resolve(app.client, channel),
                    text=await _milestone_text(app_name, cfg, environment, deployment),
                )
            except Exception:
                log.exception(
                    "Failed to announce the %s deployment of %s", environment, app_name
                )
                # Put the previous id back so the next poll retries this
                # milestone instead of silently treating it as announced.
                state.last_deployment[key] = previous


async def _stuck_release_text(app_name, cfg, in_flight, age: timedelta) -> str:
    version = in_flight["version"]
    reached = set()
    for environment in (github.RC_ENVIRONMENT, github.PRODUCTION_ENVIRONMENT):
        deployment = await github.latest_successful_deployment(cfg.repo, environment)
        if deployment is not None and deployment["version"] == version:
            reached.add(environment)
    if github.PRODUCTION_ENVIRONMENT in reached:
        # The deploy landed and `action: finish` did not. The release branch
        # outliving its production deploy is what freezes the calver counter,
        # so the next release silently reuses this version number.
        state_line = (
            "It reached production but the release never finished, so its "
            "branch is still open and the next release will collide with "
            "this version."
        )
    elif github.RC_ENVIRONMENT in reached:
        state_line = "It is deployed to RC and waiting to be promoted."
    else:
        state_line = "It has not reached RC."
    return (
        f"⏳ `{app_name}` {version} was cut {_format_age(age)} ago and is not "
        f"finished. {state_line} <{in_flight['url']}|{in_flight['branch']}>"
    )


async def _nag_stuck_releases(app, repos, state: ReleaseProgressState) -> None:
    """Report releases that were cut and never shipped."""
    threshold = _stuck_release_after()
    now = datetime.now(tz=UTC)
    for app_name, cfg in repos.items():
        channel = _announce_channel(cfg)
        if not channel:
            continue
        try:
            in_flight = await github.in_flight_release(cfg.repo)
        except Exception:
            log.exception("Failed to check for a stuck release for %s", app_name)
            continue
        if not in_flight or in_flight.get("cut_at") is None:
            continue
        age = now - in_flight["cut_at"]
        if age < threshold:
            continue
        key = (app_name, in_flight["version"])
        last_nag = state.nagged_at.get(key)
        if last_nag is not None and now - last_nag < _STUCK_RENAG_INTERVAL:
            continue
        try:
            text = await _stuck_release_text(app_name, cfg, in_flight, age)
        except Exception:
            log.exception(
                "Failed to describe the stuck release %s for %s",
                in_flight["version"],
                app_name,
            )
            continue
        try:
            await app.client.chat_postMessage(
                channel=await slack_channels.resolve(app.client, channel), text=text
            )
        except Exception:
            log.exception(
                "Failed to report the stuck release %s for %s",
                in_flight["version"],
                app_name,
            )
            continue
        state.nagged_at[key] = now


async def _poll_release_progress_loop(app, repos) -> None:
    state = ReleaseProgressState()
    while True:
        for step, name in (
            (_announce_deployments, "deployment milestone"),
            (_nag_stuck_releases, "stuck release"),
        ):
            try:
                await step(app, repos, state)
            except Exception:
                # Neither step may take the other down, and an unexpected
                # exception here must not kill the task permanently and
                # silently the way an unguarded loop body would.
                log.exception("%s poll iteration failed", name)
        await asyncio.sleep(_RELEASE_PROGRESS_POLL_SECONDS)


async def _report_unreachable_channels(app, repos) -> None:
    """Log configured channels the bot cannot post to, at boot.

    Every proactive message is fire-and-forget inside a poll loop, so a
    channel the bot was never invited to shows up only as a failed post
    buried in the logs hours later. Say it once, at startup, naming the
    channels.
    """
    configured = {
        channel
        for cfg in repos.values()
        if (channel := _announce_channel(cfg)) is not None
    }
    if not configured:
        return
    try:
        missing = await slack_channels.unresolvable(app.client, configured)
    except Exception:
        log.exception("Failed to check configured Slack channels at startup")
        return
    if missing:
        log.error(
            "Cannot resolve %s of %s configured Slack channel(s) to an id: %s."
            " Posts to these will fail with channel_not_found until the bot is"
            " invited to them (private channels are only visible to members)",
            len(missing),
            len(configured),
            ", ".join(missing),
        )


async def main():
    app, repos = create_app()
    await _report_unreachable_channels(app, repos)
    asyncio.create_task(_poll_ready_to_promote_loop(app, repos))  # noqa: RUF006
    asyncio.create_task(_poll_release_progress_loop(app, repos))  # noqa: RUF006
    handler = AsyncSocketModeHandler(app, os.environ["SLACK_APP_TOKEN"])
    await handler.start_async()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(main())
