"""Slack Bolt async app — all command and action handlers for the release bot."""

import asyncio
import logging
import os
from datetime import UTC, datetime
from functools import partial
from typing import Any

import bot_config as config
import concourse_client as concourse
import github_client as github
from slack_bolt.adapter.socket_mode.async_handler import AsyncSocketModeHandler
from slack_bolt.async_app import AsyncApp

log = logging.getLogger(__name__)

# Set by create_app(). Background tasks started from a slash command need to
# post to a configured channel rather than reply to the command, because a
# checklist watch outlives the 30-minute window a `respond` URL stays valid.
# A module global is safe here: Socket Mode connections are not multiplexed,
# so this process runs exactly one AsyncApp (see __main__.py's replicas=1).
_slack_app: AsyncApp | None = None


_USAGE = (
    "Usage:\n"
    "• `/doof release <app>` — cut a release\n"
    "• `/doof preview <app>` — show what the next release would contain "
    "(changes nothing)\n"
    "• `/doof release-notes <app>` — show unreleased commits\n"
    "• `/doof release-status [app]` — check release issue status\n"
    "• `/doof wait-for-checkboxes <app>` — watch a release checklist and "
    "report progress\n"
    "• `/doof promote <app>` — promote to production\n"
    "• `/doof publish <app>` — publish a library\n"
    "• `/doof abandon <app>` — abandon an in-progress release\n"
)


def _describe_in_flight(in_flight: dict[str, Any]) -> str:
    """Render an in-flight release as a one-line Slack summary."""
    cut_at = in_flight.get("cut_at")
    when = ""
    if cut_at is not None:
        days = (datetime.now(tz=UTC) - cut_at).days
        when = " (cut today)" if days == 0 else f" (cut {days}d ago)"
    return f"<{in_flight['url']}|{in_flight['version']}>{when}"


async def _cmd_release(repos, ack, respond, command, _context):
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]

    # Report a release that was cut but never finished. Cutting a new one
    # supersedes it on action=create, so say so rather than letting a branch
    # (and possibly a tag) be deleted silently.
    in_flight = None
    try:
        in_flight = await github.in_flight_release(cfg.repo)
    except Exception:
        log.exception("Failed to check in-flight release for %s", app_name)

    try:
        # The release resource is configured `check_every: never` with no
        # webhook, so Concourse only checks it when explicitly asked.
        # Triggering the build job without this makes the job bind whatever
        # version Concourse last recorded -- the *previous* release -- so the
        # new release reuses its version number and its commit list.
        await concourse.check_resource(cfg.pipeline, f"{app_name}-release")
    except Exception:
        log.exception("Failed to force release resource check for %s", app_name)
        await respond(
            f"❌ Could not refresh the release version for `{app_name}`. "
            "Refusing to trigger — the build would have reused the previous "
            "release's version and commits."
        )
        return

    try:
        # Matches the release-image build job name generated by
        # k8s_apps/pipeline.py's release-resource workflow
        # (_build_release_resource_app_pipeline / _build_release_image_job).
        build_url = await concourse.trigger_job(
            cfg.pipeline, f"build-{app_name}-release-image"
        )
    except Exception:
        log.exception("Failed to trigger release for %s", app_name)
        await respond(f"❌ Failed to trigger release for `{app_name}`. Check logs.")
        return

    message = f"🚀 Release triggered for `{app_name}`. Build: {build_url}"
    if in_flight:
        # The tag is only deleted when that release never reached production;
        # one whose deploy succeeded and whose `finish` failed keeps its tag,
        # since it is the only marker of what production is running.
        message += (
            f"\n⚠️ Superseding in-flight release {_describe_in_flight(in_flight)} — "
            "its release branch will be deleted, and its tag too if it never "
            "reached production."
        )
    await respond(message)


async def _cmd_preview(repos, ack, respond, command, _context):
    """Show what the next release would contain, without triggering anything."""
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]
    try:
        preview = await github.release_preview(cfg.repo)
    except Exception:
        log.exception("Failed to build release preview for %s", app_name)
        await respond(f"❌ Failed to preview a release for `{app_name}`.")
        return

    commits = preview["commits"]
    since = preview["since"] or "the start of history"
    lines = [
        f"*Release preview for `{app_name}`* — next version would be "
        f"`{preview['version']}`",
        f"_{len(commits)} commit(s) since {since}_",
    ]
    if preview["in_flight"]:
        lines.append(
            f"⚠️ In flight: {_describe_in_flight(preview['in_flight'])} — cut but "
            "not finished. Cutting a new release supersedes it."
        )
    if commits:
        lines += [
            f"• `{c['sha'][:8]}` {c['message'].splitlines()[0]} — {c['author']}"
            for c in commits
        ]
    else:
        lines.append("_Nothing to release._")
    lines.append("_Preview only — nothing was triggered._")
    await respond("\n".join(lines))


async def _cmd_release_notes(repos, ack, respond, command, _context):
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]
    try:
        commits = await github.commits_since_last_tag(cfg.repo)
    except Exception:
        log.exception("Failed to fetch release notes for %s", app_name)
        await respond(f"❌ Failed to fetch release notes for `{app_name}`.")
        return
    if not commits:
        await respond(
            f"*Release notes for `{app_name}`*\n_(no commits since last release)_"
        )
        return
    lines = [f"• `{c['sha'][:8]}` {c['message'].splitlines()[0]}" for c in commits]
    await respond(f"*Release notes for `{app_name}`*\n" + "\n".join(lines))


async def _cmd_release_status(repos, ack, respond, command, _context):
    await ack()
    app_filter = command["text"].strip() or None
    if app_filter and app_filter not in repos:
        await respond(f"Unknown app `{app_filter}`. Known apps: {', '.join(repos)}")
        return
    targets = {app_filter: repos[app_filter]} if app_filter else repos
    lines = []
    for name, cfg in targets.items():
        try:
            issues = await github.open_release_issues(cfg.repo)
        except Exception:
            log.exception("Failed to fetch release status for %s", name)
            lines.append(f"• *{name}*: ⚠️ error fetching status")
            continue
        if issues:
            checked, total = github.checklist_status(issues[0]["body"])
            status = f"🟡 {issues[0]['title']} ({checked}/{total} checked)"
        else:
            status = "✅ no open release"
        # A release branch outliving its production deploy means the finish
        # step never completed. That used to be invisible -- and it froze the
        # release version until someone noticed -- so report it here.
        try:
            in_flight = await github.in_flight_release(cfg.repo)
        except Exception:
            log.exception("Failed to fetch in-flight release for %s", name)
            in_flight = None
        if in_flight:
            status += f" · 🚧 in flight: {_describe_in_flight(in_flight)}"
        lines.append(f"• *{name}*: {status}")
    await respond("\n".join(lines))


async def _cmd_promote(repos, ack, respond, command, context):
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]
    try:
        issues = await github.open_release_issues(cfg.repo)
    except Exception:
        log.exception("Failed to fetch release issues for %s", app_name)
        await respond(f"❌ Failed to fetch release issues for `{app_name}`.")
        return
    if not issues:
        await respond(f"No open release issue found for `{app_name}`.")
        return
    user = context["user_id"]
    try:
        await github.close_release_issue(
            cfg.repo,
            issues[0]["number"],
            comment=f"Promoted to Production by <@{user}> via `/doof promote`.",
        )
    except Exception:
        log.exception("Failed to promote %s", app_name)
        await respond(f"❌ Failed to promote `{app_name}`.")
        return
    try:
        # Don't make the deploy wait for the release-gate resource's normal
        # poll interval (default 60m) to notice the issue just closed.
        await concourse.check_resource(cfg.pipeline, f"{app_name}-release-gate")
    except Exception:
        log.exception("Failed to force release-gate check for %s", app_name)
    await respond(
        f"✅ `{app_name}` {issues[0]['title']} promoted. Production deploy triggered."
    )


async def _cmd_publish(repos, ack, respond, command, _context):
    await ack()
    library = command["text"].strip()
    if library not in repos:
        await respond(f"Unknown library `{library}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[library]
    try:
        build_url = await concourse.trigger_job(cfg.pipeline, "publish")
    except Exception:
        log.exception("Failed to trigger publish for %s", library)
        await respond(f"❌ Failed to trigger publish for `{library}`.")
        return
    await respond(f"📦 Publish triggered for `{library}`. Build: {build_url}")


async def _cmd_abandon(repos, ack, respond, command, _context):
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]
    try:
        build_url = await concourse.trigger_job(
            cfg.pipeline, f"abandon-{app_name}-release"
        )
    except Exception:
        log.exception("Failed to trigger abandon for %s", app_name)
        await respond(f"❌ Failed to trigger release abandon for `{app_name}`.")
        return
    await respond(f"🗑️ Release abandon triggered for `{app_name}`. Build: {build_url}")


async def _handle_promote_button(repos, ack, body, say):
    await ack()
    value = body["actions"][0]["value"]
    app_name, version = value.split(":", 1)
    if app_name not in repos:
        await say(f"⚠️ Unknown app `{app_name}`.")
        return
    cfg = repos[app_name]
    user_id = body["user"]["id"]
    try:
        issues = await github.open_release_issues(cfg.repo)
    except Exception:
        log.exception("Failed to fetch issues for promote button: %s", app_name)
        await say(f"⚠️ Failed to fetch release issues for `{app_name}`.")
        return
    # The issue title is always just "Release {app_name}" -- the version only
    # ever appears in the body's "## Release <version>" header.
    matching = [i for i in issues if github.extract_version(i["body"]) == version]
    if not matching:
        await say(f"⚠️ Could not find open release issue for `{app_name}` `{version}`.")
        return
    try:
        await github.close_release_issue(
            cfg.repo,
            matching[0]["number"],
            comment=f"Promoted to Production by <@{user_id}> via Slack button.",
        )
    except Exception:
        log.exception("Failed to close issue for %s %s", app_name, version)
        await say(f"⚠️ Failed to promote `{app_name}` `{version}`.")
        return
    try:
        # Don't make the deploy wait for the release-gate resource's normal
        # poll interval (default 60m) to notice the issue just closed.
        await concourse.check_resource(cfg.pipeline, f"{app_name}-release-gate")
    except Exception:
        log.exception("Failed to force release-gate check for %s", app_name)
    await say(
        f"🚀 <@{user_id}> promoted `{app_name}` `{version}` to Production. "
        "Concourse deploy triggered."
    )


_CHECKBOX_POLL_SECONDS = 60

# Apps with a checkbox watcher already running, so a second
# `/doof wait-for-checkboxes` for the same app doesn't start a duplicate loop
# posting every progress message twice.
_checkbox_watchers: set[str] = set()


def _format_authors(authors) -> str:
    return ", ".join(sorted(authors))


async def _watch_checkboxes(app, app_name, cfg, channel) -> None:
    """Poll a release checklist, reporting each author as they finish.

    Ported from the release-script bot's `wait for checkboxes`: the useful
    part is naming *who* is still outstanding, so the release manager can
    chase them, rather than reporting a bare unchecked count.

    Stops once everything is checked. The final "ready to promote" message and
    its button are left to `_notify_ready_to_promote`, which already covers
    every open release and dedupes on a label -- posting them here as well
    would double up.
    """
    try:
        while True:
            try:
                issues = await github.open_release_issues(cfg.repo)
            except Exception:
                log.exception("Checkbox watch: failed to poll issues for %s", app_name)
                await asyncio.sleep(_CHECKBOX_POLL_SECONDS)
                continue
            if not issues:
                await app.client.chat_postMessage(
                    channel=channel,
                    text=(
                        f"`{app_name}`: no open release issue any more — "
                        "no longer watching checkboxes."
                    ),
                )
                return

            issue = issues[0]
            outstanding = github.unchecked_authors(issue["body"])
            if not outstanding:
                await app.client.chat_postMessage(
                    channel=channel,
                    text=(
                        f"✅ `{app_name}`: all checkboxes are checked off. "
                        f"<{issue['url']}|Release issue> is ready to promote."
                    ),
                )
                return

            await asyncio.sleep(_CHECKBOX_POLL_SECONDS)

            try:
                refreshed = await github.open_release_issues(cfg.repo)
            except Exception:
                log.exception("Checkbox watch: failed to refresh %s", app_name)
                continue
            if not refreshed:
                continue
            still_outstanding = github.unchecked_authors(refreshed[0]["body"])
            newly_done = outstanding - still_outstanding
            if newly_done:
                await app.client.chat_postMessage(
                    channel=channel,
                    text=(
                        f"Thanks for checking off your boxes, "
                        f"{_format_authors(newly_done)}!"
                    ),
                )
    finally:
        _checkbox_watchers.discard(app_name)


def _checkbox_watch_preflight(repos, app_name):
    """Return (channel, None) if a watcher can start, else (None, error message)."""
    if app_name not in repos:
        return None, f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}"
    channel = repos[app_name].channel or os.environ.get("RELEASE_ANNOUNCE_CHANNEL")
    if not channel:
        return None, (
            f"No Slack channel configured for `{app_name}`, so there is nowhere "
            "to post checklist progress."
        )
    if app_name in _checkbox_watchers:
        return None, f"Already watching `{app_name}`'s release checklist."
    if _slack_app is None:
        return None, "Bot is still starting up; try again in a moment."
    return channel, None


async def _cmd_wait_for_checkboxes(repos, ack, respond, command, _context):
    """Watch a release checklist and report who is still outstanding."""
    await ack()
    app_name = command["text"].strip()
    channel, error = _checkbox_watch_preflight(repos, app_name)
    if error:
        await respond(error)
        return
    cfg = repos[app_name]

    try:
        issues = await github.open_release_issues(cfg.repo)
    except Exception:
        log.exception("Failed to fetch release issues for %s", app_name)
        await respond(f"❌ Failed to fetch release issues for `{app_name}`.")
        return
    if not issues:
        await respond(f"No open release issue found for `{app_name}`.")
        return

    issue = issues[0]
    outstanding = github.unchecked_authors(issue["body"])
    checked, total = github.checklist_status(issue["body"])
    if not outstanding:
        await respond(
            f"✅ `{app_name}`: all {total} checkboxes are already checked off. "
            f"<{issue['url']}|Release issue> is ready to promote."
        )
        return

    _checkbox_watchers.add(app_name)
    asyncio.create_task(  # noqa: RUF006
        _watch_checkboxes(_slack_app, app_name, cfg, channel)
    )
    await respond(
        f"👀 Watching `{app_name}`'s <{issue['url']}|release checklist> "
        f"({checked}/{total} checked).\n"
        f"Still waiting on: {_format_authors(outstanding)}"
    )


_SUBCOMMANDS = {
    "release": _cmd_release,
    "preview": _cmd_preview,
    "release-notes": _cmd_release_notes,
    "release-status": _cmd_release_status,
    "wait-for-checkboxes": _cmd_wait_for_checkboxes,
    "promote": _cmd_promote,
    "publish": _cmd_publish,
    "abandon": _cmd_abandon,
}


def _in_channel(respond):
    """Wrap `respond` so its message posts visibly to the channel.

    Slash command responses are ephemeral (visible only to the invoker) by
    default; release state needs to be visible to the whole team.
    """

    async def wrapped(*args, **kwargs):
        kwargs.setdefault("response_type", "in_channel")
        await respond(*args, **kwargs)

    return wrapped


async def _cmd_doof(repos, ack, respond, command, context):
    parts = command["text"].split(None, 1)
    if not parts or parts[0] not in _SUBCOMMANDS:
        await ack()
        await respond(_USAGE)
        return
    subcommand, *rest = parts
    sub_command = dict(command, text=rest[0] if rest else "")
    await _SUBCOMMANDS[subcommand](
        repos, ack, _in_channel(respond), sub_command, context
    )


def create_app():
    global _slack_app  # noqa: PLW0603
    repos = config.load_repos_config()
    app = AsyncApp(token=os.environ["SLACK_BOT_TOKEN"])
    app.command("/doof")(partial(_cmd_doof, repos))
    app.action("promote_production")(partial(_handle_promote_button, repos))
    _slack_app = app
    return app, repos


_READY_TO_PROMOTE_POLL_SECONDS = 120


def _ready_to_promote_blocks(
    app_name: str, version: str, issue_url: str
) -> list[dict[str, object]]:
    return [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"✅ *`{app_name}` {version}* — all checklist items are "
                    f"checked off. <{issue_url}|Release issue> ready for promotion."
                ),
            },
        },
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "🚀 Promote to Production"},
                    "style": "primary",
                    "action_id": "promote_production",
                    "value": f"{app_name}:{version}",
                }
            ],
        },
    ]


async def _notify_ready_to_promote(app, repos) -> None:
    """Notify Slack for any open release issue whose checklist is now fully checked.

    Marks each notified issue with `github.PROMOTE_READY_LABEL` so repeated
    polls don't re-send the same notification every cycle.
    """
    for app_name, cfg in repos.items():
        channel = cfg.channel or os.environ.get("RELEASE_ANNOUNCE_CHANNEL")
        if not channel:
            continue
        try:
            issues = await github.open_release_issues(cfg.repo)
        except Exception:
            log.exception("Failed to poll release issues for %s", app_name)
            continue
        for issue in issues:
            if github.PROMOTE_READY_LABEL in issue["labels"]:
                continue
            if not github.is_fully_checked(issue["body"]):
                continue
            version = github.extract_version(issue["body"])
            if not version:
                # The promote button's value is "{app_name}:{version}", and
                # _handle_promote_button matches it back to an issue via
                # extract_version(issue["body"]). Falling back to the title
                # here (which never contains a version -- it's always just
                # "Release {app_name}") would produce a button that can never
                # find its issue. Skip rather than send a broken button.
                log.warning(
                    "Release issue #%s for %s has no version header; skipping"
                    " ready-to-promote notification",
                    issue["number"],
                    app_name,
                )
                continue
            try:
                await app.client.chat_postMessage(
                    channel=channel,
                    text=f"✅ `{app_name}` {version} is ready to promote.",
                    blocks=_ready_to_promote_blocks(app_name, version, issue["url"]),
                )
            except Exception:
                log.exception(
                    "Failed to send ready-to-promote notification for %s", app_name
                )
                continue
            try:
                await github.add_issue_label(
                    cfg.repo, issue["number"], github.PROMOTE_READY_LABEL
                )
            except Exception:
                # The notification already went out -- only the "don't repeat
                # this" bookkeeping failed. Log distinctly from a notify
                # failure so the two aren't conflated; worst case this issue
                # gets re-notified next poll cycle, which is a minor nuisance
                # next to silently never notifying at all.
                log.exception(
                    "Sent ready-to-promote notification for %s but failed to"
                    " apply %s label; issue #%s may be re-notified next poll",
                    app_name,
                    github.PROMOTE_READY_LABEL,
                    issue["number"],
                )


async def _poll_ready_to_promote_loop(app, repos) -> None:
    # Check-then-sleep, not sleep-then-check: a release can already be fully
    # checked and waiting at the moment the bot starts (e.g. after a
    # deploy/restart), and sleeping first would delay that notification by up
    # to _READY_TO_PROMOTE_POLL_SECONDS for no reason.
    while True:
        try:
            await _notify_ready_to_promote(app, repos)
        except Exception:
            # Without this, any unexpected exception here kills the
            # background task permanently and silently -- the feature stops
            # working with no log until someone notices and restarts the pod.
            log.exception("ready-to-promote poll iteration failed")
        await asyncio.sleep(_READY_TO_PROMOTE_POLL_SECONDS)


async def main():
    app, repos = create_app()
    asyncio.create_task(_poll_ready_to_promote_loop(app, repos))  # noqa: RUF006
    handler = AsyncSocketModeHandler(app, os.environ["SLACK_APP_TOKEN"])
    await handler.start_async()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(main())
