"""Slack Bolt async app — all command and action handlers for the release bot."""

import asyncio
import logging
import os
from functools import partial

import bot_config as config
import concourse_client as concourse
import github_client as github
from slack_bolt.adapter.socket_mode.async_handler import AsyncSocketModeHandler
from slack_bolt.async_app import AsyncApp

log = logging.getLogger(__name__)


_USAGE = (
    "Usage:\n"
    "• `/doof release <app>` — cut a release\n"
    "• `/doof release-notes <app>` — show unreleased commits\n"
    "• `/doof release-status [app]` — check release issue status\n"
    "• `/doof promote <app>` — promote to production\n"
    "• `/doof publish <app>` — publish a library\n"
    "• `/doof abandon <app>` — abandon an in-progress release\n"
)


async def _cmd_release(repos, ack, respond, command, _context):
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]
    try:
        # Matches the release-image build job name generated by
        # k8s_apps/pipeline.py's release-resource workflow
        # (_build_release_resource_app_pipeline / _build_release_image_job).
        build_url = await concourse.trigger_job(
            cfg.pipeline, f"build-{app_name}-release-image"
        )
    except Exception:
        log.exception("Failed to trigger release for %s", app_name)
        await respond(f"❌ Failed to trigger release for `{app_name}`. Check logs.")
        return
    await respond(f"🚀 Release triggered for `{app_name}`. Build: {build_url}")


async def _cmd_release_notes(repos, ack, respond, command, _context):
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]
    try:
        commits = await github.commits_since_last_tag(cfg.repo)
    except Exception:
        log.exception("Failed to fetch release notes for %s", app_name)
        await respond(f"❌ Failed to fetch release notes for `{app_name}`.")
        return
    if not commits:
        await respond(
            f"*Release notes for `{app_name}`*\n_(no commits since last release)_"
        )
        return
    lines = [f"• `{c['sha'][:8]}` {c['message'].splitlines()[0]}" for c in commits]
    await respond(f"*Release notes for `{app_name}`*\n" + "\n".join(lines))


async def _cmd_release_status(repos, ack, respond, command, _context):
    await ack()
    app_filter = command["text"].strip() or None
    if app_filter and app_filter not in repos:
        await respond(f"Unknown app `{app_filter}`. Known apps: {', '.join(repos)}")
        return
    targets = {app_filter: repos[app_filter]} if app_filter else repos
    lines = []
    for name, cfg in targets.items():
        try:
            issues = await github.open_release_issues(cfg.repo)
        except Exception:
            log.exception("Failed to fetch release status for %s", name)
            lines.append(f"• *{name}*: ⚠️ error fetching status")
            continue
        status = f"🟡 {issues[0]['title']}" if issues else "✅ no open release"
        lines.append(f"• *{name}*: {status}")
    await respond("\n".join(lines))


async def _cmd_promote(repos, ack, respond, command, context):
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]
    try:
        issues = await github.open_release_issues(cfg.repo)
    except Exception:
        log.exception("Failed to fetch release issues for %s", app_name)
        await respond(f"❌ Failed to fetch release issues for `{app_name}`.")
        return
    if not issues:
        await respond(f"No open release issue found for `{app_name}`.")
        return
    user = context["user_id"]
    try:
        await github.close_release_issue(
            cfg.repo,
            issues[0]["number"],
            comment=f"Promoted to Production by <@{user}> via `/doof promote`.",
        )
    except Exception:
        log.exception("Failed to promote %s", app_name)
        await respond(f"❌ Failed to promote `{app_name}`.")
        return
    try:
        # Don't make the deploy wait for the release-gate resource's normal
        # poll interval (default 60m) to notice the issue just closed.
        await concourse.check_resource(cfg.pipeline, f"{app_name}-release-gate")
    except Exception:
        log.exception("Failed to force release-gate check for %s", app_name)
    await respond(
        f"✅ `{app_name}` {issues[0]['title']} promoted. Production deploy triggered."
    )


async def _cmd_publish(repos, ack, respond, command, _context):
    await ack()
    library = command["text"].strip()
    if library not in repos:
        await respond(f"Unknown library `{library}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[library]
    try:
        build_url = await concourse.trigger_job(cfg.pipeline, "publish")
    except Exception:
        log.exception("Failed to trigger publish for %s", library)
        await respond(f"❌ Failed to trigger publish for `{library}`.")
        return
    await respond(f"📦 Publish triggered for `{library}`. Build: {build_url}")


async def _cmd_abandon(repos, ack, respond, command, _context):
    await ack()
    app_name = command["text"].strip()
    if app_name not in repos:
        await respond(f"Unknown app `{app_name}`. Known apps: {', '.join(repos)}")
        return
    cfg = repos[app_name]
    try:
        build_url = await concourse.trigger_job(
            cfg.pipeline, f"abandon-{app_name}-release"
        )
    except Exception:
        log.exception("Failed to trigger abandon for %s", app_name)
        await respond(f"❌ Failed to trigger release abandon for `{app_name}`.")
        return
    await respond(f"🗑️ Release abandon triggered for `{app_name}`. Build: {build_url}")


async def _handle_promote_button(repos, ack, body, say):
    await ack()
    value = body["actions"][0]["value"]
    app_name, version = value.split(":", 1)
    if app_name not in repos:
        await say(f"⚠️ Unknown app `{app_name}`.")
        return
    cfg = repos[app_name]
    user_id = body["user"]["id"]
    try:
        issues = await github.open_release_issues(cfg.repo)
    except Exception:
        log.exception("Failed to fetch issues for promote button: %s", app_name)
        await say(f"⚠️ Failed to fetch release issues for `{app_name}`.")
        return
    # The issue title is always just "Release {app_name}" -- the version only
    # ever appears in the body's "## Release <version>" header.
    matching = [i for i in issues if github.extract_version(i["body"]) == version]
    if not matching:
        await say(f"⚠️ Could not find open release issue for `{app_name}` `{version}`.")
        return
    try:
        await github.close_release_issue(
            cfg.repo,
            matching[0]["number"],
            comment=f"Promoted to Production by <@{user_id}> via Slack button.",
        )
    except Exception:
        log.exception("Failed to close issue for %s %s", app_name, version)
        await say(f"⚠️ Failed to promote `{app_name}` `{version}`.")
        return
    try:
        # Don't make the deploy wait for the release-gate resource's normal
        # poll interval (default 60m) to notice the issue just closed.
        await concourse.check_resource(cfg.pipeline, f"{app_name}-release-gate")
    except Exception:
        log.exception("Failed to force release-gate check for %s", app_name)
    await say(
        f"🚀 <@{user_id}> promoted `{app_name}` `{version}` to Production. "
        "Concourse deploy triggered."
    )


_SUBCOMMANDS = {
    "release": _cmd_release,
    "release-notes": _cmd_release_notes,
    "release-status": _cmd_release_status,
    "promote": _cmd_promote,
    "publish": _cmd_publish,
    "abandon": _cmd_abandon,
}


def _in_channel(respond):
    """Wrap `respond` so its message posts visibly to the channel.

    Slash command responses are ephemeral (visible only to the invoker) by
    default; release state needs to be visible to the whole team.
    """

    async def wrapped(*args, **kwargs):
        kwargs.setdefault("response_type", "in_channel")
        await respond(*args, **kwargs)

    return wrapped


async def _cmd_doof(repos, ack, respond, command, context):
    parts = command["text"].split(None, 1)
    if not parts or parts[0] not in _SUBCOMMANDS:
        await ack()
        await respond(_USAGE)
        return
    subcommand, *rest = parts
    sub_command = dict(command, text=rest[0] if rest else "")
    await _SUBCOMMANDS[subcommand](
        repos, ack, _in_channel(respond), sub_command, context
    )


def create_app():
    repos = config.load_repos_config()
    app = AsyncApp(token=os.environ["SLACK_BOT_TOKEN"])
    app.command("/doof")(partial(_cmd_doof, repos))
    app.action("promote_production")(partial(_handle_promote_button, repos))
    return app, repos


_READY_TO_PROMOTE_POLL_SECONDS = 120


def _ready_to_promote_blocks(
    app_name: str, version: str, issue_url: str
) -> list[dict[str, object]]:
    return [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"✅ *`{app_name}` {version}* — all checklist items are "
                    f"checked off. <{issue_url}|Release issue> ready for promotion."
                ),
            },
        },
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "🚀 Promote to Production"},
                    "style": "primary",
                    "action_id": "promote_production",
                    "value": f"{app_name}:{version}",
                }
            ],
        },
    ]


async def _notify_ready_to_promote(app, repos) -> None:
    """Notify Slack for any open release issue whose checklist is now fully checked.

    Marks each notified issue with `github.PROMOTE_READY_LABEL` so repeated
    polls don't re-send the same notification every cycle.
    """
    for app_name, cfg in repos.items():
        channel = cfg.channel or os.environ.get("RELEASE_ANNOUNCE_CHANNEL")
        if not channel:
            continue
        try:
            issues = await github.open_release_issues(cfg.repo)
        except Exception:
            log.exception("Failed to poll release issues for %s", app_name)
            continue
        for issue in issues:
            if github.PROMOTE_READY_LABEL in issue["labels"]:
                continue
            if not github.is_fully_checked(issue["body"]):
                continue
            version = github.extract_version(issue["body"]) or issue["title"]
            try:
                await app.client.chat_postMessage(
                    channel=channel,
                    text=f"✅ `{app_name}` {version} is ready to promote.",
                    blocks=_ready_to_promote_blocks(app_name, version, issue["url"]),
                )
                await github.add_issue_label(
                    cfg.repo, issue["number"], github.PROMOTE_READY_LABEL
                )
            except Exception:
                log.exception(
                    "Failed to send ready-to-promote notification for %s", app_name
                )


async def _poll_ready_to_promote_loop(app, repos) -> None:
    while True:
        await asyncio.sleep(_READY_TO_PROMOTE_POLL_SECONDS)
        await _notify_ready_to_promote(app, repos)


async def main():
    app, repos = create_app()
    asyncio.create_task(_poll_ready_to_promote_loop(app, repos))  # noqa: RUF006
    handler = AsyncSocketModeHandler(app, os.environ["SLACK_APP_TOKEN"])
    await handler.start_async()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(main())
