# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass

import types

__config__ = pulumi.Config("qdrant-cloud")


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def account_id(self) -> str | None:
        """
        Default Account Identifier for the Qdrant cloud
        """
        return __config__.get("accountId")

    @_builtins.property
    def api_key(self) -> str | None:
        """
        The API Key for Qdrant Cloud API operations.
        """
        return __config__.get("apiKey")

    @_builtins.property
    def api_url(self) -> str | None:
        """
        The URL of the Qdrant Cloud API.
        """
        return __config__.get("apiUrl")

    @_builtins.property
    def insecure(self) -> bool | None:
        """
        Allow insecure gRPC connections. This is useful for development environments with self-signed certificates. Defaults to false.
        """
        return __config__.get_bool("insecure")
