# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
from typing import overload

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass
from . import _utilities

__all__ = ["AccountsBackupSchedule", "AccountsBackupScheduleArgs"]


@pulumi.input_type
class AccountsBackupScheduleArgs:
    def __init__(
        __self__,
        *,
        cluster_id: pulumi.Input[_builtins.str],
        cron_expression: pulumi.Input[_builtins.str],
        account_id: pulumi.Input[_builtins.str] | None = None,
        delete_backups_on_destroy: pulumi.Input[_builtins.bool] | None = None,
        retention_period: pulumi.Input[_builtins.str] | None = None,
    ):
        """
        The set of arguments for constructing a AccountsBackupSchedule resource.

        :param pulumi.Input[_builtins.str] cluster_id: Backup Schedule Schema Cluster ID field
        :param pulumi.Input[_builtins.str] cron_expression: Backup Schedule Schema Cron expression for the schedule field
        :param pulumi.Input[_builtins.str] account_id: Backup Schedule Schema Account ID field
        :param pulumi.Input[_builtins.bool] delete_backups_on_destroy: Whether to delete backups when the schedule is destroyed.
        :param pulumi.Input[_builtins.str] retention_period: Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
        """
        pulumi.set(__self__, "cluster_id", cluster_id)
        pulumi.set(__self__, "cron_expression", cron_expression)
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if delete_backups_on_destroy is not None:
            pulumi.set(__self__, "delete_backups_on_destroy", delete_backups_on_destroy)
        if retention_period is not None:
            pulumi.set(__self__, "retention_period", retention_period)

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> pulumi.Input[_builtins.str]:
        """
        Backup Schedule Schema Cluster ID field
        """
        return pulumi.get(self, "cluster_id")

    @cluster_id.setter
    def cluster_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cluster_id", value)

    @_builtins.property
    @pulumi.getter(name="cronExpression")
    def cron_expression(self) -> pulumi.Input[_builtins.str]:
        """
        Backup Schedule Schema Cron expression for the schedule field
        """
        return pulumi.get(self, "cron_expression")

    @cron_expression.setter
    def cron_expression(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cron_expression", value)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Input[_builtins.str] | None:
        """
        Backup Schedule Schema Account ID field
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="deleteBackupsOnDestroy")
    def delete_backups_on_destroy(self) -> pulumi.Input[_builtins.bool] | None:
        """
        Whether to delete backups when the schedule is destroyed.
        """
        return pulumi.get(self, "delete_backups_on_destroy")

    @delete_backups_on_destroy.setter
    def delete_backups_on_destroy(self, value: pulumi.Input[_builtins.bool] | None):
        pulumi.set(self, "delete_backups_on_destroy", value)

    @_builtins.property
    @pulumi.getter(name="retentionPeriod")
    def retention_period(self) -> pulumi.Input[_builtins.str] | None:
        """
        Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
        """
        return pulumi.get(self, "retention_period")

    @retention_period.setter
    def retention_period(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "retention_period", value)


@pulumi.input_type
class _AccountsBackupScheduleState:
    def __init__(
        __self__,
        *,
        account_id: pulumi.Input[_builtins.str] | None = None,
        cluster_id: pulumi.Input[_builtins.str] | None = None,
        created_at: pulumi.Input[_builtins.str] | None = None,
        cron_expression: pulumi.Input[_builtins.str] | None = None,
        delete_backups_on_destroy: pulumi.Input[_builtins.bool] | None = None,
        deleted_at: pulumi.Input[_builtins.str] | None = None,
        retention_period: pulumi.Input[_builtins.str] | None = None,
        status: pulumi.Input[_builtins.str] | None = None,
    ):
        """
        Input properties used for looking up and filtering AccountsBackupSchedule resources.

        :param pulumi.Input[_builtins.str] account_id: Backup Schedule Schema Account ID field
        :param pulumi.Input[_builtins.str] cluster_id: Backup Schedule Schema Cluster ID field
        :param pulumi.Input[_builtins.str] created_at: Backup Schedule Schema Creation time field
        :param pulumi.Input[_builtins.str] cron_expression: Backup Schedule Schema Cron expression for the schedule field
        :param pulumi.Input[_builtins.bool] delete_backups_on_destroy: Whether to delete backups when the schedule is destroyed.
        :param pulumi.Input[_builtins.str] deleted_at: Backup Schedule Schema Deletion time field
        :param pulumi.Input[_builtins.str] retention_period: Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
        :param pulumi.Input[_builtins.str] status: Backup Schedule Schema Status field
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if cluster_id is not None:
            pulumi.set(__self__, "cluster_id", cluster_id)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if cron_expression is not None:
            pulumi.set(__self__, "cron_expression", cron_expression)
        if delete_backups_on_destroy is not None:
            pulumi.set(__self__, "delete_backups_on_destroy", delete_backups_on_destroy)
        if deleted_at is not None:
            pulumi.set(__self__, "deleted_at", deleted_at)
        if retention_period is not None:
            pulumi.set(__self__, "retention_period", retention_period)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Input[_builtins.str] | None:
        """
        Backup Schedule Schema Account ID field
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> pulumi.Input[_builtins.str] | None:
        """
        Backup Schedule Schema Cluster ID field
        """
        return pulumi.get(self, "cluster_id")

    @cluster_id.setter
    def cluster_id(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "cluster_id", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[_builtins.str] | None:
        """
        Backup Schedule Schema Creation time field
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="cronExpression")
    def cron_expression(self) -> pulumi.Input[_builtins.str] | None:
        """
        Backup Schedule Schema Cron expression for the schedule field
        """
        return pulumi.get(self, "cron_expression")

    @cron_expression.setter
    def cron_expression(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "cron_expression", value)

    @_builtins.property
    @pulumi.getter(name="deleteBackupsOnDestroy")
    def delete_backups_on_destroy(self) -> pulumi.Input[_builtins.bool] | None:
        """
        Whether to delete backups when the schedule is destroyed.
        """
        return pulumi.get(self, "delete_backups_on_destroy")

    @delete_backups_on_destroy.setter
    def delete_backups_on_destroy(self, value: pulumi.Input[_builtins.bool] | None):
        pulumi.set(self, "delete_backups_on_destroy", value)

    @_builtins.property
    @pulumi.getter(name="deletedAt")
    def deleted_at(self) -> pulumi.Input[_builtins.str] | None:
        """
        Backup Schedule Schema Deletion time field
        """
        return pulumi.get(self, "deleted_at")

    @deleted_at.setter
    def deleted_at(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "deleted_at", value)

    @_builtins.property
    @pulumi.getter(name="retentionPeriod")
    def retention_period(self) -> pulumi.Input[_builtins.str] | None:
        """
        Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
        """
        return pulumi.get(self, "retention_period")

    @retention_period.setter
    def retention_period(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "retention_period", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[_builtins.str] | None:
        """
        Backup Schedule Schema Status field
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[_builtins.str] | None):
        pulumi.set(self, "status", value)


@pulumi.type_token("qdrant-cloud:index/accountsBackupSchedule:AccountsBackupSchedule")
class AccountsBackupSchedule(pulumi.CustomResource):
    @overload
    def __init__(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        account_id: pulumi.Input[_builtins.str] | None = None,
        cluster_id: pulumi.Input[_builtins.str] | None = None,
        cron_expression: pulumi.Input[_builtins.str] | None = None,
        delete_backups_on_destroy: pulumi.Input[_builtins.bool] | None = None,
        retention_period: pulumi.Input[_builtins.str] | None = None,
        __props__=None,
    ):
        """
        Create a AccountsBackupSchedule resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Backup Schedule Schema Account ID field
        :param pulumi.Input[_builtins.str] cluster_id: Backup Schedule Schema Cluster ID field
        :param pulumi.Input[_builtins.str] cron_expression: Backup Schedule Schema Cron expression for the schedule field
        :param pulumi.Input[_builtins.bool] delete_backups_on_destroy: Whether to delete backups when the schedule is destroyed.
        :param pulumi.Input[_builtins.str] retention_period: Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
        """

    @overload
    def __init__(
        __self__,
        resource_name: str,
        args: AccountsBackupScheduleArgs,
        opts: pulumi.ResourceOptions | None = None,
    ):
        """
        Create a AccountsBackupSchedule resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param AccountsBackupScheduleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """

    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(
            AccountsBackupScheduleArgs, pulumi.ResourceOptions, *args, **kwargs
        )
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        account_id: pulumi.Input[_builtins.str] | None = None,
        cluster_id: pulumi.Input[_builtins.str] | None = None,
        cron_expression: pulumi.Input[_builtins.str] | None = None,
        delete_backups_on_destroy: pulumi.Input[_builtins.bool] | None = None,
        retention_period: pulumi.Input[_builtins.str] | None = None,
        __props__=None,
    ):
        opts = pulumi.ResourceOptions.merge(
            _utilities.get_resource_opts_defaults(), opts
        )
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError(
                "Expected resource options to be a ResourceOptions instance"
            )
        if opts.id is None:
            if __props__ is not None:
                raise TypeError(
                    "__props__ is only valid when passed in combination with a valid opts.id to get an existing resource"
                )
            __props__ = AccountsBackupScheduleArgs.__new__(AccountsBackupScheduleArgs)

            __props__.__dict__["account_id"] = account_id
            if cluster_id is None and not opts.urn:
                raise TypeError("Missing required property 'cluster_id'")
            __props__.__dict__["cluster_id"] = cluster_id
            if cron_expression is None and not opts.urn:
                raise TypeError("Missing required property 'cron_expression'")
            __props__.__dict__["cron_expression"] = cron_expression
            __props__.__dict__["delete_backups_on_destroy"] = delete_backups_on_destroy
            __props__.__dict__["retention_period"] = retention_period
            __props__.__dict__["created_at"] = None
            __props__.__dict__["deleted_at"] = None
            __props__.__dict__["status"] = None
        super().__init__(
            "qdrant-cloud:index/accountsBackupSchedule:AccountsBackupSchedule",
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package(),
        )

    @staticmethod
    def get(
        resource_name: str,
        id: pulumi.Input[str],
        opts: pulumi.ResourceOptions | None = None,
        account_id: pulumi.Input[_builtins.str] | None = None,
        cluster_id: pulumi.Input[_builtins.str] | None = None,
        created_at: pulumi.Input[_builtins.str] | None = None,
        cron_expression: pulumi.Input[_builtins.str] | None = None,
        delete_backups_on_destroy: pulumi.Input[_builtins.bool] | None = None,
        deleted_at: pulumi.Input[_builtins.str] | None = None,
        retention_period: pulumi.Input[_builtins.str] | None = None,
        status: pulumi.Input[_builtins.str] | None = None,
    ) -> "AccountsBackupSchedule":
        """
        Get an existing AccountsBackupSchedule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Backup Schedule Schema Account ID field
        :param pulumi.Input[_builtins.str] cluster_id: Backup Schedule Schema Cluster ID field
        :param pulumi.Input[_builtins.str] created_at: Backup Schedule Schema Creation time field
        :param pulumi.Input[_builtins.str] cron_expression: Backup Schedule Schema Cron expression for the schedule field
        :param pulumi.Input[_builtins.bool] delete_backups_on_destroy: Whether to delete backups when the schedule is destroyed.
        :param pulumi.Input[_builtins.str] deleted_at: Backup Schedule Schema Deletion time field
        :param pulumi.Input[_builtins.str] retention_period: Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
        :param pulumi.Input[_builtins.str] status: Backup Schedule Schema Status field
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AccountsBackupScheduleState.__new__(_AccountsBackupScheduleState)

        __props__.__dict__["account_id"] = account_id
        __props__.__dict__["cluster_id"] = cluster_id
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["cron_expression"] = cron_expression
        __props__.__dict__["delete_backups_on_destroy"] = delete_backups_on_destroy
        __props__.__dict__["deleted_at"] = deleted_at
        __props__.__dict__["retention_period"] = retention_period
        __props__.__dict__["status"] = status
        return AccountsBackupSchedule(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Output[_builtins.str]:
        """
        Backup Schedule Schema Account ID field
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> pulumi.Output[_builtins.str]:
        """
        Backup Schedule Schema Cluster ID field
        """
        return pulumi.get(self, "cluster_id")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Backup Schedule Schema Creation time field
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="cronExpression")
    def cron_expression(self) -> pulumi.Output[_builtins.str]:
        """
        Backup Schedule Schema Cron expression for the schedule field
        """
        return pulumi.get(self, "cron_expression")

    @_builtins.property
    @pulumi.getter(name="deleteBackupsOnDestroy")
    def delete_backups_on_destroy(self) -> pulumi.Output[_builtins.bool | None]:
        """
        Whether to delete backups when the schedule is destroyed.
        """
        return pulumi.get(self, "delete_backups_on_destroy")

    @_builtins.property
    @pulumi.getter(name="deletedAt")
    def deleted_at(self) -> pulumi.Output[_builtins.str]:
        """
        Backup Schedule Schema Deletion time field
        """
        return pulumi.get(self, "deleted_at")

    @_builtins.property
    @pulumi.getter(name="retentionPeriod")
    def retention_period(self) -> pulumi.Output[_builtins.str | None]:
        """
        Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
        """
        return pulumi.get(self, "retention_period")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Backup Schedule Schema Status field
        """
        return pulumi.get(self, "status")
