# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['AccountsAuthKeyArgs', 'AccountsAuthKey']

@pulumi.input_type
class AccountsAuthKeyArgs:
    def __init__(__self__, *,
                 cluster_ids: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        """
        The set of arguments for constructing a AccountsAuthKey resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] cluster_ids: Auth Keys Keys Schema Cluster Identifiers for which this Auth Key is attached field
        """
        pulumi.set(__self__, "cluster_ids", cluster_ids)

    @_builtins.property
    @pulumi.getter(name="clusterIds")
    def cluster_ids(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        Auth Keys Keys Schema Cluster Identifiers for which this Auth Key is attached field
        """
        return pulumi.get(self, "cluster_ids")

    @cluster_ids.setter
    def cluster_ids(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "cluster_ids", value)


@pulumi.input_type
class _AccountsAuthKeyState:
    def __init__(__self__, *,
                 cluster_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 created_at: Optional[pulumi.Input[_builtins.str]] = None,
                 prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering AccountsAuthKey resources.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] cluster_ids: Auth Keys Keys Schema Cluster Identifiers for which this Auth Key is attached field
        :param pulumi.Input[_builtins.str] created_at: Auth Keys Keys Schema Timestamp when the Auth Key is created field
        :param pulumi.Input[_builtins.str] prefix: Auth Keys Keys Schema Prefix of the Auth Key (the first few bytes from the token) field
        :param pulumi.Input[_builtins.str] token: Auth Keys Keys Schema Secret token for this Auth Key (handle with care!) field
        """
        if cluster_ids is not None:
            pulumi.set(__self__, "cluster_ids", cluster_ids)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter(name="clusterIds")
    def cluster_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Auth Keys Keys Schema Cluster Identifiers for which this Auth Key is attached field
        """
        return pulumi.get(self, "cluster_ids")

    @cluster_ids.setter
    def cluster_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "cluster_ids", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Auth Keys Keys Schema Timestamp when the Auth Key is created field
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Auth Keys Keys Schema Prefix of the Auth Key (the first few bytes from the token) field
        """
        return pulumi.get(self, "prefix")

    @prefix.setter
    def prefix(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "prefix", value)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Auth Keys Keys Schema Secret token for this Auth Key (handle with care!) field
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "token", value)


@pulumi.type_token("qdrant-cloud:index/accountsAuthKey:AccountsAuthKey")
class AccountsAuthKey(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cluster_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Create a AccountsAuthKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] cluster_ids: Auth Keys Keys Schema Cluster Identifiers for which this Auth Key is attached field
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AccountsAuthKeyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a AccountsAuthKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param AccountsAuthKeyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AccountsAuthKeyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cluster_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AccountsAuthKeyArgs.__new__(AccountsAuthKeyArgs)

            if cluster_ids is None and not opts.urn:
                raise TypeError("Missing required property 'cluster_ids'")
            __props__.__dict__["cluster_ids"] = cluster_ids
            __props__.__dict__["created_at"] = None
            __props__.__dict__["prefix"] = None
            __props__.__dict__["token"] = None
        super(AccountsAuthKey, __self__).__init__(
            'qdrant-cloud:index/accountsAuthKey:AccountsAuthKey',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            cluster_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            created_at: Optional[pulumi.Input[_builtins.str]] = None,
            prefix: Optional[pulumi.Input[_builtins.str]] = None,
            token: Optional[pulumi.Input[_builtins.str]] = None) -> 'AccountsAuthKey':
        """
        Get an existing AccountsAuthKey resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] cluster_ids: Auth Keys Keys Schema Cluster Identifiers for which this Auth Key is attached field
        :param pulumi.Input[_builtins.str] created_at: Auth Keys Keys Schema Timestamp when the Auth Key is created field
        :param pulumi.Input[_builtins.str] prefix: Auth Keys Keys Schema Prefix of the Auth Key (the first few bytes from the token) field
        :param pulumi.Input[_builtins.str] token: Auth Keys Keys Schema Secret token for this Auth Key (handle with care!) field
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AccountsAuthKeyState.__new__(_AccountsAuthKeyState)

        __props__.__dict__["cluster_ids"] = cluster_ids
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["prefix"] = prefix
        __props__.__dict__["token"] = token
        return AccountsAuthKey(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="clusterIds")
    def cluster_ids(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Auth Keys Keys Schema Cluster Identifiers for which this Auth Key is attached field
        """
        return pulumi.get(self, "cluster_ids")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Auth Keys Keys Schema Timestamp when the Auth Key is created field
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> pulumi.Output[_builtins.str]:
        """
        Auth Keys Keys Schema Prefix of the Auth Key (the first few bytes from the token) field
        """
        return pulumi.get(self, "prefix")

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Output[_builtins.str]:
        """
        Auth Keys Keys Schema Secret token for this Auth Key (handle with care!) field
        """
        return pulumi.get(self, "token")
