# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetAccountsDatabaseApiKeysV2Result',
    'AwaitableGetAccountsDatabaseApiKeysV2Result',
    'get_accounts_database_api_keys_v2',
    'get_accounts_database_api_keys_v2_output',
]

@pulumi.output_type
class GetAccountsDatabaseApiKeysV2Result:
    """
    A collection of values returned by getAccountsDatabaseApiKeysV2.
    """
    def __init__(__self__, account_id=None, cluster_id=None, id=None, keys=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if cluster_id and not isinstance(cluster_id, str):
            raise TypeError("Expected argument 'cluster_id' to be a str")
        pulumi.set(__self__, "cluster_id", cluster_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if keys and not isinstance(keys, list):
            raise TypeError("Expected argument 'keys' to be a list")
        pulumi.set(__self__, "keys", keys)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> _builtins.str:
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> _builtins.str:
        return pulumi.get(self, "cluster_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def keys(self) -> Sequence['outputs.GetAccountsDatabaseApiKeysV2KeyResult']:
        return pulumi.get(self, "keys")


class AwaitableGetAccountsDatabaseApiKeysV2Result(GetAccountsDatabaseApiKeysV2Result):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAccountsDatabaseApiKeysV2Result(
            account_id=self.account_id,
            cluster_id=self.cluster_id,
            id=self.id,
            keys=self.keys)


def get_accounts_database_api_keys_v2(account_id: Optional[_builtins.str] = None,
                                      cluster_id: Optional[_builtins.str] = None,
                                      id: Optional[_builtins.str] = None,
                                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAccountsDatabaseApiKeysV2Result:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['clusterId'] = cluster_id
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('qdrant-cloud:index/getAccountsDatabaseApiKeysV2:getAccountsDatabaseApiKeysV2', __args__, opts=opts, typ=GetAccountsDatabaseApiKeysV2Result, package_ref=_utilities.get_package()).value

    return AwaitableGetAccountsDatabaseApiKeysV2Result(
        account_id=pulumi.get(__ret__, 'account_id'),
        cluster_id=pulumi.get(__ret__, 'cluster_id'),
        id=pulumi.get(__ret__, 'id'),
        keys=pulumi.get(__ret__, 'keys'))
def get_accounts_database_api_keys_v2_output(account_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                             cluster_id: Optional[pulumi.Input[_builtins.str]] = None,
                                             id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                             opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAccountsDatabaseApiKeysV2Result]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['clusterId'] = cluster_id
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('qdrant-cloud:index/getAccountsDatabaseApiKeysV2:getAccountsDatabaseApiKeysV2', __args__, opts=opts, typ=GetAccountsDatabaseApiKeysV2Result, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetAccountsDatabaseApiKeysV2Result(
        account_id=pulumi.get(__response__, 'account_id'),
        cluster_id=pulumi.get(__response__, 'cluster_id'),
        id=pulumi.get(__response__, 'id'),
        keys=pulumi.get(__response__, 'keys')))
